### ISSUE TITLE
Caroussel responsive mode

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#1000]
on master => we have css conflict on carousel, its not responsive
![image](https://user-images.githubusercontent.com/2539440/103437136-159bd580-4c24-11eb-8fa1-23ee6aebf3c7.png)
good result need to be
![image](https://user-images.githubusercontent.com/2539440/103437151-43811a00-4c24-11eb-8573-34a0a835ffd8.png)

https://flexidemo.com3elles.com/realestate/

**Comment by ggppdk** [comment]
There is no bug, i mean this is configurable, and you can set to 1,
but i understand you want to set it to e.g. 3 and then reduced have it auto reduced

so i will mark this a new feature ...

![univ_mod_set_num_of_items_in_carousel](https://user-images.githubusercontent.com/5092940/103502420-ce972580-4e59-11eb-86f6-a4afba2ca79f.png)

**Comment by micker** [comment]
hi
but if we check code https://github.com/FLEXIcontent/flexicontent-cck/blob/b4c79e42bfe36eb36e1cfd8068ae321f5e677446/modules/mod_flexicontent/tmpl/carousel/carousel.css#L252
we have css for display only one item on smartphone ?

**Comment by ggppdk** [comment]
aahh, I see now,
...  so we have added code to this , but it is not working

this is a bug, i will fix this,

**Comment by micker** [comment]
yes i trying to check in css code we have
` .mod_flexicontent_standard_wrapper.cols_4
.mod_flexicontent_standard_wrapper.cols_5
.mod_flexicontent_standard_wrapper.cols_6
.mod_flexicontent_standard_wrapper.cols_7
.mod_flexicontent_standard_wrapper.cols_8
.mod_flexicontent_standard_wrapper.cols_9
.mod_flexicontent_standard_wrapper.cols_10
`
but i didn't find this class in output ...

**Comment by micker** [comment]
close for Flexicontent v4
