### ISSUE TITLE
Tag creation in item form is broken

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#1007]
hello in last master version tags creation is broken
/administrator/components/com_flexicontent/tasks/core.php?927acf7410ba9cd45bb9f444866e0e70=1&q=&task=viewtags&item_lang=*&lang=fr-FR&format=json:1 Failed to load resource: the server responded with a status of 500 ()
![image](https://user-images.githubusercontent.com/2539440/113204220-55974680-926d-11eb-93b3-d115f6c5918d.png)

**Comment by ggppdk** [comment]
I changed the code so that it works in J4
something must have broken
this should be easy to fix
