### ISSUE TITLE
Image Fallback option in category template not working

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#1008]
hello in last commit with fallback image option broke the image display
by defaut  in category template
choose an image field
choose no fallback (defaut option)
=> only display 'no image'
choose an image field
choose any other option for fallback
=> image filed is dsplayed

**Comment by ggppdk** [comment]
i will be working to close such issue next days. this will be out of the first to fix

**Comment by micker** [comment]
i add a FLEXI v4 blocker tag to bee more clear

**Comment by micker** [comment]
corrected via https://github.com/FLEXIcontent/flexicontent-cck/commit/86729476b3fb08e0df42c90e76c1fac1c96488e2
