### ISSUE TITLE
Template thumbnail

### ISSUE THREAD

**Issue by lungkao** [FLEXIcontent/flexicontent-cck#102]
blog-item
![blog-item](https://cloud.githubusercontent.com/assets/2047778/5604346/f9e5ea4a-93e9-11e4-8596-9d4449cb7953.png)

blog-category
![blog-category](https://cloud.githubusercontent.com/assets/2047778/5604347/f9e98556-93e9-11e4-96a7-3644000ba17f.png)

default-item
![default-item](https://cloud.githubusercontent.com/assets/2047778/5604345/f9e1ddc4-93e9-11e4-99de-760aa4373b6b.png)

default-category
![default-category](https://cloud.githubusercontent.com/assets/2047778/5604343/f9df2bec-93e9-11e4-9798-738e2711bb17.png)

items-tabbed-category
![items-tabbed-category](https://cloud.githubusercontent.com/assets/2047778/5604365/7841037e-93eb-11e4-9060-a41d0d358ebf.png)

faq-category
![faq-category](https://cloud.githubusercontent.com/assets/2047778/5988507/76f2b7f0-a995-11e4-899f-8fc742133630.png)

**Comment by micker** [comment]
great propose !

**Comment by vistamedia** [comment]
Hi Bubu ;) I'm about to commit your thumbnails but I noticed that one view is missing... (faq-category.png). Could you add this to the post? Cheers, Manu.

**Comment by lungkao** [comment]
![faq-category](https://cloud.githubusercontent.com/assets/2047778/5988348/1fed32a6-a98f-11e4-8afa-234b12081480.png)

**Comment by lungkao** [comment]
![faq-category](https://cloud.githubusercontent.com/assets/2047778/5988510/a3c7e0de-a995-11e4-81af-ad9307955cc8.png)

**Comment by ggppdk** [comment]
You icons were commited by Emmanuel, closing this
