### ISSUE TITLE
[FLEX 3.3.11]Menu Items are repeating

### ISSUE THREAD

**Issue by iamrobert** [FLEXIcontent/flexicontent-cck#1022]
I'm getting repeating menu items when adding to menu:

![Image](https://i.imgur.com/5t3bLwU.png)

But there is only 1 version of the pages.

- Joomla! 3.10.0 Stable [ Daraja ] 14-August-2021 11:55 GMT
- FLEXIcontent 3.3.11

Is there something I can do as I am meant to hand off to client ASAP?

**Comment by iamrobert** [comment]
More information:

If the item is in a single category - it appears only once. Each time we add it to another category it adds an additional item.

For instance: 3 Categories
![](https://i.imgur.com/1UwoSvV.png)

3 Appearances:
![](https://i.imgur.com/1UwoSvV.png)

1 Category:
![](https://i.imgur.com/WrAxcNW.png)

1 Appearance:
![](https://i.imgur.com/A5vlH3g.png)

At least the URLs are the same - so it doesn't matter which is selected.

**Comment by micker** [comment]
hello i tested in 3.3.11 bug confirmed not in futur version flexicontent 4
@ggppdk

**Comment by micker** [comment]
i think we can close this for flexicontent v4 @iamrobert  ?

**Comment by ggppdk** [comment]
Group By a.id was missing
It is now fixed. Fix will be in v4.0.1
