### ISSUE TITLE
[J4] Weblink field breaks item form when image option (joomla media) is enabled

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#1029]
need update code like image field

**Comment by micker** [comment]
corrected

**Comment by philippeg2** [comment]
Except now when I click on the image I open the editor.. still not working for me

**Comment by micker** [comment]
hello can you explain more ? the context ?
i tested in backed 
adding defaut image works
adding image on item works
=> you update flexicontent via master branch  ?

**Comment by philippeg2** [comment]
yes master but you can see it in the front end only; usually on j3 site it trigger a plugin ( event gallery) that show the gallery; with the master it open the editor ..

**Comment by micker** [comment]
maybe the problem is the plugin did you test it ?
open media manager is a normal behavior on j4

**Comment by philippeg2** [comment]
of course it worked on other part of the site

**Comment by micker** [comment]
we will check it (but not a priority sorry)

**Comment by philippeg2** [comment]
for my site it's a priority i use weblink all along the site without it.... in meantime the user will continue to update the J3 site and i will have to make the upgrade again

**Comment by micker** [comment]
but a specific use case... we try to check it but its not a bug (bug is corrected) but and an enchance

**Comment by philippeg2** [comment]
you don't know it this use case worked with j3; if it not working with j4 i will have to change all if i can find a workaround or remove fc and find a solution without fc

**Comment by micker** [comment]
hello don't be hurt i try to be honnet. We provide free component, free support we try do our best but we have works arround this we didn't win any money with flexicontent directly please respect this

**Comment by philippeg2** [comment]
on the free support we have already have an exchange on the flexicontent forum in french .....

**Comment by micker** [comment]
yes i know 
i do my best we correct all other thing, try other CCK component paid for it and wait for better support if you thing we are so bad
remember that you never say that you use plugin on this. You already say that you have a problem on this field (you have found a bugg cool). For a normal behavior its corrected
=> can you help me a little and explain more :
- plugin name
- user case 
etc ...

**Comment by philippeg2** [comment]
yes because i tought that the problem came only from weblink; before i came again to you i will make more test on my side

**Comment by micker** [comment]
we will find a solution i hope
reagrds

**Comment by philippeg2** [comment]
And the filter problem has not be solved yet ? Because for some test on weblink i need it ...

**Comment by micker** [comment]
It seems corrected Can you tested it

**Comment by philippeg2** [comment]
yes on an another site with a lot of filters seems to work well
