### ISSUE TITLE
[j4] Per template custom flexicontent.css isnt loaded since joomla 4.1

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#1035]
In j4.1 css file are moved to media folder
Flexicontent.css file arent loaded
media/templates/site/Cassiopeia/css for exemple

Need to check a solution
https://github.com/joomla/joomla-cms/issues/37057

**Comment by ggppdk** [comment]
Yannick, in our case the issue existed since J4.0.0 so i have updated the title of your issue

**Comment by ggppdk** [comment]
I am making a fix
