### ISSUE TITLE
[j4] adding image in image field is broken

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#1037]
Hello on 4.1 image adding is broken
1 adding multi image doesn't works (upload yes)
2 adding new value doesn't actived uploader
3 remove image is broken
`index.php?option=com_flexicontent&task=item.edit&view=item&id=3941:900 Uncaught TypeError: newField.find(...).fieldMedia is not a function
    at addField20 (index.php?option=com_flexicontent&task=item.edit&view=item&id=3941:900:43)
    at HTMLSpanElement.onclick (index.php?option=com_flexicontent&task=item.edit&view=item&id=3941:2539:416)
addField20 @ index.php?option=com_flexicontent&task=item.edit&view=item&id=3941:900
onclick @ index.php?option=com_flexicontent&task=item.edit&view=item&id=3941:2539`
![image](https://user-images.githubusercontent.com/2539440/155518463-827ebf2b-075a-4830-ae80-e287aaba5956.png)

**Comment by ggppdk** [comment]
Fixed with f364eb4
