### ISSUE TITLE
[j4] Filter and search on relation field after update

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#1038]
hello have after update j3 -> j4 relation field can be searchable and filtrable
select and result are empty
if user save item, value are good
i try to regenerate index but doesn't works

**Comment by ggppdk** [comment]
Fixed with 0694ae9

The remaining SQL queries that needed updating for publish_up , publish_down being NULL were patched
One of these cases is the filtering of the relation field
