### ISSUE TITLE
Frontend CSV Export : all core fields are added in the csv file despite core fields set to "No"

### ISSUE THREAD

**Issue by Bendebsp23** [FLEXIcontent/flexicontent-cck#1044]
Frontend Export items (CSV) : all core fields is added to the file despite I set these core fields to "No" (fields parameters : "Include in CSV export" >>> No).
Though It works good in backend.

**Comment by ggppdk** [comment]
Hello
this was fixed yesterday

please test with master branch, it should be good now
besides fixing this issue, CSV export will now
- respect (use) current filtering
- you have 2 buttons "export all (pages)" , "export current page"

**Comment by micker** [comment]
@Bendebsp23 can you do some return ?
