### ISSUE TITLE
Error when saving item after upgrading from J3/FC3.3.11 to J4/FC4.0.2

### ISSUE THREAD

**Issue by step-it** [FLEXIcontent/flexicontent-cck#1052]
After upgrading from Joomla 3 to Joomla 4 I get this error when saving an item:

```
Si è verificato un errore.
    0 Argument 1 passed to Joomla\Filter\InputFilter::__construct() must be of the type array, null given, called in /home/test/public_html/libraries/src/Filter/InputFilter.php on line 66 
```
The same action on Joomla 3 (latest available build) and FC 3.3.11 work normally.

**Comment by micker** [comment]
Hello Can you be more précise ?
Joomla version
Flexicontent version
Type of field in your content ?

**Comment by step-it** [comment]
Joomla/FC version were in topic title: Joomla 4 latest, FC 4 latest
For the type of fields used in that item, here the complete list used in that article type:
![immagine](https://user-images.githubusercontent.com/25658461/164057128-b52c60dc-a421-4dc7-a08c-030c504a1da7.png)

**Comment by step-it** [comment]
Please let me know if you need something more specific.

**Comment by micker** [comment]
Hello it realy strange i Cant reproduce it ... Can you update on New 4.1 flexi version aviable via github

**Comment by step-it** [comment]
Updatet FC to 4.1, still having the same issue:
	`Argument 1 passed to Joomla\Filter\InputFilter::__construct() must be of the type array, null given, called in /home/test/public_html/libraries/src/Filter/InputFilter.php on line 66 `

**Comment by step-it** [comment]
I think to have found where the issue arise.
The error shows up when using "SAFE HTML : remove dangerous tags/attributes" option in "Text (numbe/time/etc/custom validation)" field type. Setting this option value to "TEXT or ENCODED HTML : allow entities, stip tags" the error disappears.
Can you please provide a fix for that? Thanks :)

**Comment by micker** [comment]
hello we are a little busy but very thanks finding a solid way !

**Comment by micker** [comment]
hello @step-it its corrected on master
