### ISSUE TITLE
flexicontent 4.1 update and post installation

### ISSUE THREAD

**Issue by mekamak** [FLEXIcontent/flexicontent-cck#1053]
The flexicontent 4.1 update and post-installation version number appears to be 4.1.0b1
![Flexi](https://user-images.githubusercontent.com/12696950/164468253-68b3b522-eb3c-484b-b5a4-0f5fe1509d98.jpg)
.

**Comment by micker** [comment]
Hello yes its pre release we will update this
Thanks
