### ISSUE TITLE
[flexi4.1] Association table after migration J3 -> j4

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#1054]
hello after migrate a multilangue site to j4 content list doesn't work
![image](https://user-images.githubusercontent.com/2539440/164626207-152ca04c-e115-4691-a845-c8de4cc15cec.png)

**Comment by iamrobert** [comment]
@micker So if I try to convert a multi-lingual site to J4 it will fail. Still?

**Comment by ggppdk** [comment]
hhmm, this error depends on the MySql version (older one)

**Comment by ggppdk** [comment]
Hhmm this was fixed here 5df2df3fce878c49800d8312621da6d0647f7ece
