### ISSUE TITLE
Upload several images into image field  JScript Error

### ISSUE THREAD

**Issue by coweb01** [FLEXIcontent/flexicontent-cck#1055]
when configuring an image field with image source "Joomla media manager", or "Item+Field specific folder" and "allow multiple values" it is not possible to upload or assign multiple images from the media manager. The error "newField.find(...)fieldMedia is not a function" appears in the console.
With the setting image Source Reusable (DB mode) the whole thing works.  Flexicontent Version 4.1.0b1

**Comment by micker** [comment]
thanks for reporting : post https://www.flexicontent.org/forum/21-troubleshooting/58249-add-image-error-fieldmedia-is-not-a-function.html#82167

**Comment by micker** [comment]
Hello Can you test New release on master ?

**Comment by coweb01** [comment]
yes I can test it. which version?

**Comment by micker** [comment]
hello this
https://github.com/FLEXIcontent/flexicontent-cck/archive/refs/heads/master.zip
