### ISSUE TITLE
Joomla 4 compatibility checker

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#1060]
more informations
System - Flexisystem, core tasks 
System - Flexiadvroute, routing tasks
return fals positif error on j4 checker
![image](https://user-images.githubusercontent.com/2539440/172695465-5b5eef49-a068-49cc-afad-fa867be91c2d.png)

**Comment by ggppdk** [comment]
It seems the criteria is to show this message 
if plugin is a non-Joomla core 'system','user','authentication','actionlog','twofactorauth' plugin

**Comment by micker** [comment]
ok just need to close it ?
