### ISSUE TITLE
Additional message on filtering

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#1067]
on flexicontent 4 in front we have an additionnal message on filter just after loading animation
see my screen
https://www.loom.com/share/2ae6ce3a29e04f7195e2489847c5f034

**Comment by ggppdk** [comment]
Yes "Applying filtering" was shown for a couple of seconds on first website load because CSS file has not loaded yet
Fixed with 19e0943ab8749c57f5de511dc657edcb49e55219

**Comment by micker** [comment]
Message is return ..
https://www.loom.com/share/6dd558d77c1f490886b44e1d90f0910b

**Comment by ggppdk** [comment]
hhmm, this is a different case, it thinks you have logged off and it redirects to new URL to force bypass of browser cache
something needs to be fixed about the detection (this was broken in some recent commit)
