### ISSUE TITLE
joomla 4.2 + FLEXI 4.1.1 if make menu  single article on joomla content show 404

### ISSUE THREAD

**Issue by lungkao** [FLEXIcontent/flexicontent-cck#1068]
joomla 4.2 + FLEXI 4.1.1 if make menu  single article on joomla content show 404. but can see if login on frontpage

![Screen Shot 2565-07-14 at 07 31 05](https://user-images.githubusercontent.com/2047778/178859590-e608c1c7-3892-401d-8357-b3bf53919feb.png)
![Screen Shot 2565-07-14 at 07 31 40](https://user-images.githubusercontent.com/2047778/178859630-6212712c-deab-4f3d-8ae2-3f58e7aca453.png)
![Screen Shot 2565-07-14 at 07 32 20](https://user-images.githubusercontent.com/2047778/178859680-9dee3a0c-0189-4319-a2b5-29b3b96c5d7c.png)

**Comment by micker** [comment]
did you actived error repoting to see error ?
i have this
![image](https://user-images.githubusercontent.com/2539440/179685332-5e82e99f-8514-46e8-9851-4a52c86bcd8e.png)

**Comment by lungkao** [comment]
![Screen Shot 2565-07-19 at 16 59 45](https://user-images.githubusercontent.com/2047778/179724240-41be234d-9764-4d73-bb37-5a1b86ee16c5.png)


> did you actived error repoting to see error ? i have this ![image](https://user-images.githubusercontent.com/2539440/179685332-5e82e99f-8514-46e8-9851-4a52c86bcd8e.png)

**Comment by lungkao** [comment]
if change  Permissions Public Group Edit state Allowed not 404 
![Screen Shot 2565-08-10 at 13 27 48](https://user-images.githubusercontent.com/2047778/183854139-7b92cf35-a5b0-4963-83d1-df88445e991b.png)

**Comment by lungkao** [comment]
administrator/components/com_flexicontent/models/parentclassitem.php
change 
$nullDate    = $this->_db->getNullDate();
to
$nullDate = NULL;
![Screen Shot 2565-08-11 at 09 51 37](https://user-images.githubusercontent.com/2047778/184057123-5d218bff-2a20-41c3-b8ef-547041fba54e.png)

**Comment by lungkao** [comment]
edit. administrator/components/com_flexicontent/models/parentclassitem.php
change
#$nullDate    = $this->_db->getNullDate();
to
$nullDate = NULL;
![Screen Shot 2565-08-11 at 09 51 37](https://user-images.githubusercontent.com/2047778/184058259-832c045e-d579-4ed5-a59f-a8147348bcf7.png)

**Comment by micker** [comment]
hello great ! maybe need to check if $this->_db->getNullDate() exist or NULL ? @ggppdk
