### ISSUE TITLE
Phpthumbs doesn't works on PHP8.1

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#1078]
releated to https://github.com/JamesHeinrich/phpThumb/issues/189

**Comment by twiddly** [comment]
Also not working on php 8.1.9, lots of php errors and warnings.

I tried editing to remove errors, and succeeded in that, but clearly didn't do it correctly as it still didn't work.

**Comment by micker** [comment]
@twiddly if you can test last master correction is inside
