### ISSUE TITLE
Image Field Typ: Joomla Images not visible in frontend after new saving the item 

### ISSUE THREAD

**Issue by coweb01** [FLEXIcontent/flexicontent-cck#1082]
There is a problem with the field type Image/Gallery Source: Joomla Article Images (intro/full). After creating new an article, the image in the template is displayed in the frontend. As soon as you edit the article and save it again, no image is displayed. I have no explanation why this is the case.
The image is still in the article, the file path says something like: images/photogalleries/mediaman/m_l_nasa1-400.jpg#joomlaImage://local-images/photogalleries/mediaman/m_l_nasa1-400.jpg?width=400&height=400. When the image is selected again and the article is saved, the image is there again.

Joomla Version: 4.2.3
Flexicontent: 4.1.3
PHP: 7.4.32

**Comment by micker** [comment]
bug confirmed

**Comment by coweb01** [comment]
I have tested it on my test page. I can give you access for testing

The category picture also does not appear when you select it.
For the article image, the image is not displayed if the field for the image is of type Image with Image Source "Joomla article images".

We have had this problem since the last Joomla update.

**Comment by micker** [comment]
Yes send me an Access for testing

**Comment by coweb01** [comment]
Yes to which email address?

**Comment by micker** [comment]
yannick@com3elles.com

**Comment by micker** [comment]
can we close it ?

**Comment by coweb01** [comment]
Yes thanks.
