### ISSUE TITLE
Item create by flexicontent can display in joomla category view

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#1084]
I tested it on a local MAMP installation and the same problem. There is no active php cache.
A new item does not appear in the category view.
Here's what I found.
After saving the new item, in the database table „ flexicontent_items_tmp“,  in the rows modified  and publish_down appears  „1000-01-01 00:00:00“.
This causes it will not to be included in the category view query.
After you log out and log back in to the backend, you need to "Update Temporary Item Data" and refresh.
After that,“ 0000-00-00 00:00:00“ will appear in the database in the modified and publish_down row. The article will now be displayed correctly in the frontend.
I think this is the problem. You can see it in the screenshots.

https://www.flexicontent.org/forum/20-general-support/58376-news-items-in-category-view-not-visible.html?start=10

**Comment by web54** [comment]
get the same issue
articles done in 4.1.1
new articles done with master are well displaid
there are differences in database : image_2022-11-23_100729475.png image_2022-11-23_100823369.png
for old articles : I managed the issue with two ways : check the box for each article in database (i guess it can be done with a request)
OR allow admin to manage joomla articles, going into each article with com_content, and save.

https://www.flexicontent.org/forum/20-general-support/58376-news-items-in-category-view-not-visible.html?start=10#83027

**Comment by micker** [comment]
we plan a new option to disable tmp database => that only needed for very large site ... 80% of site doesn't need it

**Comment by micker** [comment]
relevant to this too
https://github.com/FLEXIcontent/flexicontent-cck/issues/1086

**Comment by micker** [comment]
@web54 Can you test master branch seems correctes b9bd60cc5d6dae54516d0ed6f58b018eb1f1683a
