### ISSUE TITLE
Save & New button is not displayed 

### ISSUE THREAD

**Issue by lipatovroman** [FLEXIcontent/flexicontent-cck#1095]
Save & New button is not displayed for new items.
When editing existing item, the button is displayed correctly.

**Comment by micker** [comment]
Hello 
Can you post some screen i dont understand

**Comment by lipatovroman** [comment]
> Hello Can you post some screen i dont understand

I recorded a video for you: https://directory.audio/images/monopics/2023-04-04_19-20-10.mp4

The button "Save and New" is not displayed when you're creating new item.
But it's ok when editing existing item.

**Comment by micker** [comment]
Its a normal behavior you need to add item AT first 
Save and New need to be save AT first  to return same setting

**Comment by lipatovroman** [comment]
> Its a normal behavior you need to add item AT first Save and New need to be save AT first to return same setting
Sorry, but it's not normal behavior.
It worked fine in Flexicontent 3.3.xx
What's the point of the button "Save & New" if I have to add an item to get this button?
I can just save an item and then press new item from the list view. Same steps.
I recorded video with FC 3.3.xx - https://directory.audio/images/monopics/2023-04-04_19-33-59.mp4

**Comment by micker** [comment]
but flexicontent 4 have a new form system more flexible (you can customize all form and all fields in front and backend )and this behavior was removed for now

**Comment by lipatovroman** [comment]
> but flexicontent 4 have a new form system more flexible (you can customize all form and all fields in front and backend )and this behavior was removed for now

As we can see, this behavior was not removed. 
It works only in existing items. 
It's a bug. We discussed this with Georgios.
It's a very useful option. Especially when you have to add a lot of items.

**Comment by micker** [comment]
hello => can you test this ?https://github.com/FLEXIcontent/flexicontent-cck/commit/7308426d31e7ce39e6cb1dcc645b16dfa1b9229b
