### ISSUE TITLE
No aliases under item names in lists

### ISSUE THREAD

**Issue by lipatovroman** [FLEXIcontent/flexicontent-cck#1098]
Hello!
No aliases under item names in lists

![2023-04-04 18-52-00](https://user-images.githubusercontent.com/6747127/229848126-3dfcd10c-321e-4ff2-ae2b-5df92bcc8cc8.jpg)

This is how it looks in Joomla

![2023-04-04 18-53-31](https://user-images.githubusercontent.com/6747127/229848534-f08a8243-08c2-4fb4-918e-7de4413a3e21.jpg)

**Comment by micker** [comment]
We didnt add this its not a bug its a feature WE will study it

**Comment by micker** [comment]
done here https://github.com/FLEXIcontent/flexicontent-cck/commit/783e57e428ee5ec4fa821312c5aed5eea334e939
