### ISSUE TITLE
Extract image on joomla fild is broken (imagefield and category image)

### ISSUE THREAD

**Issue by krae11** [FLEXIcontent/flexicontent-cck#1103]
Category has a description and selected an image in the category image field.

Within the category  menu item, I've selected display category image, but the image does not appear.

I have also tried selecting an image in the menu item parameters.  It will not display either.  

In configuration, category image source is set to try param then extract.

The image will appear if I place it within the category description, but that is not ideal

**Comment by micker** [comment]
i add that same problem i nimage field in image/intro mode
maybe something change in joomla

**Comment by micker** [comment]
@krae11 can you send me an email for testing ?

**Comment by krae11** [comment]
do you want to test on one of my sites or want me to test it?

**Comment by micker** [comment]
i can send you 2 files for remplace it

**Comment by krae11** [comment]
kaitie.babin@voxinteractif.com

**Comment by micker** [comment]
sended

**Comment by micker** [comment]
@krae11 some return ?

**Comment by micker** [comment]
Validate we can cloqse it ?

**Comment by krae11** [comment]
yes
