### ISSUE TITLE
Error after update joomla 3.10.11 To 4.3.2 and Flexicontent 4.1.3 to 4.1.5

### ISSUE THREAD

**Issue by alaingrach** [FLEXIcontent/flexicontent-cck#1114]
Hello,
I have do an Update from Joomla  3.10.11 To 4.3.2 and from Flexicontent  4.1.3 to 4.1.5.
PHP is 8.1.16 and Mysql is 5.7.42-log

When I try to edit and save an item (old or new) if i choose "Save and Close" I have this error message : 
Une erreur est survenue
    0 Joomla\Filter\InputFilter::__construct(): Argument #1 ($tagsArray) must be of type array, null given, called in /home/whoswort/www/lesunimog_fr/libraries/src/Filter/InputFilter.php on line 69 

if I choose "Save" (without close) I stay in an infinite loop while saving.

When I list the "champs" (in french version) of Flexicontent, I Have this error for some "champs" (like "Description", "Tags", "Categories", "Favoris", "État", "Version", "Type de document, "Hits", "Titre", "Modifié par", "Dernière modification", "Créé par", "Date de création") :
Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /home/whoswort/www/lesunimog_fr/administrator/components/com_flexicontent/helpers/html/fcfields.php on line 212
created

**Comment by micker** [comment]
Please do not post twice here and in forum
I already reply on this  and WE Can check more
Regards
