### ISSUE TITLE
FLEXIcontent + j4: Tooltips

### ISSUE THREAD

**Issue by iamrobert** [FLEXIcontent/flexicontent-cck#1116]
Hi,

I'm trying to build a site in Joomla 4 - but I see tooltips are missing not working in Administrator:

![IMG](https://i.imgur.com/yI7syBI.png)

1) ATUM doesn't have tooltips:
https://github.com/joomla-projects/j4adminui/issues/184

2) Bootstrap 4 recommends popover:
https://getbootstrap.com/docs/4.0/components/tooltips/

Is it something that I should implement?

**Comment by micker** [comment]
Hello yes j4 remove tooltip
If you do a pr it can bé appreciate

**Comment by iamrobert** [comment]
@micker

For the item page - the problem is this is missing from the joomla-script-options:

`"bootstrap.tooltip":{".hasTooltip":{"animation":true,"container":"body","html":true,"trigger":"hover focus","boundary":"clippingParents","sanitize":true}},`

When I add that code to a html page it seems to work:

https://youtu.be/ubD_v7Oy44M

How to insert this into FLEXIContent itempage - I'm yet to identify. Its probably above my paygrade.

Any ideas?

**Comment by micker** [comment]
i found a base in 
-> administrator\components\com_flexicontent\views\item\tmpl\layouts\tabs\main.php and add this
```
use Joomla\CMS\HTML\HTMLHelper;
HTMLHelper::_('bootstrap.tooltip', '.hasTooltip');
```
can you confirm it ?
can help me for front view ? (item, category and module)

**Comment by iamrobert** [comment]
Hey @micker,

Thanks for sharing that solution! It works for the item view.

Unfortunately, we don't have frontend editing enabled, so I can't confirm if it works for the front view (item, category, and module). However, as I continue working on the site, I'll test it in other areas and see if it functions as expected.  I'm working on a module next,

Since this is my first Joomla 4 site, it's taking a bit longer to fully understand everything. But I'm getting there!

Also, I noticed that the spacing seems off: 

![](https://i.imgur.com/YYog6ND.png) 

I'll take a stab at switching to font awesome icons and updating it. Will share a PR when done.

Thanks again for your help!

**Comment by iamrobert** [comment]
The field view seems broken as well.

I added this to administrator/components/com_flexicontent/views/field/tmp/default.php

```
use Joomla\CMS\HTML\HTMLHelper;
HTMLHelper::_('bootstrap.tooltip', '.hasTooltip');
```

and it works in places.

However - I don't think its coded in a way to read tooltips. As **.hasPopover** class is used:

![](https://i.imgur.com/SLILZQW.png)

**Comment by micker** [comment]
yes i think we need to remove popover for tooltips. @ggppdk are you agree ?

**Comment by micker** [comment]
can we close it ?

**Comment by iamrobert** [comment]
Perhaps. Other areas of the admin I haven't tested and require it. eg
fields.
