### ISSUE TITLE
FLEXIcontent versions fails

### ISSUE THREAD

**Issue by iamrobert** [FLEXIcontent/flexicontent-cck#113]
I go to versioning in FLEXIcontent Item Manager and it returns a blank URL:

![download](https://cloud.githubusercontent.com/assets/8617673/5819897/3d4b8d7a-a0fc-11e4-8d88-e277055b210f.png)

The URL returns:
index?option=com_flexicontent&task=items.edit&cid=1061&version=1&80740342c6a36928d2223b25490a57bf=1

The view comparison works.

Any ideas?

**Comment by iamrobert** [comment]
Sorry - its just one version of a FLEXIcontent site

**Comment by ggppdk** [comment]
This was fixed in a later commit, do you have latest commit ?

**Comment by iamrobert** [comment]
OK - I have upgraded + the problem is solved...
