### ISSUE TITLE
FLEXIContent Hidden Classes missing in J4

### ISSUE THREAD

**Issue by iamrobert** [FLEXIcontent/flexicontent-cck#1141]
Hi,

Bootstrap no longer uses hidden-tablet or hidden-phone classes for visibility. So - the backend templates break in J4 on smaller screens. The new utility classes are: https://getbootstrap.com/docs/5.0/utilities/display/

A quick fix would  be to carry over the old BS CSS into the LESS Code. I've revised the [breakpoints](https://getbootstrap.com/docs/5.0/layout/breakpoints/) to match BS5.

```
#flexicontent {
	  .hidden-desktop {
		display: none !important;
	  }

	  @media (min-width: 768px) and (max-width: 991.98px) {
		.hidden-desktop {
		  display: inherit !important;
		}
		.hidden-tablet {
		  display: none !important;
		}
	  }
	  @media (max-width: 767.98px) {
		.hidden-desktop {
		  display: inherit !important;
		}
		.hidden-phone {
		  display: none !important;
		}
	  }
}
```

**Comment by micker** [comment]
hello can you propose a PR in j4.less and css ?

**Comment by iamrobert** [comment]
Hey @micker,

Creating a PR for `j4.less` and CSS directly won't be feasible for me. I'm in the middle of developing a custom J4 Admin Template, and it's different from the current FLEXIContent.

For the CSS, I use [Prepros](https://prepros.io/) to compile. So the code output won't match the existing CSS, and my codebase has diverged a fair bit from the original. 

I can add a PR to the LESS file – but I’m sure you’ll be better at where you want to place the code. 

If there's another way I can contribute or assist, I'm all ears.

**Comment by iamrobert** [comment]
PR: https://github.com/FLEXIcontent/flexicontent-cck/pull/1142

**Comment by micker** [comment]
ok i will generate and commit css modification ! very thanks

**Comment by iamrobert** [comment]
Here's a quick tip for improving UX on the items/fields category pages in J4 FLEXIContent.

When the page loads, we can automatically add a JavaScript snippet to shrink the Side Menu to its compressed state. It makes navigating those category pages a bit easier. Here's the code snippet:

```
<script>
	document.addEventListener('DOMContentLoaded', function() {
  var sidebar = document.querySelector('#sidebar-wrapper'); 
  var wrapper = document.querySelector('#wrapper'); 
  if (sidebar) {
    wrapper.classList.add('closed'); // Add the class that shrinks your sidebar
  }
});
</script>
```

**Comment by micker** [comment]
hello @iamrobert i tested your code for sidebar . its interesting but it change joomla core behavior user can't use official button to open and close this sidebar ... Maybe the solution can be
- adding an option in flexicontent to set this
- update script to respect current user click
- adding script with option condition

**Comment by micker** [comment]
i commit css modification

**Comment by micker** [comment]
I open an discution in facebook group for some return (for sidebar closing)
