### ISSUE TITLE
Joomla 5 compatibilty

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#1148]
Hello i am testing joomla 5 and flexicontent
here all reference : https://manual.joomla.org/migrations/44-50/compat-plugin#class-aliases

### Back-end

- [x] Installation
- [x] Dashboard
- [x] Items / filters
- [x] Item
- [x] Save Item
- [x] Categories / filters
- [x] Categorie
- [x] Types
- [x] Type
- [x] Fields / filters
- [x] Field
- [x] Tags
- [x] Save Tag
- [x] Templates
- [x] Template
- [x] Users
- [x] User
- [x] Save User
- [x] Groups
- [x] Group
- [x] Save group
- [x] Files
- [x] File
- [x] Import
- [x] Search
- [x] Stats
- [x] Configuration
- [x] Darkmode css 

### Front-end

- [x] Categorie
- [x] Item
- [x] Filter module
- [x] Map module
- [x] Category module
- [x] Search module
- [x] Tag module
- [x] Submission view

i will continu my test

**Comment by micker** [comment]
Dark css for adin is on road 80% is done

**Comment by Laurent-Cosmic** [comment]
Salut
excellente nouvelle
je ne sais pas si tu l'avais noté mais les filtres sur la photo ne fonctionnaient pas
![image](https://github.com/FLEXIcontent/flexicontent-cck/assets/55958422/e0f708d7-1f5a-4e5b-ab4a-14ce35ba5c5d)

**Comment by VanShane** [comment]
## A vérifier

### Admin :
- éditeur (TinyMCE) ne charge pas dans les vues d'édition (je n'ai pas encore testé les autres)
- impossible d'enlever tout les tags d'un élément
- impossible de supprimer les Fichiers (dans la vue files)

**Comment by micker** [comment]
Petit retour le bug de filtrage est corrigé
Le package sera compatible de j3 a j5 sans plugin
Plus un lot de correction diverse. Il ne nous reste que le formulaire de suppression de fichier et les tags sinon tout roule
