### ISSUE TITLE
batch-copy items is buggy: new category is ignored

### ISSUE THREAD

**Issue by Icehoi** [FLEXIcontent/flexicontent-cck#1150]
batch-copy items is buggy: category is ignored.

reproduce:
- in backend-item-list, select multiple items,
- at screen top, select batch > update/copy/move
- in batch-options-screen,
-- 1) select "copy",
-- 2) change main category

expected:
- item copies should be in newly selected category

reality:
- item copies still are in old category

[setup]
J 4.3.4
FC 4.2.1

**Comment by micker** [comment]
Bug confirmed
