### ISSUE TITLE
Deprecated: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#1151]
Need to update this for php8.1
https://github.com/FLEXIcontent/flexicontent-cck/blob/65a65ec0e7e00848aeef5399d4e77f9194783a7e/site/flexicontent.php#L281

**Comment by VanShane** [comment]
easy to fix, just cast second parameter of preg_match to string.
e.g.:  `preg_match("/Itemid=([0-9]+)/", (string) $pathway_arr[0]->link, $matches)`

**Comment by micker** [comment]
adding here on master 
https://github.com/FLEXIcontent/flexicontent-cck/commit/b9663b5df251d083c2781bfcc361e2923003e621
thanks @VanShane
