### ISSUE TITLE
File field display items multiple times when not logged

### ISSUE THREAD

**Issue by NGXG** [FLEXIcontent/flexicontent-cck#116]
Hi, 

There is a display bug when using file plugin, if items are downloadable only for logged user.
When i'm not logged, i have something like a loop.
First downloadable file display well; the second downloadable file display first file and itself; the third display the first and the second then itself, etc...

When logged in, everything works perfectly.
I tried with file.php from 2.2.0 and from GitHub, got the same things.

Here is a pic to be more clear, based on how HTML is rendered : 
![loop](https://cloud.githubusercontent.com/assets/9053585/5916421/58dcf032-a611-11e4-99af-984453fce845.gif)

**Comment by NGXG** [comment]
I was searching again why it does this and i have more informations. It seems like when not authorized to download, the variable $str isn't cleared at each loop.

Here is what i've got in file.php :
$field->{$prop}[]	=  $pretext . $str . $posttext;

My pretext is '<div class="dwnld">' and my posttext is '</div>'.
On each loop, $str append html of the new value instead of replacing it.

I don't find where in the file I can fix it...

**Comment by ggppdk** [comment]
// [1]: either create the download link -or- use no authorized link ...
if ( !$authorized ) {
	$dl_link = $noaccess_url;
..............


should be:


// [1]: either create the download link -or- use no authorized link ...
$str = '';
if ( !$authorized ) {
	$dl_link = $noaccess_url;
.............
