### ISSUE TITLE
Joomla 5 - Search and filter by category do not work in backend

### ISSUE THREAD

**Issue by elegantviolence** [FLEXIcontent/flexicontent-cck#1161]
On version 4.2.1 of Joomla 5, in the backend in the “Categories” section, five identical categories with the name “Uncategorised”, one category “ROOT” appear, and search and filtering completely stop working.
Everything works on Joomla 4.4, so the problem is in the fifth version.

**Comment by micker** [comment]
hello this is corrected on 4.5n branch (ETA beta)
