### ISSUE TITLE
Update Module to Super User breaks Update in backend

### ISSUE THREAD

**Issue by iamrobert** [FLEXIcontent/flexicontent-cck#1168]
Hi @ggppdk 

As a Super User I can no longer edit FLEXIContent Universal modules with this update:

[Super admins only](https://github.com/FLEXIcontent/flexicontent-cck/commit/22f74e25262f2fdfff0adce33f25e3b841c281a7)

I keep getting the error message when I click Update:
You can not edit this in frontend. Please login as a super admin

[Video of Issue](https://youtu.be/OJRYV0KpPPM)

**Screenshots:**
![](https://i.imgur.com/rpf8Wii.png)
![](https://i.imgur.com/UkV8rW1.png)

**Comment by iamrobert** [comment]
Your code works - have old code for some reason.

**Comment by micker** [comment]
Hello dis you test master branch ? That correctedLe 24 déc. 2023 17:34, Robert Stark ***@***.***> a écrit :
Hi @ggppdk
As a Super User I can no longer edit FLEXIContent Universal modules with this update:
Super admins only
I keep getting the error message when I click Update:
You can not edit this in frontend. Please login as a super admin
Video of Issue
Screenshots:

**Comment by iamrobert** [comment]
hi @micker 

For clarification, this version works:

`if ( (!$hasTemplates || !Factory::getUser()->authorise('core.admin')) && (isset($_POST['jform']['params']['php_rule']) || isset($_REQUEST['jform']['params']['php_rule']) ))			`

**Comment by ggppdk** [comment]
Your report revealed another (different) issue that existed:
- non-super admins in backend
despite having core.admin on templates will not be able to edit the module

Fixed it here and added backend message too
https://github.com/FLEXIcontent/flexicontent-cck/commit/5b473198a3a5d4bf7c96bbf1bc4831927077ba39
