### ISSUE TITLE
latest beta - backend - items lists - dark blue background on hover

### ISSUE THREAD

**Issue by nzimas** [FLEXIcontent/flexicontent-cck#1177]
After installing the latest master (2024.01.08), I've noticed that all item lists (articles, categories and so forth) on the backend display a blue background when the item is hovered.
See attached screenshot.

Environment: 
FC Github master as of 2024.01.08.
Joomla 4.4.1
<img width="927" alt="Screenshot 2024-01-09 at 11 52 28" src="https://github.com/FLEXIcontent/flexicontent-cck/assets/6955694/590b3453-d8da-4afc-a153-6f0abd69d64e">

**Comment by micker** [comment]
yes we prepare flexionctent backend for dark theme
if you schema is dark that used but joomla 4.X doesn't have a dark theme ...

**Comment by nzimas** [comment]
I see.

It “respects” my OS and browser theme choices, right?
They are both set to dark mode, indeed.

**Comment by micker** [comment]
yes but j4 doesn't have dark theme

**Comment by micker** [comment]
hello solved with https://github.com/FLEXIcontent/flexicontent-cck/commit/eef3978eb5b467c7d13c51dffd6a8fb5189b3762
