### ISSUE TITLE
After update to joomla4.4.1 language string not work.

### ISSUE THREAD

**Issue by desbear** [FLEXIcontent/flexicontent-cck#1178]
![CleanShot-2024-01-10-at-22-27-06@2x](https://github.com/FLEXIcontent/flexicontent-cck/assets/545068/73eba7ed-35dd-40e6-97ef-04f5c20edbdf)
this problem also on joomla4.4.2
Do I need to adjust any settings?

**Comment by micker** [comment]
you need to update your language file (download and install it) https://www.flexicontent.org/downloads/translations.html
