### ISSUE TITLE
Posting in FB - 404 requested page not found

### ISSUE THREAD

**Issue by lipatovroman** [FLEXIcontent/flexicontent-cck#1179]
Hello!
When I post in the Facebook FC main page, I'm getting error - 404 requested page not found.

![2024-01-11_17-22-14](https://github.com/FLEXIcontent/flexicontent-cck/assets/6747127/a89cde7f-8f07-42ae-bafa-cab22561a5b3)

This only happens with FlexiConten. Other components behave correctly.

So, when we post the main page of site [https://directory.audio](https://directory.audio) the link goes like this - https://directory.audio/?fbclid=IwAR1w9zh5Bn9GxrRs1bZLI0nNxhfrKLlQapqDyFUcbf5U356h6orhN48ul8s

Maybe that's the reason.

**Comment by micker** [comment]
I close this because replay IS on forum
