### ISSUE TITLE
bug on international adress

### ISSUE THREAD

**Issue by web54** [FLEXIcontent/flexicontent-cck#1180]
wanted to create a field : international adress
I have this error : 0 Class "Joomla\CMS\Form\FormFieldFcSortableList" not found

it runs in a loop and I get the above error when saving

in console : A form field element should have an id or name attribute
A form field element has neither an id nor a name attribute. This might prevent the browser from correctly autofilling the form.
To fix this issue, add a unique id or name attribute to a form field. This is not strictly needed, but still recommended even if you have an autocomplete attribute on the same element.

**Comment by micker** [comment]
Hello Can you put some screen about your error ? I update 5 sites with this field without error
Maybe it on field création

**Comment by micker** [comment]
AT first actived débug mode to see complet error
Thanks

**Comment by web54** [comment]
<html>
<body>

() | JROOT/administrator/components/com_flexicontent/elements/fccountries.php:38
-- | --
2 | require_once() | JROOT/libraries/src/Form/FormHelper.php:271
3 | Joomla\CMS\Form\FormHelper::loadClass() | JROOT/libraries/src/Form/FormHelper.php:136
4 | Joomla\CMS\Form\FormHelper::loadType() | JROOT/libraries/src/Form/FormHelper.php:78
5 | Joomla\CMS\Form\FormHelper::loadFieldType() | JROOT/libraries/src/Form/Form.php:1451
6 | Joomla\CMS\Form\Form->loadField() | JROOT/libraries/src/Form/Form.php:293
7 | Joomla\CMS\Form\Form->getFieldset() | JROOT/plugins/system/jce/jce.php:225
8 | PlgSystemJce->onContentPrepareForm() | JROOT/libraries/src/Plugin/CMSPlugin.php:289
9 | Joomla\CMS\Plugin\CMSPlugin->Joomla\CMS\Plugin\{closure}() | JROOT/libraries/vendor/joomla/event/src/Dispatcher.php:486
10 | Joomla\Event\Dispatcher->dispatch() | JROOT/libraries/src/Application/EventAware.php:111
11 | Joomla\CMS\Application\WebApplication->triggerEvent() | JROOT/libraries/src/MVC/Model/FormBehaviorTrait.php:169
12 | Joomla\CMS\MVC\Model\FormModel->preprocessForm() | JROOT/administrator/components/com_flexicontent/models/base/base.php:794
13 | FCModelAdmin->preprocessForm() | JROOT/administrator/components/com_flexicontent/models/field.php:313
14 | FlexicontentModelField->preprocessForm() | JROOT/libraries/src/MVC/Model/FormBehaviorTrait.php:107
15 | Joomla\CMS\MVC\Model\FormModel->loadForm() | JROOT/administrator/components/com_flexicontent/models/base/base.php:670
16 | FCModelAdmin->getForm() | JROOT/administrator/components/com_flexicontent/controllers/base/baseadmin.php:343
17 | FlexicontentControllerBaseAdmin->save() | JROOT/administrator/components/com_flexicontent/controllers/fields.php:96
18 | FlexicontentControllerFields->save() | JROOT/libraries/src/MVC/Controller/BaseController.php:693
19 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/administrator/components/com_flexicontent/admin.flexicontent.php:264
20 | require_once() | JROOT/administrator/components/com_flexicontent/flexicontent.php:22
21 | require_once() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:71
22 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher::Joomla\CMS\Dispatcher\{closure}() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:73
23 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:361
24 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:143
25 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:186
26 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:293
27 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/includes/app.php:61
28 | require_once() | JROOT/administrator/index.php:32


</body>
</html>

**Comment by micker** [comment]
Corrected via https://github.com/FLEXIcontent/flexicontent-cck/commits/master/
