### ISSUE TITLE
Can't Create Media File Plugin

### ISSUE THREAD

**Issue by iamrobert** [FLEXIcontent/flexicontent-cck#1183]
I'm trying to create a mediafile field - but there is a 500 error:

![](https://i.imgur.com/6csTcfr.png)

index.php:1 
        

       Failed to load resource: the server responded with a status of 500 (Internal Server Error)

       
```
administrator/index.php?option=com_flexicontent&task=fields.getfieldspecificproperties&cid=0&field_type=mediafile&format=raw 500 (Internal Server Error)
```

IF I open the link I getL

![](https://i.imgur.com/JpuFOvL.png)

**Comment by micker** [comment]
Ah can you display this with debug to 1 and error_reporting to max ?

**Comment by micker** [comment]
i think i found can you edit https://github.com/FLEXIcontent/flexicontent-cck/blob/aee90af8f02338db4f668aa0900a354513130526/admin/elements/fcmediaprops.php#L38 and 
And change \Joomla\CMS\Form\FormFieldFcSortableList for JFormFieldFcSortableList
test and do a return

**Comment by iamrobert** [comment]
Thanks - that works. 

Also I saw it here and this doesn't seem to work:

administrator\components\com_flexicontent\elements\fccountriesphones.php

**Comment by micker** [comment]
ok i will publish
