### ISSUE TITLE
error in flexi google map module

### ISSUE THREAD

**Issue by web54** [FLEXIcontent/flexicontent-cck#1185]
when enabling flexi google map menu I have this error 
ERROR 0 - Call to a member function get() on null in /home/weblor/cigale-evasion.weblor.fr/modules/mod_flexigooglemap/helper.php:130

**Comment by micker** [comment]
il me faudrait le log complet en activant le debug puis aussi le contexte (front back ??)
Merci

**Comment by web54** [comment]
context : front : j'affiche le module carte dans une page de pbck

log : (je ne sais pas si le copié collé est bon)

Function	Location
1	()	JROOT/modules/mod_flexigooglemap/helper.php:130
2	modFlexigooglemapHelper::renderMapLocations()	JROOT/modules/mod_flexigooglemap/mod_flexigooglemap.php:125
3	include()	JROOT/libraries/src/Dispatcher/ModuleDispatcher.php:52
4	Joomla\CMS\Dispatcher\ModuleDispatcher::Joomla\CMS\Dispatcher\{closure}()	JROOT/libraries/src/Dispatcher/ModuleDispatcher.php:55
5	Joomla\CMS\Dispatcher\ModuleDispatcher->dispatch()	JROOT/libraries/src/Helper/ModuleHelper.php:281
6	Joomla\CMS\Helper\ModuleHelper::renderRawModule()	JROOT/libraries/src/Helper/ModuleHelper.php:161
7	Joomla\CMS\Helper\ModuleHelper::renderModule()	JROOT/libraries/src/Document/Renderer/Html/ModuleRenderer.php:99
8	Joomla\CMS\Document\Renderer\Html\ModuleRenderer->render()	JROOT/components/com_pagebuilderck/models/page.php:668
9	PagebuilderckModelPage->renderModule()	JROOT/components/com_pagebuilderck/models/page.php:504
10	PagebuilderckModelPage->replaceModule()	 
11	preg_replace_callback()	JROOT/components/com_pagebuilderck/models/page.php:129
12	PagebuilderckModelPage->parseHtml()	JROOT/plugins/system/pagebuilderck/pagebuilderck.php:249
13	plgSystemPagebuilderck->onContentPrepare()	JROOT/libraries/src/Plugin/CMSPlugin.php:289
14	Joomla\CMS\Plugin\CMSPlugin->Joomla\CMS\Plugin\{closure}()	JROOT/libraries/vendor/joomla/event/src/Dispatcher.php:486
15	Joomla\Event\Dispatcher->dispatch()	JROOT/libraries/src/Application/EventAware.php:111
16	Joomla\CMS\Application\WebApplication->triggerEvent()	JROOT/components/com_flexicontent/classes/flexicontent.fields.php:1179
17	FlexicontentFields::triggerContentPlugins()	JROOT/components/com_flexicontent/classes/flexicontent.fields.php:976
18	FlexicontentFields::renderField()	JROOT/components/com_flexicontent/classes/flexicontent.fields.php:1261
19	FlexicontentFields::renderPositions()	JROOT/components/com_flexicontent/classes/flexicontent.fields.php:161
20	FlexicontentFields::getFields()	JROOT/administrator/components/com_flexicontent/views/item/view.html.php:2201
21	FlexicontentViewItem->_displayItem()	JROOT/administrator/components/com_flexicontent/views/item/view.html.php:59
22	FlexicontentViewItem->display()	JROOT/libraries/src/MVC/Controller/BaseController.php:660
23	Joomla\CMS\MVC\Controller\BaseController->display()	JROOT/components/com_flexicontent/controller.php:267
24	FlexicontentController->display()	JROOT/libraries/src/MVC/Controller/BaseController.php:693
25	Joomla\CMS\MVC\Controller\BaseController->execute()	JROOT/components/com_flexicontent/flexicontent.php:270
26	require_once()	JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:71
27	Joomla\CMS\Dispatcher\LegacyComponentDispatcher::Joomla\CMS\Dispatcher\{closure}()	JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:73
28	Joomla\CMS\Dispatcher\LegacyComponentDispatcher->dispatch()	JROOT/libraries/src/Component/ComponentHelper.php:361
29	Joomla\CMS\Component\ComponentHelper::renderComponent()	JROOT/libraries/src/Application/SiteApplication.php:208
30	Joomla\CMS\Application\SiteApplication->dispatch()	JROOT/libraries/src/Application/SiteApplication.php:249
31	Joomla\CMS\Application\SiteApplication->doExecute()	JROOT/libraries/src/Application/CMSApplication.php:293
32	Joomla\CMS\Application\CMSApplication->execute()	JROOT/includes/app.php:61
33	require_once()	JROOT/index.php:32

**Comment by micker** [comment]
tes sur de tes champs adresse dans tes contenus ?

**Comment by web54** [comment]
non, je dois regarder quoi ?

**Comment by micker** [comment]
ton champs map il doit aller chercher des infos dans un champs flexi de type adresse, c'est configuré ?

**Comment by web54** [comment]
![image](https://github.com/FLEXIcontent/flexicontent-cck/assets/9278935/312f7389-67ba-44d0-af60-f6b568cfc6f6)
le seul truc bizarre c'est que je peux pas changer le zoom

**Comment by micker** [comment]
non mais dans le module map c'est régler comment ?

**Comment by web54** [comment]
oui, c'est cela, il allait pas chercher le champs adresse
grand merci au sorcier de Toulouse

**Comment by micker** [comment]
il faudra quand meme que l'on regle le soucis car il ne devrait pas y avoir d'erreur

**Comment by web54** [comment]
alors : plusieurs options
- un message sur la page frontale pour signaler l'oubli
- un blocage sur le module empéchant de sauvegarder si pas de champs selectionné
- premier champs selectionné par défaut

**Comment by micker** [comment]
C'est corrigé https://github.com/FLEXIcontent/flexicontent-cck/commit/760454683cf26a7aec3e1c12aa310a2975bd5620
