### ISSUE TITLE
can 't edit template item view

### ISSUE THREAD

**Issue by web54** [FLEXIcontent/flexicontent-cck#1186]
context : 
duplicate a template from grid
enter into item template edit view

error : 0 You have not supplied a valid HTTP status code

log : 

Function	Location
1	()	JROOT/libraries/vendor/joomla/application/src/AbstractWebApplication.php:497
2	Joomla\Application\AbstractWebApplication->redirect()	JROOT/libraries/src/Application/CMSApplication.php:983
3	Joomla\CMS\Application\CMSApplication->redirect()	JROOT/administrator/components/com_flexicontent/views/template/view.html.php:43
4	FlexicontentViewTemplate->display()	JROOT/administrator/components/com_flexicontent/controllers/base/baseadmin.php:954
5	FlexicontentControllerBaseAdmin->edit()	JROOT/libraries/src/MVC/Controller/BaseController.php:693
6	Joomla\CMS\MVC\Controller\BaseController->execute()	JROOT/administrator/components/com_flexicontent/admin.flexicontent.php:264
7	require_once()	JROOT/administrator/components/com_flexicontent/flexicontent.php:22
8	require_once()	JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:71
9	Joomla\CMS\Dispatcher\LegacyComponentDispatcher::Joomla\CMS\Dispatcher\{closure}()	JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:73
10	Joomla\CMS\Dispatcher\LegacyComponentDispatcher->dispatch()	JROOT/libraries/src/Component/ComponentHelper.php:361
11	Joomla\CMS\Component\ComponentHelper::renderComponent()	JROOT/libraries/src/Application/AdministratorApplication.php:143
12	Joomla\CMS\Application\AdministratorApplication->dispatch()	JROOT/libraries/src/Application/AdministratorApplication.php:186
13	Joomla\CMS\Application\AdministratorApplication->doExecute()	JROOT/libraries/src/Application/CMSApplication.php:293
14	Joomla\CMS\Application\CMSApplication->execute()	JROOT/administrator/includes/app.php:61
15	require_once()	JROOT/administrator/index.php:32

**Comment by micker** [comment]
hello can you more precise Joomla version / flexi version ?
because in joomla 4 i tested it works
in joomla 5 editor seems broken

**Comment by web54** [comment]
found it : there was a space in name
