### ISSUE TITLE
FC- Universal Content module - New content items not displaying

### ISSUE THREAD

**Issue by nzimas** [FLEXIcontent/flexicontent-cck#1187]
New items added to the DB are not retrieved and displayed by the universal content module.

I have tried different scopes in Static - Include mode, but even the Item scope (which is very specific) fails to load newly created items. 
No problem whatsoever with existing item.

I have also tried the category and tag scopes, but to no avail.
All existing items that meet the criteria in those scopes are shown as expected, but newly created items are not.

Suffice to say that I have set the Publishing state of newly created items to "Published".

Furthermore, I have investigated relevant tables like flexicontent_cats_item_relations and flexicontent_tags_item_relations.
The bindings for newly created items are stored correctly.

Environment:
Joomla 4.4.2
FC (Github version as 2024-01-14)
PHP 7.4

**Comment by micker** [comment]
Please use forum we reserve github only for code bug
I use flexicontent in many site without problem. Need to investigate more before that a code bug
