### ISSUE TITLE
tooltip missing on language association since J!4

### ISSUE THREAD

**Issue by Laurent-Cosmic** [FLEXIcontent/flexicontent-cck#1189]
Hello
with J!3, we had some information on the language icons, including the title in a tooltip. The only thing missing was the ID number, but it was in the status bar below the screen...
and then came J!4 and J!5, with improvements in many areas and also the disappearance of this tooltip, which I found very useful
is it possible to find this tooltip? I swear it saves me time in my daily use of J!

thanks in advance
![416052256_3865826073644849_5822034237447491686_n](https://github.com/FLEXIcontent/flexicontent-cck/assets/55958422/6ed8a105-0b90-40de-8dc8-46197f41ad8a)
![416106095_2605625999585399_324351728225656455_n](https://github.com/FLEXIcontent/flexicontent-cck/assets/55958422/0752105c-ecf4-4253-ba37-b22ad66953c6)

**Comment by micker** [comment]
Did you use flexicontent beta (in master) ?

**Comment by Laurent-Cosmic** [comment]
yes - since yesterday based on your advise :D 
but I had the same issue since a while with the official version

**Comment by Laurent-Cosmic** [comment]
great - thanks a lot
