### ISSUE TITLE
Galleryfic responsive

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#1191]

**Comment by web54** [comment]
I'd like to clarify the problem: the height is very difficult to adjust on mobile.
and the description sticks in the middle on mobile device.

**Comment by web54** [comment]
I'd like to clarify the problem: the height is very difficult to adjust on mobile.
and the description sticks in the middle on mobile device.

**Comment by web54** [comment]
I'd like to clarify the problem: the height is very difficult to adjust on mobile.
and the description sticks in the middle on mobile device.
