### ISSUE TITLE
gallerific and convert form bug

### ISSUE THREAD

**Issue by web54** [FLEXIcontent/flexicontent-cck#1193]
Hello,
on a page, when I display a slideshow with convert form, I get a conflict
http://cigale-evasion.weblor.fr/index.php?option=com_flexicontent&view=item&cid=13:sejours-velos&id=65:des-cevennes-a-la-camargue&Itemid=145
BUG : the fields do not accept spaces.

on other pages the same module works
and if I choose another layout it works too

so it is galleryfic that makes conflict

**Comment by micker** [comment]
can yu try this
edit this file in this line
https://github.com/FLEXIcontent/flexicontent-cck/blob/222e6b2080d948d6b7f301ea164ce82434fddba4/site/librairies/galleriffic/js/jquery.galleriffic.js#L1126
and change 32 for 13 ou 45
clean cache and do return

**Comment by web54** [comment]
ok, that works

Can you explain? Will this be corrected in a future version or not?

**Comment by micker** [comment]
Hello i will add this chnage in core
