### ISSUE TITLE
error 404 with search

### ISSUE THREAD

**Issue by web54** [FLEXIcontent/flexicontent-cck#1194]
hello,

link to flexicontent search :

error message : 0 - Class "PlgSearchContent" not found (404)

Call stack
--
# | Function | Location
1 | () | JROOT/plugins/search/pagebuildercksearch/pagebuildercksearch.php:20
2 | require_once() | JROOT/libraries/src/Extension/ExtensionManagerTrait.php:217
3 | Joomla\CMS\Application\CMSApplication->loadPluginFromFilesystem() | JROOT/libraries/src/Extension/ExtensionManagerTrait.php:160
4 | Joomla\CMS\Application\CMSApplication->loadExtension() | JROOT/libraries/src/Extension/ExtensionManagerTrait.php:99
5 | Joomla\CMS\Application\CMSApplication->bootPlugin() | JROOT/libraries/src/Plugin/PluginHelper.php:232
6 | Joomla\CMS\Plugin\PluginHelper::import() | JROOT/libraries/src/Plugin/PluginHelper.php:192
7 | Joomla\CMS\Plugin\PluginHelper::importPlugin() | JROOT/components/com_flexicontent/models/search.php:298
8 | FLEXIcontentModelSearch->getAreas() | JROOT/libraries/src/MVC/View/AbstractView.php:152
9 | Joomla\CMS\MVC\View\AbstractView->get() | JROOT/components/com_flexicontent/views/search/view.html.php:75
10 | FLEXIcontentViewSearch->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:660
11 | Joomla\CMS\MVC\Controller\BaseController->display() | JROOT/components/com_flexicontent/controller.php:267
12 | FlexicontentController->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:693
13 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/components/com_flexicontent/flexicontent.php:270
14 | require_once() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:71
15 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher::Joomla\CMS\Dispatcher\{closure}() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:73
16 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:361
17 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/SiteApplication.php:208
18 | Joomla\CMS\Application\SiteApplication->dispatch() | JROOT/libraries/src/Application/SiteApplication.php:249
19 | Joomla\CMS\Application\SiteApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:293
20 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/includes/app.php:61
21 | require_once() | JROOT/index.php:32

in admin : search indexes

0 Attempt to assign property "canCheckin" on null

Call stack
--
# | Function | Location
1 | () | JROOT/plugins/search/pagebuildercksearch/pagebuildercksearch.php:20
2 | require_once() | JROOT/libraries/src/Extension/ExtensionManagerTrait.php:217
3 | Joomla\CMS\Application\CMSApplication->loadPluginFromFilesystem() | JROOT/libraries/src/Extension/ExtensionManagerTrait.php:160
4 | Joomla\CMS\Application\CMSApplication->loadExtension() | JROOT/libraries/src/Extension/ExtensionManagerTrait.php:99
5 | Joomla\CMS\Application\CMSApplication->bootPlugin() | JROOT/libraries/src/Plugin/PluginHelper.php:232
6 | Joomla\CMS\Plugin\PluginHelper::import() | JROOT/libraries/src/Plugin/PluginHelper.php:192
7 | Joomla\CMS\Plugin\PluginHelper::importPlugin() | JROOT/components/com_flexicontent/models/search.php:298
8 | FLEXIcontentModelSearch->getAreas() | JROOT/libraries/src/MVC/View/AbstractView.php:152
9 | Joomla\CMS\MVC\View\AbstractView->get() | JROOT/components/com_flexicontent/views/search/view.html.php:75
10 | FLEXIcontentViewSearch->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:660
11 | Joomla\CMS\MVC\Controller\BaseController->display() | JROOT/components/com_flexicontent/controller.php:267
12 | FlexicontentController->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:693
13 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/components/com_flexicontent/flexicontent.php:270
14 | require_once() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:71
15 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher::Joomla\CMS\Dispatcher\{closure}() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:73
16 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:361
17 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/SiteApplication.php:208
18 | Joomla\CMS\Application\SiteApplication->dispatch() | JROOT/libraries/src/Application/SiteApplication.php:249
19 | Joomla\CMS\Application\SiteApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:293
20 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/includes/app.php:61
21 | require_once() | JROOT/index.php:32

what shall I do ?

**Comment by web54** [comment]
when in search logs : 

message : Form::loadForm could not load file

**Comment by micker** [comment]
Can you put complet log with débug mod on and error reporting to max ?

**Comment by web54** [comment]
> Can you put complet log with débug mod on and error reporting to max ?

just did in my post

**Comment by web54** [comment]
I installed a fresh on in the same server and it works : it is not the server

**Comment by web54** [comment]
I disabled pagebuilderck search plugin, and it works now

**Comment by web54** [comment]
seems to be an error from a pagebuilderck search plugin
