### ISSUE TITLE
0 Attempt to assign property "canCheckin" on null (admin / search index

### ISSUE THREAD

**Issue by web54** [FLEXIcontent/flexicontent-cck#1195]
Hello

I have this issue : 

0 Attempt to assign property "canCheckin" on null
it happens when i want to go into the search index tools in admin

<html>
<body>
<blockquote class="blockquote" style="box-sizing: border-box; margin: 0px 0px 1rem; font-size: 1.25rem; color: rgb(33, 37, 41); font-family: Roboto, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Helvetica Neue&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(237, 241, 247); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="badge bg-secondary" style="box-sizing: border-box; --badge-padding-x: .2rem; --badge-padding-y: .3rem; --badge-font-size: .75rem; --badge-font-weight: 700; --badge-color: #fff; --badge-border-radius: .2rem; padding: var(--badge-padding-y) var(--badge-padding-x); font-size: var(--badge-font-size); font-weight: var(--badge-font-weight); color: var(--badge-color); text-align: center; white-space: nowrap; vertical-align: baseline; border-radius: var(--badge-border-radius); line-height: 1; display: inline-block; --bg-opacity: 1; background-color: var(--secondary) !important; margin-bottom: 0px;">0</span><span> </span>Attempt to assign property "canCheckin" on null</blockquote><div style="box-sizing: border-box; color: rgb(33, 37, 41); font-family: Roboto, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Helvetica Neue&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(237, 241, 247); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
Call stack
--
# | Function | Location
1 | () | JROOT/administrator/components/com_flexicontent/views/search/tmpl/default.php:336
2 | include() | JROOT/libraries/src/MVC/View/HtmlView.php:415
3 | Joomla\CMS\MVC\View\HtmlView->loadTemplate() | JROOT/libraries/src/MVC/View/HtmlView.php:203
4 | Joomla\CMS\MVC\View\HtmlView->display() | JROOT/administrator/components/com_flexicontent/views/search/view.html.php:442
5 | FLEXIcontentViewSearch->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:660
6 | Joomla\CMS\MVC\Controller\BaseController->display() | JROOT/administrator/components/com_flexicontent/controller.php:286
7 | FlexicontentController->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:693
8 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/administrator/components/com_flexicontent/admin.flexicontent.php:264
9 | require_once() | JROOT/administrator/components/com_flexicontent/flexicontent.php:22
10 | require_once() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:71
11 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher::Joomla\CMS\Dispatcher\{closure}() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:73
12 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:361
13 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:143
14 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:186
15 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:293
16 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/includes/app.php:61
17 | require_once() | JROOT/administrator/index.php:32

</div>
</body>
</html>

**Comment by micker** [comment]
Please
Joomla version
Flexicontent version
PHP version

**Comment by web54** [comment]
flexi : last master
other : 
<html>
<body>

Type de la base de données | mysql
-- | --
10.6.17-MariaDB
latin1_swedish_ci
utf8mb4_general_ci
Aucun
Non
8.1.27
Apache
litespeed
Joomla! 4.4.3 Stable [ Pamoja ] 20-February-2024 16:00 GMT


</body>
</html>

**Comment by micker** [comment]
i couldn't find a way to reproduce on master
i close

**Comment by web54** [comment]
As it was on March 27th , I have forgotten on what site it was
Guess it is solved
Thanks
