### ISSUE TITLE
delete flexi file not possible

### ISSUE THREAD

**Issue by web54** [FLEXIcontent/flexicontent-cck#1196]
in the flexi file management tab, it is impossible to delete an image (selection and red cross)

I get this message:

JLIB_FORM_FIELD_INVALID Type MIME (exemple: jpg)
JLIB_FORM_FIELD_INVALID Titre
JLIB_FORM_FIELD_INVALID FLEXI_URL_LINK

**Comment by micker** [comment]
That already solved in master
