### ISSUE TITLE
Enchance export file

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#1198]
Some interesting return for export tool
Field separator: ;

- (semicolon), which is already the case and is very good, DO NOT CHANGE IT.
- Item separator: \n (backslash n), which is already the case and is very good, DO NOT CHANGE IT.
- Field enclosure character: (none), which is already the case and is very good, DO NOT CHANGE IT.

- Multi-value separator: %% (double percentage), currently at export, it is: , (comma), which is NOT GOOD because "," can be in text fields and numeric fields. %% is much better! SO IT NEEDS TO BE CHANGED (in the source code because we cannot modify it in the FlexiContent export settings or add it to the export settings and give it the value %% by default).

- Multi-property separators: !! (double exclamation mark). I'm not sure when this appears and what character is actually used for export, but !! seems possible or better && which is unlikely to be in a field value (!! might be in a text field). SO IT NEEDS TO BE CHANGED (in the source code because we cannot modify it in the FlexiContent export settings or add it to the export settings and give it the value && by default). ALSO, CHANGE THE DEFAULT VALUE in the import configuration if using &&.

If I look at an export, the value of a relation field is:
- 2356:137, meaning: related_item_id:category_id_of_this_item. Is : (colon) the multi-property separator?
- If I look at an export, the value of an image field is:
- a:3:{s:12:"originalname";s:30:"413-110-u-80_413_4639536_1.jpg";s:12:"existingname";s:0:"";s:4:"desc";s:0:"";}. Is ; (semicolon) the multi-property separator?
- I'm not sure what a multi-property separator is.

The ideal scenario would be for all these separators to be configurable in the Flexicontent export preferences (just like they are in the import settings) and have the same default values as the default import settings. This way, we could export and re-import immediately without touching the contents of the CSV file.

**Comment by micker** [comment]
first step here
https://github.com/FLEXIcontent/flexicontent-cck/commit/7f3b5863c8c8ab4f7604149126b3c8ec3b09ba32

**Comment by micker** [comment]
Utilise cet URL https://github.com/FLEXIcontent/flexicontent-cck/archive/refs/heads/master.zip

**Comment by alaingrach** [comment]
1er test 👍 👍 Très bien les réglages d'export de Flexicontent avec les nouveaux séparateurs (juste le séparateur multi-propriété (il manque un p dans l'intitulé) aurait pu être "&&" à la place de "!!" qui pourrait se trouver dans un champs texte).

Par contre en fonctionnement , problèmes :
- Le caractère \n de séparation des item n'est pas pris comme un LF Unix mais comme deux caractères ascii "\" et "n", les lignes (et donc les items) ne sont pas séparées dans la fichier CSV. J'ai essayé avec un autre caractère ("##") et ça fonctionne bien.
- Les nouveaux séparateurs du réglage d'export ne sont pas prise en compte (c'est toujours ":" pour séparer les Multi-values et non "%%", je ne sais pas pour les multi-propriétés parce que je ne sais pas ce que sont les multi-propriété, mais je n'ai trouvé nul part le caractère "!!" indiqué dans les réglages).

J'ai changé le caractère de séparation des fields ("@@"), ça fonctionne bien.

Pour les intitulés :
Réglage export Flexicontent                     Filtre de la fenètre items                             Réglage import Flexicontent

Column Headers                                       Header Row
Field Label                                                 Champ Etiquette
Field name                                                 Champ Nom
Field (Column) separator                                                                                               Séparateur de champs
Séparateur d'item                                                                                                          Séparateur d'item
Multivalue separator                                                                                                     Séparateur de multi-valeur
Séparateurs Multi-proriété                                                                                           Séparateurs Multi-proriété

**Comment by micker** [comment]
Attention pour tes tests il faut forcément sauver la configuration générale
Si tu mets les valeurs souhaitées cela fonctionne ?

**Comment by alaingrach** [comment]
En fait pour le problème du \n, la première ligne celle qui contient les noms des champs est OK et se termine bien par un Line Feed.
Les suivantes sont sur une seule ligne séparées par les caractères ascii \n.

Je t'ai fait une image des différences d'intitulés entre les trois fenètres ou l'on paramètres les imprts et exports de CSV :
![Capture d’écran 2024-04-19 à 23 17 26](https://github.com/FLEXIcontent/flexicontent-cck/assets/15897534/57f5579c-d8ee-469b-b9b9-32c153f3a465)

**Comment by micker** [comment]
Pour le line feed il faut que je check ... 
par contre le %% fonctionne chez moi un exemple d'export
`Employée de maison;Beginer accepted; test@com3elles.com!! test2@com3elles.com!! test3@com3elles.com;diplome 1%%diplome 2%%diplome 3;Castanet - Pompertuzat - Pechabou%%St Orens - Auzielle - Labège - Escalquens\r\n;1;Aide à la personne;More than 2 years;`
le !! est utiliser dans les champs multi,propriété (email, adresse, terme .. etc)

**Comment by alaingrach** [comment]
Oui, tu as raison, je me suis planté (je n'avais pas de multi valeurs dans mon export !), le séparateur de multi valeurs marche très bien et si je le change, ça fonctionne aussi.
Pour le champs de multi propriétés, j'ai bien dans ma base un champs email avec par exemple cette valeur :
a:2:{s:4:"addr";s:14:"alain@grach.fr";s:4:"text";s:0:"";}
ou un champ image (gallery) avec plusieurs images qui a pour valeur :
a:3:{s:12:"originalname";s:8:"6467.jpg";s:12:"existingname";s:0:"";s:4:"desc";s:0:"";}%%a:3:{s:12:"originalname";s:8:"6466.jpg";s:12:"existingname";s:0:"";s:4:"desc";s:0:"";}%%a:3:{s:12:..........
Je n'y trouve pas le séparateur !! choisi dans les réglages d'export, mais devrait-il y être ?

**Comment by micker** [comment]
En fait le séparateur n'est actif que si tu fais un export avec des valeurs HTML pas la valeur raw

**Comment by micker** [comment]
j'ai charger la correciton sur le saut de ligne
https://github.com/FLEXIcontent/flexicontent-cck/commit/cd77c0258ffe26cf2b3e9a8ff0f2c535f4ed431a

**Comment by alaingrach** [comment]
Super, si tu veux que je teste donne moi le lien à télécharger (je n'ai toujours pas trouvé comment faire sur Gitub).

Je n'ai pas réussi à avoir le séparateur de multipropriété, même en exportant un champs email ou adresse en "Valeurs de rendu" au lieu de "Valeurs brutes".

**Comment by alaingrach** [comment]
Ah, et je ne t'ai pas dit, très bien aussi qu'il y ait des valeurs par défaut pour l'export dans les filtres de la page des items. Avant ils n'y étaient pas...
![Capture d’écran 2024-04-20 à 14 03 18](https://github.com/FLEXIcontent/flexicontent-cck/assets/15897534/d8312770-45ca-4503-95e3-9a73ce411079)

**Comment by micker** [comment]
Tu reprends lien au dessus et tu télécharges
Puis tu installes ça te fais une mise a jour

**Comment by alaingrach** [comment]
J'ai réinstallé et toujours le problème de \n sauf que maintenant même la ligne des entêtes de colonnes se termine par un \n en ascii au lieu d'un Line Feed...

**Comment by micker** [comment]
Ta bien sauver la configuration ? C'est bizarre sur mon dev pas de soucis

**Comment by micker** [comment]
Bon j'ai compris le soucis ....
si on recupere la valeur par le parametre pour avoir une valeur administrable mais \n ne fonctionne plus ... soit c'est par defaut et ca marche. il faut que je vois ce qui est possible c'est tres con .... mais pas evident a mettre en place

**Comment by alaingrach** [comment]
Hello,

Peut être faut aller voir dans les paramètres de la fenêtre d'import.
Si je change le séparateur d'items dans la fenêtre d'import (par exemple @@) que j'essaye d'importer un fichier qui avait \n comme séparateur d'items, ça me dit qu'il y a beaucoup trop de colonnes ce qui est normal puisque tous mes items sont lus comme un seul item.
Mais si je remets \n comme séparateur d'items dans les réglages d'import (je le tape dans la fenètre de paramètres) et que je réimporte le fichier, il le lit correctement, il a donc bien décodé mon entrée de \n comme un line feed et non comme les caractères ascii.
Si ça peut aider ???

**Comment by micker** [comment]
A l'import on lit la on écrit mais t'inquiètes on va trouver

**Comment by micker** [comment]
cela devrait être bon
https://github.com/FLEXIcontent/flexicontent-cck/commit/67121521dac149d6976f88489b223ad325dd2887
tu peus confirmer ?

**Comment by micker** [comment]
pour le champs relation c'est normal la version beta integre un nouveau systeme que l'on doit affiner pour le truc des lien c'est bizarre j'ai pas ca en dev ... a voir
pour l'instant je cloture cette issue

**Comment by alaingrach** [comment]
Ça à l'air d'être tous les champs multi valeurs qui ont changé de mise en page, pas seulement les champs Relation.

**Comment by micker** [comment]
pour les cadres autours des elements c'est volontaire, c'est pour être plus léger et plus accessible
pour le cas du champs lien c'est un soucis de css il faut qu'on regarde
