### ISSUE TITLE
Image Field Stopped Working if image is in custom tab due to JS Error

### ISSUE THREAD

**Issue by iamrobert** [FLEXIcontent/flexicontent-cck#1199]
https://www.youtube.com/watch?v=cHy9MYODtf8

Relevant [FLEXIContent Forum Post](https://www.flexicontent.org/forum/20-general-support/58729-image-fields-stopped-working.html)

###  JS Bug when uploading:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'replace')
    at fcfield_image.assignImage (form.js?a55697b159ef541eb26b6f01d3686084:225:27)
    at fcfield_image.fileUploaded (form.js?a55697b159ef541eb26b6f01d3686084:316:17)
    at l.Uploader.fcfield_FileUploaded_32 (index.php?option=com_flexicontent&task=items.edit&view=item&id=179:1127:19)
    at l.Uploader.FileUploaded (plupload-extend.js?a55697b159ef541eb26b6f01d3686084:289:42)
    at l.Uploader.dispatchEvent (plupload.full.min.js:29:16013)
    at l.Uploader.trigger (plupload.full.min.js:13:19080)
    at T.onload (plupload.full.min.js:29:10758)
    at h.<anonymous> (plupload.full.min.js:13:19249)
    at Array.<anonymous> (plupload.full.min.js:13:18634)
    at n (plupload.full.min.js:13:2325)


Cannot read properties of undefined (reading 'replace'):

    fcfield_image.assignImage = function(tagid, file, preview_url, keep_modal, preview_caption, config_name)
    {
        // Get TAG ID of the main form element of this field
        var ff_suffix = '_existingname';
        var elementid_n = tagid.replace(ff_suffix, '');
```

The _existingname doesn't exist. If I add it here:

```
    if ($img_link)
    {
        $imgpreview = '<img class="fc_preview_thumb" id="'.$elementid_n.'_preview_image" src="'.$img_link.'" alt="Preview image" />';
    }
    elseif ($img_link !== false)
    {
        $imgpreview = '<img class="fc_preview_thumb" id="'.$elementid_n.'_preview_image" src="data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=" alt="Preview image" />';
    }
```

The JS Error disappears but the image fails on apply and reload.
 
### Temporary Solution
 
 Reverting to this[ field_InlineBoxes.php](https://github.com/FLEXIcontent/flexicontent-cck/blob/e51b4b4f80714ba7dcf79819a568c138dd94d341/plugins/flexicontent_fields/image/tmpl/field_InlineBoxes.php) works, but UI is poor:
 
![](https://i.imgur.com/k2JxdW9.png)

**Comment by micker** [comment]
what is your image field configuration (for form) ?

**Comment by iamrobert** [comment]
@micker 
Is this what you're looking for?

![image](https://github.com/FLEXIcontent/flexicontent-cck/assets/8617673/47fbb773-04f1-4575-8e14-6b7d755e199b)

![image](https://github.com/FLEXIcontent/flexicontent-cck/assets/8617673/0077ec1e-b9ab-4fa6-87f7-a6222d54c682)

**Comment by micker** [comment]
can you test with multi value mode ? (maybe something is missing

**Comment by iamrobert** [comment]
I think you are right.

Each image field creates a hidden input in the old version - I reverted to.

`<input type="hidden" class="existingname fcfield_textval" id="custom_image_0_existingname" name="custom[image][0][existingname]" value="" />`


`<input type="hidden" class="existingname fcfield_textval" id="custom_banner_image_0_existingname" name="custom[banner_image][0][existingname]" value="" />`

But in the latest version, these fields don't exist for single images - only for those with multiple images.

**Comment by micker** [comment]
ah we forgot it i will re add it

**Comment by micker** [comment]
WE will check thanks for return

**Comment by Icehoi** [comment]
> WE will check thanks for return @Icehoi if you change value 1 peer Line for multiple that works ?

^ Nope, not change.

**Comment by micker** [comment]
@Icehoi @iamrobert can you update via master branch and redo your test ?

**Comment by micker** [comment]
Sorry i dont understand did you update with master branchement without any override and test in backend do a report
And test in front without any override and do a report
Thanks

**Comment by micker** [comment]
@iamrobert some return ?

**Comment by iamrobert** [comment]
I downloaded the master - but I am still getting the same issue:

```Uncaught TypeError: Cannot read properties of undefined (reading 'replace')


    at fcfield_image.assignImage (form.js?90cc064b15c238d07a8fe81ccaa7c1a2:225:27)
    at fcfield_image.fileUploaded (form.js?90cc064b15c238d07a8fe81ccaa7c1a2:316:17)
    at l.Uploader.fcfield_FileUploaded_32 (index.php?option=com_flexicontent&task=item.edit&view=item&id=176:1062:19)
    at l.Uploader.FileUploaded (plupload-extend.js?90cc064b15c238d07a8fe81ccaa7c1a2:289:42)
    at l.Uploader.dispatchEvent (plupload.full.min.js:29:16013)
    at l.Uploader.trigger (plupload.full.min.js:13:19080)
    at T.onload (plupload.full.min.js:29:10758)
    at h.<anonymous> (plupload.full.min.js:13:19249)
    at Array.<anonymous> (plupload.full.min.js:13:18634)
    at n (plupload.full.min.js:13:2325)
    ```

here's a video:
[video-issue.webm](https://github.com/FLEXIcontent/flexicontent-cck/assets/8617673/15433742-f5d9-4f97-8ea2-580ddad3c15f)

**Comment by micker** [comment]
ok thanks for return need to check on j4 ! it seems work on j5 (my demo site works)
https://www.loom.com/share/458ad17eb75e40988ea146a19a8d2c1a?sid=b1aa24c9-a83c-41f9-b524-630ed7afa10a
Can you confirm it ?

**Comment by micker** [comment]
@iamrobert i do a fresh install with joomla 4.4 and flexicontent on master branch
i add an image field and no problem upload works

**Comment by iamrobert** [comment]
@micker - 

Thanks - the loom showed it working new version v5. 

I will test it again - but have been unable to get it to work.

Do you want a version to check? I can install one for you to check.

**Comment by micker** [comment]
Yes it Can be cool thanks

**Comment by micker** [comment]
@iamrobert some news  ?

**Comment by iamrobert** [comment]
@micker Thanks - I sent login details via your @com3elles.com

One thought - could it be because the image is in a tab? Tabs are hidden using display: none - so it's not visible?

**Comment by micker** [comment]
yes i confirm that the problem upload is broken in custom tab

**Comment by iamrobert** [comment]
@micker I think with the latest version of FLEXIContent it working if you use below PHP 8.2. As soon as you use PHP 8.2 it fails.

![php-issue](https://github.com/user-attachments/assets/29ebb3e1-f71b-4301-ae31-e2b1ffe6beea)

Here's the JS issue:
<img width="1127" alt="image" src="https://github.com/user-attachments/assets/d15860c0-9368-462f-8ec1-4bd37416967f">

**Comment by micker** [comment]
for information this bug exist on file field
