### ISSUE TITLE
Fieldset Group Marker - defaults to Tab-set: Start

### ISSUE THREAD

**Issue by iamrobert** [FLEXIcontent/flexicontent-cck#124]
1. Open Fieldset Group Marker: eg Tab Close

![download 1](https://cloud.githubusercontent.com/assets/8617673/6019790/84cf6994-abdf-11e4-9f86-b36344775f75.png)

2. Forgets that its "Tab Close" Always reverts to Tab-set: Start

![download 2](https://cloud.githubusercontent.com/assets/8617673/6019810/ba25f0fe-abdf-11e4-8276-07e439be2f00.png)

**Comment by ggppdk** [comment]
Yes i have seen this morning,

backend/elements/multilist.php

replace
'list.select'=>$element_id, // value of the SELECTED field
with
'list.select'=>$values, // value of the SELECTED field

will fix in next commit

**Comment by ggppdk** [comment]
Fixed in 1686672
