### ISSUE TITLE
Enchanced file field by adding multi-upload feature

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#128]
i have 2 ideas :
-adding plusupload script to allow multi upload
-create a light view in upload popup many user doesn't need all option (for front editing is very too mutch
i think 2 ways 
=> allow to hide par of this view for front (ex tabs, list of file, description ...)
=> create a folder mode like image field to only put file without other option
an screenshot about an override => user prefer this less option more simple (for front)
![overide-filemanager](https://cloud.githubusercontent.com/assets/2539440/6097753/64c70f2e-afc9-11e4-8a01-2e3212bdf00b.jpg)

**Comment by sitefaitbienfait** [comment]
+1
I'm agree, for image and file fields, sometimes we need a very minimalist form (just the input type="file").
I need this in short delay, i can sponsor it, i will talk about that with Georgios.
Regards

**Comment by ggppdk** [comment]
effectively 
1. placing inline, the  - upload - FILE (form) field,
2. and parameters to select what other FILE data to hide or display inline:
- Title
- Language
- Description
- other ?

For this purporse i think enhancing the file field is the way to

**Comment by micker** [comment]
when you say inline you say without popup ?

**Comment by Igcorreia** [comment]
+1 Yes without pop-up. Not every website needs it, or not every TYPE of content/field needs it.

-- and that pop up does not work on mobile :)

**Comment by acymru** [comment]
I've found that the frontend use of this field to also perform video playback is unclear.  The file shows with the "View" button, but when the button is clicked, there is a modal with a "wait" spinner, but the file just downloads to the local computer.  Perhaps I'm missing a configuration step, but clear tooltips and/or documentation are difficult to find.  Would you say the coding is complete?  This is with 3beta5a, using both the popup and inline options.

**Comment by ggppdk** [comment]
about the "view" , we need some more documentation for this

-- the user should enable "view" only for file type that can be really viewed by the browser

the view is happening by passing some HTTP headers to the browser asking it to display the file instead of downloading it, if the browser can not display it then a download will start, 

-- so viewing must not be enabled if file field contains not viewable files, or we would need an extra parameters to specify which extensions should be viewable, for non-viewable extensions the "View" should not be displayed as it makes little sense

**Comment by acymru** [comment]
True.  If the file in question is an mp4 (video), what would the user need to do to enable it as viewable?

**Comment by ggppdk** [comment]
A new parameter in field confguration, will have have a comma list of the extensions of the files considered as viewable

**Comment by ggppdk** [comment]
v3.0.9 adds
- Inline edit of item properties (inside item form) 
- fieldgroup support
- also added preview thumbnail if file is an image

v3.0.10 
- will finish and enable multi-upload (plupload), which is partly done in v3.0.9 and not enabled
- also add per user file upload size limit (in v3.0.x we added file size column in DB table) so this will be calculated without re-opening files every time

**Comment by micker** [comment]
i think we can add auto assign option 
1 display plusupload in item form (minimal dimension) or in slider 
2 user can drag and drop image inside
3 click on upload
4 image are assigned to item
=> user can remove or move
it will be more more userfriendly

**Comment by ggppdk** [comment]
Done, 
- added multi-uploader to filemanager and to fields: image, file, minigallery
- also added image previewing with zoom to every file row before uploading
- along with also file property editing to every file row before uploading

What is missing is adding option to 
- auto select all uploaded files
- image zooming for the existing file list, e.g. we can use multibox

**Comment by micker** [comment]
Great an add plusupload in dbmode for image field



Le 1 oct. 2016 20:31, à 20:31, Georgios Papadakis <notifications@github.com> a écrit:

**Comment by ggppdk** [comment]
> Great an add plusupload in DB-mode for image field

we need 
- update the fileselement DB model to respect configuration parameters of the field (easy, little work)
- then also updating the JS code of image field (a little more difficult than the above, but i think we should be able to use existing JS code from file / minigallery fields, and save time)
