### ISSUE TITLE
Adding item list markup to the module

### ISSUE THREAD

**Issue by esinet** [FLEXIcontent/flexicontent-cck#13]
From flexicontent forum : http://www.flexicontent.org/forum/index.php?f=20&t=8349&rb_v=viewtopic
Hello,
Item list markup in Universal module content
They exist in item listing, and it could be great to have them in universal module contet too
Thank you

**Comment by ggppdk** [comment]
The code that creates the markups is in helper class, it can be reused in module with some modification, the reason putting it in helper functions, was to re-use and eventually use it in all lists too
