### ISSUE TITLE
Universal module date scope should use server local time instead of UTC+0, for comparing date field values that do not use timezone

### ISSUE THREAD

**Issue by piperchick** [FLEXIcontent/flexicontent-cck#130]
Hello,

I use the FLEXIcontent Universal module to show "This day in history" but I can't control the time zone.  I am in the Eastern time zone (UCT -5), but the module displays in UCT so every evening my site is showing the events for the next day.

When I posted in the FC forum, ggppdk suggested that I post a feature request here.  Original thread below: 
http://www.flexicontent.org/forum/index.php?f=71&t=8711&rb_v=viewtopic
 
Thanks.

**Comment by ggppdk** [comment]
Accepted as enhancement issue for v3.1 or later

**Comment by piperchick** [comment]
I look forward to this enhancement. It would be nice if the Universal Module pulled the date and time from the core Joomla configuration.

Thanks.

**Comment by piperchick** [comment]
I am writing to check on the status of this enhancement.  

For some reason the date currently seems to be based on UTC but I think it should be based on the offset specified in the Joomla configuration or from the setting specified in the FC field.

Maybe I am missing something in setting the time zone in the field configuration because no matter what I change it to, there is no change.

Joomla date/time offset in configuration UTC -5 (Toronto)
My local time zone UTC -5
My server UTC -6
PHP setting in Joomla System setting UTC -6 (Chicago)
Field setting: Use editor's time zone "yes" (but it doesn't matter if I set it to "no")
Time zone guest viewers: Site's time zone (have tried other settings with no difference)
Time zone logged viewers: Site's time zone (have tried other settings with no difference)
Flexi Universal Module Publishes UTC

Joomla Joomla! 3.6.3 Stable
FLEXIcontent 3.1.0 

Thanks,

**Comment by ggppdk** [comment]
Changing milestone to 3.1.1

About your question:
- Publish Up
- Publish Down
- Created
- Modified

all above dates are stored in DB as UTC+0 so we are doing right to compare (SQL query) them with current time expressed as UTC+0 

now the date field allows 
- either storing to DB table without convertion
- or storing to DB table as UTC+0

So i am guessing your case is that FLEXIcontent date field is:
- "storing to DB table without convertion"

Since **changing the UTC+0 comparison is wrong** to handle the above special case, i am thinking either to read date field configuration or add extra option to universal module configuration

**Comment by ggppdk** [comment]
with commit: 86ba049

- added handling of case that date field does not use timezones, in this case we will assume server local time for the purpose of comparing to select listed items

copy the new helper file:
https://raw.githubusercontent.com/FLEXIcontent/flexicontent-cck/master/modules/mod_flexicontent/helper.php

and test

**Comment by piperchick** [comment]
Thanks for looking into this, but unfortunately I can't get it to work.  Is there a trick or something?

Thanks.

**Comment by ggppdk** [comment]
There is a new configuration parameter, you will need to enabled it

For further talking about this, please do not post here, instead open a new thread in our forum:
http://www.flexicontent.org/forum/
