### ISSUE TITLE
Category state can be changed to 'trashed'

### ISSUE THREAD

**Issue by lungkao** [FLEXIcontent/flexicontent-cck#133]
Category not Trashed i click select category and click  Trash but
Message
category(ies) published

![2015-02-18_09-26-41](https://cloud.githubusercontent.com/assets/2047778/6241700/51ac7d92-b754-11e4-9ffe-4780be5d8786.png)

**Comment by ggppdk** [comment]
Yes i confirm this bug, to be fixed in next v3beta

**Comment by ggppdk** [comment]
Fixed here: 5ff5a12
