### ISSUE TITLE
Flexicontent And Warp Theme Framework issue

### ISSUE THREAD

**Issue by lungkao** [FLEXIcontent/flexicontent-cck#141]
if enable module
Universal Content Module for FLEXIcontent
Content Lists Filter Module for FLEXIcontent
Advanced Search Module for FLEXIcontent

in tag body have element.style  overflow: hidden; if use on mobile

hide on position offcanvas 

![2015-03-01_08-42-58](https://cloud.githubusercontent.com/assets/2047778/6429123/cc7c777a-bff1-11e4-9547-be5c94c70363.gif)

**Comment by ggppdk** [comment]
We have JS code to restore overflow 100 milliseconds after page completes loading, do you have any JS error during loading ?

Test this,  in file
components//assets/js/tmpl_common.js
replace:
		document.documentElement.style.overflow = "auto";  // firefox, chrome, ie11+
		//document.body.style.overflow = "auto";
with:
		document.documentElement.style.overflow = "";  // firefox, chrome, ie11+
		document.body.style.overflow = "";

**Comment by lungkao** [comment]
Test Pass Thank You

**Comment by ggppdk** [comment]
Fix commited here:  ee5cc91
