### ISSUE TITLE
Image field popup upload (fileselement view) seem to have URLs to backend CSS/JS

### ISSUE THREAD

**Issue by ggppdk** [FLEXIcontent/flexicontent-cck#144]
This is not the wanted behaviour, we do not want links to backend from frontend,
because the backend folder maybe inaccessible e.g. protected via password

**Comment by lclaude** [comment]
Like demanded here http://www.flexicontent.org/forum/index.php?f=21&t=8910&rb_v=viewtopic
I do a UP!

**Comment by ggppdk** [comment]
Removed the 2 backend file referened in f3586ca
