### ISSUE TITLE
Progress of work on the FLEXIcontent replacements plugin

### ISSUE THREAD

**Issue by ggppdk** [FLEXIcontent/flexicontent-cck#150]
Now this system plugin (yet unreleased) supports 
- replacement of FC item/ FC category links everywhere (by using title)
- replacement of fields anywhere (CSS/JS work)
- replacement items anywhere (CSS/JS work)

TODO:
- allow replacing in links to use partial title
- when a category or item is not found or unpublished, then just add the title text without adding an error

Also to be able to make adding into textareas more user friendly, it is good to have an editor button

**Comment by ggppdk** [comment]
If someone has need for the powerful replacements that plugin supports,
then he may contact me by email, and i will give him/her for testing

**Comment by lungkao** [comment]
Wow! Pending Test It

**Comment by Rooney2** [comment]
You can see it here live in action: http://www.muenstermann.com/en/download-centre/reference-project-information/1476-reference-flyer-dedusting-september-2014. All the links are built using {flexi_link:item title:"Article Title"}. The goal was to have easy internal linking.
