### ISSUE TITLE
Relation field enhancements

### ISSUE THREAD

**Issue by ggppdk** [FLEXIcontent/flexicontent-cck#155]
http://www.flexicontent.org/forum/index.php?f=29&t=8256&rb_v=viewtopic

**Comment by jkirsch2** [comment]
Any news about this ?

**Comment by micker** [comment]
relation field is alrady update did you test it ?

**Comment by ggppdk** [comment]
@jkirsch2 
There have been several updates on the relation field, and this issue does describe an exact enhancement

So i will close it,
you should use latest official release, and speak of specific improvements based on it

Also better discuss them in forum first, but if you think 
- that you have a good description of an enhancement 
- that will be used by several sites

then open new issue here directly
