### ISSUE TITLE
Order category by "More popular" is inverted

### ISSUE THREAD

**Issue by irbian** [FLEXIcontent/flexicontent-cck#157]
https://github.com/FLEXIcontent/flexicontent-cck/blob/master/site/classes/flexicontent.helper.php#L5331

Switch cases 'hits' and 'rhits' are inverted

**Comment by ggppdk** [comment]
Thanks actually, will do the correction (reversing) on the XML files
config.xml
category.xml
etc

because we use "r" for "DESC"

**Comment by ggppdk** [comment]
Fixed here: 194d346
