### ISSUE TITLE
Extra character appears in Advanced Search Module

### ISSUE THREAD

**Issue by piperchick** [FLEXIcontent/flexicontent-cck#159]
I installed Beta5 today and noticed that the "o" now appears next to the Advanced Search Module for Flexicontent. I installed the module again in a different position and it did the same thing.

I don't think I did anything to cause this.

You can see it here on the right side of the page: http://deadcanadians.ca/

Thanks.

![ss_flexi_search](https://cloud.githubusercontent.com/assets/11019150/6718919/a541dfb6-cd8d-11e4-904f-be5c557c219e.jpg)

**Comment by ggppdk** [comment]
Will test/fix this in next public BETA

**Comment by ggppdk** [comment]
Fixed
