### ISSUE TITLE
Examine creating a plugin for an alternative to the (discontinued) XMAP

### ISSUE THREAD

**Issue by ggppdk** [FLEXIcontent/flexicontent-cck#161]
http://extensions.joomla.org/tags/site-map

**Comment by iamrobert** [comment]
Could it work with:
https://www.z-index.net/en/joomla-xmap/mapx-xmap-reloaded.html

**Comment by micker** [comment]
Osmap is compatible with xmap plugin

Envoyé par Type Mail



Sur 2 avr. 2015 21:40, à 21:40, iamrobert <notifications@github.com> a écrit:
