### ISSUE TITLE
Feature: Pin a category to the backend Dashboard

### ISSUE THREAD

**Issue by Igcorreia** [FLEXIcontent/flexicontent-cck#166]
The idea is to pin the Primary category to the FC dashboard in the backend.

The link with give the user of all items in that list.

**Comment by micker** [comment]
You have my flexiadmin module to do it lol

**Comment by iamrobert** [comment]
As well as flexiadmin:
http://extensions.joomla.org/extension/asikart-quickicons

Then you can combine FLEXIcontent with other areas eg Rsform etc.

**Comment by micker** [comment]
now with flexiadmin you can load flexicontent field !
