### ISSUE TITLE
Bug on Search Module display a zero number: 0

### ISSUE THREAD

**Issue by Igcorreia** [FLEXIcontent/flexicontent-cck#167]
There is a 0 appearing in the search module with this configuration:

![image](https://cloud.githubusercontent.com/assets/1076409/6942327/b5dfcb20-d87e-11e4-850b-3b77ce8a70ff.png)

**Result:**
![image](https://cloud.githubusercontent.com/assets/1076409/6942313/9ae40714-d87e-11e4-961a-d98b2a40b694.png)

**Comment by piperchick** [comment]
This was reported in #159 here: https://github.com/FLEXIcontent/flexicontent-cck/issues/159

Slated for correction in v. 3.1

**Comment by ggppdk** [comment]
no it is a bug, so it is not for v3.1
it is minor and easy to fix, already done locally 

will be in next commit, and so will be in v3 BETA6

**Comment by ggppdk** [comment]
Fixed here: 65bd851
