### ISSUE TITLE
Field grouping support in file field

### ISSUE THREAD

**Issue by acymru** [FLEXIcontent/flexicontent-cck#168]
Field grouping support in file field needs completion within 3 beta.

**Comment by ggppdk** [comment]
This will not be in v3.0 final,  rather it will be added in v3.1 BETAs

**Comment by Igcorreia** [comment]
+1

**Comment by ggppdk** [comment]
Added in 311944e

Multi-value and fieldgroup support for file field, multi-value inline editing for file properties for fields: file, minigallery
