### ISSUE TITLE
Post Installation Issue - multilingual support times out

### ISSUE THREAD

**Issue by iamrobert** [FLEXIcontent/flexicontent-cck#169]
Install multilingual support times out:
![download](https://cloud.githubusercontent.com/assets/8617673/6977389/c565489c-d9ee-11e4-9142-249078fd803f.png)

**500 error for:**
administrator/index.php?option=com_flexicontent&task=createlangcolumn&format=raw&5349950ec39f848683dca92ac5d1c14d=1&tmpl=component

~~Related to mootools.~~ no controller.php

Running Joomla 3.4.1 + FLEXIcontent 3.0 BETA6

index.php?option=com_flexicontent:270 (anonymous function)

**Comment by iamrobert** [comment]
Further Info has as error:
index.php?option=com_flexicontent&task=createlangcolumn&format=raw&5349950ec39f848683dca92ac5d1c14d=1&tmpl=component

Error: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near &#039;)&#039; at line 1 SQL=UPDATE xxx_flexicontent_items_ext AS ie LEFT JOIN xxx_content as i ON i.id=ie.item_id SET ie.language = i.language WHERE i.language&lt;&gt;ie.language )

**Comment by iamrobert** [comment]
issue with controller.php. Proposed change here: 
https://github.com/FLEXIcontent/flexicontent-cck/compare/master...iamrobert:patch-17

**Comment by ggppdk** [comment]
This code (SQL query) was updated recently to fix an issue, 

so the query is broken due to the parenthesis, thanks for the fix,
we missed this

**Comment by ggppdk** [comment]
Fixed
