### ISSUE TITLE
SEF URL Category in flexicontent 3 beta 5a

### ISSUE THREAD

**Issue by miken912** [FLEXIcontent/flexicontent-cck#171]
Forum link:

http://www.flexicontent.org/forum/20-general-support/53303-new-sef-links-for-categories-in-fc-module.html

Perhaps the problem here:

flexicontent-cck/site/helpers/route.php  line 492-494  

If you change like this all works:
===================================================
	$link = 'index.php?option=com_flexicontent&view=category';
		if ($_catid) $link .= '&cid='.$catid;

===================================================

**Comment by ggppdk** [comment]
Fixed in 3c65090
