### ISSUE TITLE
Unable to reindex basic search, when no items exist or no fields are marked as searchable

### ISSUE THREAD

**Issue by iamrobert** [FLEXIcontent/flexicontent-cck#172]
Hi ,

This issue comes up when I am trying to reindex fields.

index.php?option=com_flexicontent&task=search.index&items_per_call=50&itemcnt=0&indexer=advanced&rebuildmode=quick

![bug](https://cloud.githubusercontent.com/assets/8617673/7002869/59c42d18-dc84-11e4-847b-529fde9e1c36.png)

```$lang_query = "SELECT id, language"
				." FROM #__content AS i "
				.(!FLEXI_J16GE ? " LEFT JOIN #__flexicontent_items_ext AS ie ON i.id=ie.item_id" : "")
				." WHERE id IN (".implode(', ',$query_itemids).")"
				);```

controllers\search.php

**Comment by ggppdk** [comment]
Hi, 

Language is empty, what is the language setup that you have ?

--- if you go to Joomla Language manager and click
"Content languages"
do you have some active languages there ?

**Comment by iamrobert** [comment]
Hi ggppdk,

The site is here:
http://htw3.taichungdesigner.com/
it indexes at v3.0 beta 

I downloaded it and starting working on it for a new site and 3.0.6 - I get the above issue. 

Language Files for Content:
![language](https://cloud.githubusercontent.com/assets/8617673/7016570/7a037ec2-dd19-11e4-8c4d-cab1aefc312a.png)

Administrator - multilingual setup module shows its working
![multi](https://cloud.githubusercontent.com/assets/8617673/7016583/e141fc1c-dd19-11e4-85f3-5fe674e072ca.png)

Thanks,

Robert

**Comment by iamrobert** [comment]
Sorry - solved. If you create the fields before you create the articles - it tells you to index files.

However - you need 1 item in order to index.

**Comment by ggppdk** [comment]
Yes also if you have all fields marked as not searchable it will give an error,

i know these bugs have little effect,

but they are confusing to the user because you get message to re-index, so i re-open this to add 1 or 2 checks in appropriate places

**Comment by iamrobert** [comment]
Also - I thought you could add a modal for the re-index notice - it would simplify the UX:
https://github.com/FLEXIcontent/flexicontent-cck/pull/174

**Comment by ggppdk** [comment]
Fixed Indexer to finish when no items or no text-searchable fields are found in: 237ba53

Also added listing of Basic Index records in same commit
