### ISSUE TITLE
multivalue image field only has 1 image in universal module flexicontent

### ISSUE THREAD

**Issue by ldoliv** [FLEXIcontent/flexicontent-cck#175]
Hello, I'm using the lastest flexi build beta 6, in universal module flexicontent under "Layout: Select fields" I specify the multi value image field in the "Fields parameters" section, but when accessing the object thumbs_src array has only 1 image for each of the sizes.

Thanks.

**Comment by ggppdk** [comment]
Yes this is done deliberately, you can disable image and use getfielddisplay method instead please see our FAQ. Using getfielddisplay you can render any custom field by its name inside your custom code. Do a print_r on the field to see the all available data
