### ISSUE TITLE
Univ. Content Module for FLEXIcontent, doesn't save custom params

### ISSUE THREAD

**Issue by ldoliv** [FLEXIcontent/flexicontent-cck#176]
Hello,

I'm using the latest build beta 6 nightly 3, Universal Content Module for FLEXIcontent doesn't save custom parameters for the template, also doesn't save if no xml file exists.

Thanks.

**Comment by micker** [comment]
yes we found the same problem
work in progress

**Comment by ggppdk** [comment]
Hello if you have advanced module manager a fix was commited today, if you do then you can test and we close this

**Comment by ggppdk** [comment]
Hello fixed in: 13a9576
included in v3 BETA6 nightly4

if you have still have problem then post back here, closing this

**Comment by ldoliv** [comment]
Hello, I’m still having problemas with the universal content module. It’s not saving the custom params. I have the latest nonumber advanced module manager.
I’m using joomla 3.4.1.



De: Georgios Papadakis [mailto:notifications@github.com]
Enviada: 14 April 2015 18:52
Para: FLEXIcontent/flexicontent-cck
Cc: Leonel Oliveira
Assunto: {Disarmed} Re: [flexicontent-cck] Univ. Content Module for FLEXIcontent, doesn't save custom params (#176)


Hello fixed in: 13a9576<https://github.com/FLEXIcontent/flexicontent-cck/commit/13a9576e2426a4ed0db09629af0bab7a47d4763e>
included in v3 BETA6 nightly4

if you have still have problem then post back here, closing this
