### ISSUE TITLE
Univ. Content Module for FLEXIcontent, doesn't save custom params

### ISSUE THREAD

**Issue by ldoliv** [FLEXIcontent/flexicontent-cck#178]
Hello,

I have the latest build nightly 4, and the latest update to advanced module manager, using joomla 3.4.1.
Custom params are saved, but it only works if the template xml file exists. When there is no file, custom1.. custom5 appear but values aren't saved.

Thanks.

**Comment by ggppdk** [comment]
aaa that is what you mean with "custom" ??

it was not clear in your previous writing, FLEXIcontent is large and some times, it is difficult to understand a user's description

i thought you meant parameters template.xml

will test this

**Comment by ldoliv** [comment]
Sorry, yes "Universal Content Module for FLEXIcontent" module, on the "Layout: ... " separator that has custom fields associated to the template that is in use.
For me it isn't saving if there is no xml file.

Thanks.

**Comment by ggppdk** [comment]
Will look at this,

but note that these parameters are not really needed now

because you can place your parameter inside the XML file (mynews.xml) of your custom template !!

"custom" parameters were added before the universal module could load and save XML files per template

**Comment by ldoliv** [comment]
Ok, thanks.

**Comment by ggppdk** [comment]
Fixed here: e58483f
