### ISSUE TITLE
Created field custom format issue

### ISSUE THREAD

**Issue by ldoliv** [FLEXIcontent/flexicontent-cck#180]
Hello,

With the "created" field, I'm trying to print the format: "April 16, 2015", the custom format I'm using is " F d, Y ".
For some reason everything after the " , " doesn't show. I'm getting "April 16".
If I try a " . " it works but not a " , ".

Thanks.

**Comment by ggppdk** [comment]
It is because of language filter the custom date format string
Fixed here: d919e7c

**Comment by ldoliv** [comment]
Thank you
