### ISSUE TITLE
Labels of fields in a fieldgroup show even if "Display Label" is set to "No"

### ISSUE THREAD

**Issue by ldoliv** [FLEXIcontent/flexicontent-cck#183]
Hello,

I have the latest flexi build, using joomla 3.4.1.
I have 2 fields in a group field, both fields have the "Display Label" to "No" but the labels still show in item view.

Thanks.

**Comment by ggppdk** [comment]
Yes, it should

but also display, is meant to better than this ...

The display variable is not yet there,
it is meant to be an HTML "templating" variable in which you can mix HTML and fields and their display methods as needed 
example:
{{field31}}
<ul>
 <li>{{field63}}</i>
 <li>{imgfield45::display_small}}</li>
</ul>

so display of field's in group is not finished !

**Comment by ldoliv** [comment]
Ok, thanks, for now I will hide it with css

**Comment by ggppdk** [comment]
Closing this in favorite of this issue: #147
please subscribe to it

**Comment by ggppdk** [comment]
See this commit: fb252f4
