### ISSUE TITLE
sélect  position broken

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#185]
Choosen select JS not applied in universal module configuration
e.g. in module position parameter

**Comment by ggppdk** [comment]
can you be more specific ?

**Comment by micker** [comment]
Go In module universal
In sélect list for position .. You van that sélect script is broken

**Comment by micker** [comment]
Select2 script isnt works d'or all sélect ans all flexi module

**Comment by ggppdk** [comment]
we do not use select2 JS in modules
i have just now added class="use_select2_lib" in one of the parameters and it was loaded properly

**Comment by ggppdk** [comment]
Disable by mistake while implementing workaroud for max_input_vars limitation.
Fixed here: ca4de0f
