### ISSUE TITLE
Field "fieldgroup" notice of unset variable (used by inline description)

### ISSUE THREAD

**Issue by ldoliv** [FLEXIcontent/flexicontent-cck#186]
Hello,

I'm using the latest release. Editing the article with fieldgroup composed of a text, textarea and image field. I'm getting the error: Notice: Undefined variable: alert_box in .../httpdocs/plugins/flexicontent_fields/fieldgroup/fieldgroup.php on line 304.

**Comment by ggppdk** [comment]
yes some small code to display the description text (instructions for item form) is missing

you have enabled showing description text in some of the fields in the group
this should be very easy to fix

**Comment by ldoliv** [comment]
Ok. Thanks

**Comment by ggppdk** [comment]
Fixed here: dc499a7
