### ISSUE TITLE
About improving the auto-generated field name

### ISSUE THREAD

**Issue by juliendude** [FLEXIcontent/flexicontent-cck#187]
We know that field Names do not allow spaces, coma or other symbol. And with rights, no problem here at all. I suppose it avoids potential errors/conflicts in code.

Why not make a similar clean-up rule than Allias. My understanding is that automatically FC would strip spaces and symbols (to respect: First character must be a-z_ followed characters a-z_0-9) from the label, while keeping upper and lower cases; field names would make more sense by default than fieldxx.

So if you type in the field label: "Dog Race", then when you hit the save button, it would make the field name be "DogRace". Right now, you just get the warning that it is not valid and has to be "First character must be a-z_ followed ....". But the field name is defaulted back to "Fieldxx".

I believe it could be a useful, although minor, enhancement.

**Comment by iamrobert** [comment]
What should happen with  non-latin alphabets - for example - Japanese and Chinese (漢字) fields names?

**Comment by ggppdk** [comment]
-- About auto-generated field name

1. the default field-name should be empty, 
2. then on save auto-generated by the name,

(while of course continuing to check if field-name is already in use)


-- About allowing UTF8 characters is not possible, 
- we use it in CSS class names which allows UTF8
- we use it in HTML tag ids, which do -not- allow UTF8

maybe we could allow - (hyphen)

**Comment by iamrobert** [comment]
Sorry - I wasn't asking for UTF8 support. 

In Joomla, if you put a title with Chinese (漢字) in the Joomla menu title- it generates an alias date string eg "2015-04-22-16-13-25". So - this seems more unfriendly than "Fieldxx" - if FLEXIcontent does it the same way. 

So - whilst this feature is promising for flexicontent labels that use latin characters - it could be problematic for other languages if the label was Chinese (漢字). Just wanted to make you aware of this issue.

**Comment by julienbenisty** [comment]
Hi ggppdk,
yes, that sounds right if you ask me. 

And yes, I would allow hyphen as well.
