### ISSUE TITLE
restrict target directory of file field to be either media or secure

### ISSUE THREAD

**Issue by Macjoomla** [FLEXIcontent/flexicontent-cck#188]
There should be the possibility to restrict the target directory of a file field to be either media or secure so users have not to decide themselves what to choose on uploading a file. It should upload, as chosen in field preferences.

**Comment by ggppdk** [comment]
we were thinking of this recently, it can be made via an extra parameter in the file field

**Comment by Macjoomla** [comment]
Great! What about appearing as selection "media", "secure", "hidden altogether"? Or did i misunderstand?

**Comment by ggppdk** [comment]
Added here: c161676

**Comment by Macjoomla** [comment]
This works great now for file inline input mode, but Inline mode, supports only single file selection. This would be important for usability of Popup input mode too.

**Comment by ggppdk** [comment]
Hello was added in popup mode the commit is just a few hours ago

**Comment by Macjoomla** [comment]
Just downloaded and installed again, but these new preferences are only appearing in inline mode. However there aren't much preferences for form field popup preferences, if you take a look at attached screenshots.
![formfield inline preferences](https://cloud.githubusercontent.com/assets/12052112/7294083/750db700-e9aa-11e4-95d2-a74a2afa64b9.png)
![formfield popup preferences](https://cloud.githubusercontent.com/assets/12052112/7294085/794949a6-e9aa-11e4-9633-18da34b514a2.png)

**Comment by ggppdk** [comment]
No release exists. Did you zip latest github repository and installed it?

**Comment by Macjoomla** [comment]
Oh, seems my fault, thought it would have been in latest release FLEXIcontent v3.0 Beta6 as this was mentioned as one of 6 commits. Sorry, i am not used to work with githup. I will try to zip latest repository or wait for next release. Sorry.

**Comment by Macjoomla** [comment]
Ok, zipped the master and installed and there it is "media, secure, allow selection" Thank you!
