### ISSUE TITLE
Bug if use Display item all and use copy/move FLEXIcontent v3.0 Beta6 

### ISSUE THREAD

**Issue by lungkao** [FLEXIcontent/flexicontent-cck#191]
Bug if use item all and use copy/move FLEXIcontent v3.0 Beta6 

if i use display all and use copy/move FLEXIcontent Redirect to  index.php?option=com_flexicontent&view=items  and don't have some button

![2015-04-24_17-02-02](https://cloud.githubusercontent.com/assets/2047778/7316799/56e30f78-eaa4-11e4-9955-bd621e93c3e4.jpg)

![2015-04-24_17-01-35](https://cloud.githubusercontent.com/assets/2047778/7316797/4ff9b98c-eaa4-11e4-8534-0dd80bf19267.jpg)

all item 162 item

i can use display 100 and copy/move it

**Comment by ggppdk** [comment]
I tested and it is as you describe,
bit newer PHP versions will tell you why it is because of max_input_vars

-- it works if you increase 'max_input_vars'
