### ISSUE TITLE
Duplicated ID's on module per-category config

### ISSUE THREAD

**Issue by Igcorreia** [FLEXIcontent/flexicontent-cck#194]
When I activate in the Universal module the per category configuration the module has the same ID in the div's:

RESULT:
![image](https://cloud.githubusercontent.com/assets/1076409/7345600/2e867250-ecce-11e4-9b89-89b29b0b82db.png)

MODULE:
![image](https://cloud.githubusercontent.com/assets/1076409/7345608/42a3355c-ecce-11e4-90fc-f6bc3b0eb630.png)

**Comment by Igcorreia** [comment]
Our suggestion:
<div class="news mod_flexicontent_wrapper mod_flexicontent_wrap<?php echo $moduleclass_sfx; ?>" id="mod_flexicontent_news<?php echo $module->id;?>_<?php echo $catdata->id; ?>">

**Comment by ggppdk** [comment]
I think replace:
<?php echo $module->id; ?>
with
<?php echo $module->id.(count($catdata_arr)>1 && $catdata ? '_'.$catdata->id : ''); ?>

Thus the extra part will be added only if we have multiple blocks (apply per category is ON)

if it is not on the id will not be modified 
- thus existing websites/installation will be not effected

**Comment by ggppdk** [comment]
Also the non unique ID is in a few other places, thus breaking multiple carousels for "Applying per category"
Also removed some CSS

Fixed here: 0633317
