### ISSUE TITLE
About improving file field 's inline mode

### ISSUE THREAD

**Issue by ldoliv** [FLEXIcontent/flexicontent-cck#197]
Hello,

Using the latest build.
By using the inline input mode of the file field, I am unable to remove the file after being selected in the field.

Thanks.

**Comment by micker** [comment]
yes inline input is a new mode without any option => if you need more use popup mode
maybe we update this mode but no now we want to stabilize first release

**Comment by ldoliv** [comment]
Ok. thanks

**Comment by ggppdk** [comment]
This needs to be made possible

**Comment by micker** [comment]
i think we can add this option in inline value:
-add value
-change value (supr old)

**Comment by Igcorreia** [comment]
+1

**Comment by ggppdk** [comment]
It was important to support "inline" mode, for simpler / more attractive forms, thus it was added in v3,

but it is not 100% finished in terms of capabilities that it must have
- these will be added in v3.1
... most notably the multi-value

but for 
- removing existing value
- changing existing value

these are needed in this version and ... they 
- were implemented / should be possible -already-
i ll verify if something in UI is wrong

**Comment by ggppdk** [comment]
In commit: f33a177

- allowed file removal for file inline mode, 
- also file cleanup (delete old one) when new file is uploaded,
- also added support for form layout templating (2 layouts available: inline-boxes and table)
