### ISSUE TITLE
Editing item in backoffice issue, long load time after saving or refresh

### ISSUE THREAD

**Issue by ldoliv** [FLEXIcontent/flexicontent-cck#199]
Hello,

I'm having problems editing an item in the backoffice and I think it's related with the fieldgroup, not sure.

The browser takes very very long to load everything after I save or refresh the page. Does not happen when first clicking the item to edit.

In the console log I get the following notices:
Resource interpreted as Image but transferred with MIME type application/x-gzip: ".../components/com_flexicontent/assets/images/comment.png".
Resource interpreted as Image but transferred with MIME type application/x-gzip: ".../components/com_flexicontent/assets/images/insert_before_180.png".
Resource interpreted as Font but transferred with MIME type application/x-gzip: ".../media/jui/fonts/IcoMoon.woff".
Resource interpreted as Image but transferred with MIME type application/x-gzip: ".../components/com_flexicontent/assets/images/move2.png".
Resource interpreted as Image but transferred with MIME type application/x-gzip: ".../administrator/components/com_flexicontent/assets/images/ajax-loader.gif".

I'm not using gzip compression.

If i use the web developer extension for chrome and disable all images. The page loads almost instantly.

I have fields of various types such as image field with multivalue not in the field group.
Fields in fieldgroup: text, textarea.
Fields not in fieldgroup: text, textarea, image with multivalue.

I would really appreciate it if you could look into this. Thanks.

**Comment by micker** [comment]
version of flexicontent ?

**Comment by ldoliv** [comment]
the latest v3.0 beta 7

**Comment by Igcorreia** [comment]
+1

**Comment by ggppdk** [comment]
will test this, to see if we are using corrected HTTP header in some cases

**Comment by ggppdk** [comment]
This should be the next thing to check / verify / fix

**Comment by ggppdk** [comment]
I cannot replicate this delay with chrome,

could it be because of references to JS or CSS to 3rd party websites ?
or due to server related configuration ?

**Comment by ggppdk** [comment]
i am closing this, if you still have a problem, then please respond

**Comment by ggppdk** [comment]
Verified form validation performance and checked for broken JS/CSS files in v3.0.8 / v3.0.9
