### ISSUE TITLE
Article Button for Links

### ISSUE THREAD

**Issue by mikeh000** [FLEXIcontent/flexicontent-cck#2]
For fields (like the image field or weblink field) that have a place for editor to type in a url, add a button next to it (labeled pages, items, articles, or whatever you want) , which would bring up a popup box of all my items in flexicontent I have created. I can then simply click on one of the items and the link to this item will be put in that URL field for me automatically. This allows me to put in links to other areas of my site MUCH quicker. You could probably use the built in ARTICLES button that comes with Joomla for this. I've seen this on many other components, which gave me the idea.

What button would look like:  http://screencast.com/t/LIIXvYz9G 
What popup box would look like:  http://screencast.com/t/wOhE5PeK

**Comment by ggppdk** [comment]
Will having a link replacement via a system plugin be useful ?

like:

{flexi_link:item  id:551}
{flexi_link:cat id:47}

{flexi_link:item  id:551  linkopen:yes}   my custom HTML </a>
