### ISSUE TITLE
All States(s) doesn't include Unpublished

### ISSUE THREAD

**Issue by iamrobert** [FLEXIcontent/flexicontent-cck#200]
Question: Wouldn't it be expected that  "ALL States" would included unpublished single states?

As - I can only view unpublished by choosing from single unpublished. I expected ALL to include those states. 

FLEXIcontent 3.0 BETA7

**Comment by ggppdk** [comment]
Hello

no item state limit is added, but category state is still added which is a different filter

i guess you have less item because category state filter is set to published

**Comment by ggppdk** [comment]
I will close this as invalid, the category of the items is not "published" and this is a different filter
