### ISSUE TITLE
Display of field filters allows using custom text as default option text, but it is ignored

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#201]
I think i found a little bug when we display a field as a filter, FLEXI_ALL language string is always used, and custom text is ignored

Example configuration: inside "Filtering" Tab
Add a default Option : yes
Default Option Text : my text
in frontend "ALL" text is displayed

**Comment by ggppdk** [comment]
Added usage of the parameters in:164faff
