### ISSUE TITLE
Bug creating new category or from existing category

### ISSUE THREAD

**Issue by ldoliv** [FLEXIcontent/flexicontent-cck#205]
Hello,

I'm using FLEXIcontent 3.0 BETA7 with Joomla 3.4.1, to save time:

1. I created a category and set all params needed, then save
2. I do save as copy, then I get:

Notice: Undefined offset: 14 in .../administrator/components/com_flexicontent/views/category/view.html.php on line 174 Notice: Trying to get property of non-object in .../administrator/components/com_flexicontent/views/category/view.html.php on line 174

I also get the message if I create a new category.

The id of the newly created category is 14.

Even if I save and close and then edit the category the notice is still there.

Update: For the error to dissapear and for the categories to appear in the category filter I had to downgrade to version 3.0.0 Beta7 nightly1.

Thanks.

**Comment by Igcorreia** [comment]
+1

**Comment by ggppdk** [comment]
Fixed in commit: 88bbd4c
