### ISSUE TITLE
Enhancement Category view by item type

### ISSUE THREAD

**Issue by ldoliv** [FLEXIcontent/flexicontent-cck#206]
Hello,

I would like to show the items in a category but be filtered by type.
I have a huge category, with categories "Industry", "Vehicle" and "Product Type" each have subcategories.

I have various content types, "Products", "White papers" and "Projects" where each type has the same category structure. I would like to only have 1 structure and not 3 category structures for each type.

Example, a project can be of a subcategory in industry, same for a product and same for a white paper.

The search view is no good because I need to get the subcategories with images.

Please add this as an enhancement. Thank you!

**Comment by ggppdk** [comment]
This is already possible, and not just by type
you can do by creating menu items and customizing them

please use our forum to ask how:
http://flexicontent.org/forum/

**Comment by ldoliv** [comment]
Ok thanks I've already figured it out.

**Comment by ggppdk** [comment]
We have a parameter "locked" / "initial" filter values.

Thus you can create hidden filters that will make the menu items behave as desired,
- the reason that ask you to post in forum, is so that more people will benefit from the answer
