### ISSUE TITLE
Try to avoid small horizontal movement during loading universal module with carousel template

### ISSUE THREAD

**Issue by ggppdk** [FLEXIcontent/flexicontent-cck#207]
When using chrome browser
during page loading a web page that uses universal module with carousel template,
threre is a small horizontal movement (and maybe scrollbar in html body)

We should try to avoid it

**Comment by iamrobert** [comment]
Whilst I haven't seen the code - typically if you wrap the carousel in the following it will hide the horizontal scroll:

.overflow-x {overflow-x: hidden;}

**Comment by ggppdk** [comment]
we are scrolling the container,
- and about adding it to parent containers, we already have external containers that have overflow-x set to hidden

**Comment by iamrobert** [comment]
Sorry - I've used owl carousel (www.owlcarousel.owlgraphic.com/) as my FLEXIcontent Module - never seem to have any issues:
https://www.visitfootball.com/en/

**Comment by micker** [comment]
you done an template with owlcarousel great !
i want to do it and propose with all option for customer (... need time)

**Comment by ggppdk** [comment]
There is no horizontal scrollbar during loading in latest chrome, rather the width of the column that has the modules changes that causes a small horizontal movement of the page

The parent containers for the module have overflow-x: hidden, so indeed there should not be a horizontal scrollbar during loading

**Comment by ggppdk** [comment]
We cannot know how much width to have so that the column of the module position will not change,
closing this

**Comment by ggppdk** [comment]
But it can be FLEXIcontent JS that manipulates body tag
-- we have such JS, to force the removal of an unneeded body scrollbar
that was added by older version of the module
this code may no longer be needed ?
TODO: check this

**Comment by ggppdk** [comment]
JS to manipulate body tag was removed, that is a few minor versions of v3.0.x ago
