### ISSUE TITLE
Make search query parameters language independent

### ISSUE THREAD

**Issue by pjmatos** [FLEXIcontent/flexicontent-cck#209]
As a suggestion, maybe the query parameter "searchword" could be something shorter and independent from any language, in order to avoid mixed languages urls. Maybe you can use the letter "q", such as used by Google: www.site.com/search?q=example

This was originally asked here:
http://www.flexicontent.org/forum/21-troubleshooting/53661-search-issues-with-languages-and-sef.html

Where you also commented:
"we would also want to possible replace our filter_NN= with e.g. q_fieldname in regards of field filters too"

**Comment by ggppdk** [comment]
Done for seach view in this commit: 9016029

Changed: searchword, searchphrase
to be: q, p, o

For field filter names, we will examine doing this in v3.1, as it will need more through testing
