### ISSUE TITLE
In type configuration "Custom Fields for Items List" in "Items Manager" TAB

### ISSUE THREAD

**Issue by ldoliv** [FLEXIcontent/flexicontent-cck#215]
Hello,

I'm using the latest release. I've tried placing the field id in global configuration and in type configuration.

The column appears but doesn't display any value. I've tried with image type field and with radio field.

**Comment by ggppdk** [comment]
I have tested,
please check description of the parameter,
you need to use field name and and not field id

e.g. 
myimage, myradio

e.g.
myimage:display_small, myradio

thanks for all of your feed back )),  you can also use forum for submitting bugs

if you have used fieldname then post back here, and it does not work the you can post back here
if you want to discuss the feature of custom columns you can post to our forums

**Comment by ldoliv** [comment]
I tried with the field name by itself and various properties and nothing, doesn't seem to be working for custom fields. Works for core fields.

**Comment by ggppdk** [comment]
I am guessing you have used correct field name

since i cannot replicate this
please login to our forums and send me a PM with admin access

**Comment by ldoliv** [comment]
Hello, I sent you a PM in the forum. Thanks!
