### ISSUE TITLE
Add per usergroup authoring configuration (e.g. max_uploadsize for files)

### ISSUE THREAD

**Issue by ghost** [FLEXIcontent/flexicontent-cck#218]
For some purposes it would be handy to have a separate max_uploadsize for the file-upload for e.g. admin and normal user, of that kind that for example the admin shall be able to upload files up to 10MB the normal user otherwise should only be able to upload files up to 3MB.

best regards D. Kring

**Comment by ggppdk** [comment]
We can add this together with other usergroup configuration planned for v3.1

**Comment by ggppdk** [comment]
Worked started on both revising upload manager and on per user-group limits
