### ISSUE TITLE
Update Select2 library to 4.0.0

### ISSUE THREAD

**Issue by Igcorreia** [FLEXIcontent/flexicontent-cck#228]
Current is 3.5

**Comment by ggppdk** [comment]
We can update select2.js in v3.1, i think we can upgrade select2 JS to 4.0+ in v3.1, to avoid breaking something in v3.0.x

**Comment by Igcorreia** [comment]
Perfect.

**Comment by ggppdk** [comment]
Closing this. I have not posted but the update was never made because the select2 JS v4.x is very slow when having many options !

We will replace select2 JS with choice.js , which a good alternative and also it was selected to be used in J4 , replacing the chosen.js that is used in J3
