### ISSUE TITLE
Component configuration doesn't save

### ISSUE THREAD

**Issue by Lyquix** [FLEXIcontent/flexicontent-cck#23]
FC 2.2.0 stable (r1974)
J! 3.3.6

When attempting to Save (not Save & Close) changes to the Flexicontent component configuration, the  page loads Joomla Global Configuration page (instead of staying in Flexicontent Configuration), no alert box is displayed indicating that the changes have been saved, and when going back to the Configuration page the values are still the default ones.

**Comment by ggppdk** [comment]
Recently added wokaround that serializes the full form into a single variable,

-- this workaround is automatically applied if the estimated form variables are close to the max_input_vars e.g. (<100)

-- the workaround will be activated in these cases:
a. component form
b. item / category form
c. universal content module

closing this
