### ISSUE TITLE
Import function is missing the Access Level field (registered, super user, public, ...)

### ISSUE THREAD

**Issue by woluweb** [FLEXIcontent/flexicontent-cck#235]
See http://www.flexicontent.org/forum/30-feature-requests/53894-import-no-access-level-field-for-importation-to-choose-registered-directly-during-importation

**Comment by ggppdk** [comment]
+Added field and column support in 1ae6766
Please click zip to download and install
(our default "master" branch is selected by default which will be v3.0.3)

![impoved_import](https://cloud.githubusercontent.com/assets/5092940/8891209/0e035a4c-3329-11e5-83bc-f132d27cdadb.png)
![impoved_import2](https://cloud.githubusercontent.com/assets/5092940/8891218/36c7353e-3329-11e5-8624-46db85c0dfb9.png)
