### ISSUE TITLE
Items manager translate task button, new items aren't associated

### ISSUE THREAD

**Issue by ldoliv** [FLEXIcontent/flexicontent-cck#241]
Hello,

I'm using FLEXIcontent v3.0.4 with joomla 3.4.3.
I can use the translate task button to translate an item from EN to PT but then they are not associated. I know in previous versions of flexi this was automatic. Is this an issue ?

**Comment by ggppdk** [comment]
You must mean the translate task button in items manager, i have corrected your issue text to be more clear. 

Yes translate task needs to load associations of the item being copied , add new item to them and save the associations

**Comment by ldoliv** [comment]
Thanks for support

**Comment by ggppdk** [comment]
Fixed in 6865485

Also improved language field making it required and removed from it the meaningless option for language 'ALL'
