### ISSUE TITLE
Add new filter display types: slider and slider range, via popular noUiSlider JS

### ISSUE THREAD

**Issue by ggppdk** [FLEXIcontent/flexicontent-cck#244]
This is almost done, and needs to finish testing, 
we are using noUiSlider

implemented support for displays and add relevant parameters to 15 fields (text, select, radioimage, checkbox, etc):
- slider
- slider range

the above sliders are using either:
- either field's found values
- or custom entered values/labels 
both the above can be alphanumeric, inside the JS slider we use numeric values (noUiSlider needs numeric values) and do a remap to the real values

Also these are configurable
- percentage placement (thanks to noUiSlider JS)
- min and max values are empty (aka ANY value) for found values, and can be empty for custom values
- labels appear as tooltips (max is 36 characters, currently not configurable) and we try to make auto placement of the labels so that they do not overlap in the case of range

**Comment by micker** [comment]
great adding !

**Comment by ggppdk** [comment]
Commited in 3cfa25e

This issue will be open for a while until this is tested a little more
- Using the new JS lib noUIslider and the knowledge gained by implementing the filter displays we can create 2 or more indexable fields (fields: value-label value-label-image) 

![new_filter_display_slider_conf](https://cloud.githubusercontent.com/assets/5092940/9155033/d2ed58d2-3eb2-11e5-8679-11015e8eaa67.png)
![new_filter_display_slider1](https://cloud.githubusercontent.com/assets/5092940/9155034/d2f2c970-3eb2-11e5-8e9f-55b217b734e0.png)

- now we have 
select, selectmultiple,
checkbox, checkboximage,
radio, radioimage

- we can add fields
a. slider / slider range
b. color picker (that will use as an option slider display)
c. or use slider in other fields ?

**Comment by micker** [comment]
very  good 
adding In date field i think will be good 
very good adding
