### ISSUE TITLE
FLEXIcontent UX suggestion

### ISSUE THREAD

**Issue by iamrobert** [FLEXIcontent/flexicontent-cck#245]
Do you think the UX would be improved for the top headers - if we add a tooltip and also btn-wrapper input-append like Joomla 3 administrator does?

`<div class="btn-wrapper input-append fc-filter"> <span class="filter-search btn-group">
          <input type="text" name="search" id="search" placeholder="<?php echo JText::_( 'FLEXI_SEARCH' ); ?>" value="<?php echo htmlspecialchars($this->lists['search'], ENT_QUOTES, 'UTF-8'); ?>" class="inputbox" />
          </span> <span class="btn-group hidden-phone">
          <button title="<?php echo JText::_( 'FLEXI_SEARCH' ); ?>" class="<?php echo $btn_class; ?> <?php echo $tip_class; ?>" onclick="document.adminForm.limitstart.value=0; Joomla.submitform();"  data-original-title="<?php echo JText::_( 'FLEXI_SEARCH' ); ?>"><?php echo FLEXI_J30GE ? '<i class="icon-search"></i>' : JText::_('FLEXI_GO'); ?></button>
          <button title="<?php echo JText::_('FLEXI_RESET_FILTERS'); ?>" class="btn hasTooltip" onclick="document.adminForm.limitstart.value=0; delAllFilters(); Joomla.submitform();"><?php echo FLEXI_J30GE ? '<i class="icon-remove"></i>' : JText::_('FLEXI_CLEAR'); ?></button>
          </span> </div>`

**Comment by iamrobert** [comment]
<div id="fc-filters-header">
        <div class="btn-wrapper input-append fc-filter"> <span class="filter-search btn-group">
          <input type="text" name="search" id="search" placeholder="<?php echo JText::_( 'FLEXI_SEARCH' ); ?>" value="<?php echo htmlspecialchars($this->lists['search'], ENT_QUOTES, 'UTF-8'); ?>" class="inputbox" />
          </span> <span class="btn-group hidden-phone">
          <button title="<?php echo JText::_( 'FLEXI_SEARCH' ); ?>" class="<?php echo $btn_class; ?> <?php echo $tip_class; ?>" onclick="document.adminForm.limitstart.value=0; Joomla.submitform();"  data-original-title="<?php echo JText::_( 'FLEXI_SEARCH' ); ?>"><?php echo FLEXI_J30GE ? '<i class="icon-search"></i>' : JText::_('FLEXI_GO'); ?></button>
          <button title="<?php echo JText::_('FLEXI_RESET_FILTERS'); ?>" class="btn hasTooltip" onclick="document.adminForm.limitstart.value=0; delAllFilters(); Joomla.submitform();"><?php echo FLEXI_J30GE ? '<i class="icon-remove"></i>' : JText::_('FLEXI_CLEAR'); ?></button>
          </span> </div>
        <?php $_class = FLEXI_J30GE ? ' btn' : ' fc_button fcsimple fcsmall'; ?>
        <div class="btn-wrapper btn-group">
          <input type="button" id="fc_filters_box_btn" class="<?php echo $_class.($this->count_filters ? ' btn-primary' : ''); ?>" onclick="fc_toggle_box_via_btn('fc-filters-box', this, 'btn-primary');" value="<?php echo JText::_( 'FLEXI_FILTERS' ); ?>" />
          <input type="button" id="fc_mainChooseColBox_btn" class="<?php echo $_class; ?>" onclick="fc_toggle_box_via_btn('mainChooseColBox', this, 'btn-primary');" value="<?php echo JText::_( 'FLEXI_COLUMNS' ); ?>" />
        </div>
       
       
         <span class="limit btn-group pull-right hidden-phone">
        
        <?php
				$pagination_footer = $this->pagination->getListFooter();
				if (strpos($pagination_footer, '"limit"') === false) echo $this->pagination->getLimitBox();
				?>
      
        <?php if (($getPagesCounter = $this->pagination->getPagesCounter())): ?>
        <?php echo $getPagesCounter; ?>
        <?php endif; ?>
        </span> 
       
       
        </div>

**Comment by ggppdk** [comment]
This was done in all backend listings,
- appending buttons go and reset to the search input 
- pagination was moved to the end
- and also some layouts to make top row more compact
closing this
