### ISSUE TITLE
Display problems with fieldgroup

### ISSUE THREAD

**Issue by Jebyl** [FLEXIcontent/flexicontent-cck#258]
Say you have 2 fields:

Aspect Ratio
Sound Mix

Both are usable in fieldgroups.

Then you have 2 document types:

Film with Aspect Ratio field (stand-alone) and Sound Mix field (stand-alone)
DVD with fieldgroup "Video Tracks" with "Aspect Ratio" in it and fieldgroup "Audio Tracks" with Sound Mix in it.

When both document types use the same template, you'd want the fields only to appear either with DVD in the fieldgroups or with Film as stand-alone fields, right?

Problem is, when you set these fields to Film and DVD they all show up (so both the fieldgroups and the standalone fields). I tried removing DVD from the standalone fields and only having the fieldgroups keep the DVD type, but that means that those fields are shown but can not be saved. Can this be fixed?

**Comment by ggppdk** [comment]
You say:
When both document types use the same template

why use the same template for 2 different content types ?

**Comment by Jebyl** [comment]
I have a default template for most content types. It consists of an image on the top with details next to it and underneath in the tabs it has all the information (altough I change the Tab names in the configuration of the template per document type). It should be possible to have the same template for multiple document types, no?

I've also noticed that when you use a groupable field multiple times it inherits the data from the other groupfields. For example:

I put in fieldgroup "Audio Tracks":
English as language
Dolby Digital as format
5.1 as Channels

Automatically "Subtitles", that also uses the language field, will show:
English as language

When I haven't even added any data to that fieldgroup?

**Comment by ggppdk** [comment]
about inheriting data, i am not sure that i understand you,

please open a new forum thread in our forum, we can discuss this there

**Comment by ggppdk** [comment]
Are you using the same field in 2 field groups ?

**Comment by ggppdk** [comment]
Ok this was resolved in forum, 
a field is not allowed to be used in 2 field groups
closing this, if the above is not the case, then please post back with details
