### ISSUE TITLE
Add option to hide Add New Article & New Category in Top Menu

### ISSUE THREAD

**Issue by iamrobert** [FLEXIcontent/flexicontent-cck#265]
The new article and new category links don't work - so is confusing for the average user.

![new-article](https://cloud.githubusercontent.com/assets/8617673/9293251/d55d5650-4455-11e5-9c32-e205a9016429.png)

If the following css is added - it will hide the links:
.dropdown-toggle.menu-article:after, .dropdown-toggle.menu-category:after {display: none !important;}

#menu-com-content, #menu-com-categories-com-content {display: none !important;}

It could be further refined to an option in FLEXIcontent configuration.

**Comment by ggppdk** [comment]
Instead of hiding them we have added redirection to the respective FLEXIcontent new item and new category forms, fixed in commit 2a5bf49
