### ISSUE TITLE
Add default image parameter to blog template

### ISSUE THREAD

**Issue by lungkao** [FLEXIcontent/flexicontent-cck#276]
Blog template can benefit of 2 parameter (leading, standard) to specify default image tp be used in case of "extract image from text" but also for the case of using an image field

**Comment by ggppdk** [comment]
I think the format of the parameters should be:
- single image
- or a comma seperated list of images
typealias1:default_image1, typealias2:default_image2,  typealias3:default_image3

**Comment by lungkao** [comment]
great !!

**Comment by ggppdk** [comment]
Added with 8eb53c1
