### ISSUE TITLE
Email addresses displayed by email field are not always clickable

### ISSUE THREAD

**Issue by amkmonk** [FLEXIcontent/flexicontent-cck#278]
plugins/flexicontent_fields/email/email.php 

Third argument in
```php
JHTML::_('email.cloak', $addr, $addr!=$text, $text, $text_is_email)
```
 must always be 1 or true
```php
JHTML::_('email.cloak', $addr, 1, $text, $text_is_email)
```

**Comment by ggppdk** [comment]
Maybe this should be a parameter, with default value YES

**Comment by amkmonk** [comment]
Yes, it is even better.

**Comment by ggppdk** [comment]
This was added in v3.0.9-dev and will be in v3.0.9
