### ISSUE TITLE
Does the global htmlmode in the FLEXIcontent configuration exist?

### ISSUE THREAD

**Issue by iamrobert** [FLEXIcontent/flexicontent-cck#279]
Currently the code gives the global option to set html5 - but I can't find this setting in FLEXIcontent configuration. Does it exist?

Also could we please make the default setting html5 - its the default for Joomla 3. 

````
<field name="htmlmode" type="radio" default="" label="FLEXI_HTML_MODE" description="FLEXI_HTML_MODE_DESC" filter="int" class="btn-group btn-group-yesno">
				<option value="">FLEXI_USE_GLOBAL</option>
				<option value="0">FLEXI_XHTML</option>
				<option value="1">FLEXI_HTML5</option>
			</field>
````

**Comment by ggppdk** [comment]
There is the global template setting at template manager

**Comment by iamrobert** [comment]
Thanks - but I don't see it:
![download 1](https://cloud.githubusercontent.com/assets/8617673/9648427/0698969e-521b-11e5-9f81-aee05edca815.png)

**Comment by ggppdk** [comment]
but i said in template manager , inside every layout, not in component permissions

- this setting is not meant to exist in all templates, 
- some may have it , some may not have it

e.g. some new templates may only be HTML5 and will not have the setting
