### ISSUE TITLE
Single property fields text, 'select, selectmultiple is useful to have a prefix / suffix in item form

### ISSUE THREAD

**Issue by ggppdk** [FLEXIcontent/flexicontent-cck#284]
It is useful to allow a prefix / suffix

2 ways:
- display before / after the form field element
- display inside the form field, by either using CSS or by using jQuery inputmask JS (the suffix/prefix will not be part of the value, it should just be displayed)

**Comment by ggppdk** [comment]
we need 4 parameters:
Item Form Prefix/Suffix
1. Prefix  (text parameter)
2. Prefix position   (radio parameter) 
- before form field
- inside form field (by loading and using jquery inputmask)

Similar for "Suffix", will be parameters 3. 4.

**Comment by iamrobert** [comment]
Could we also please have the ability to add a class to a field? If we had the ability to add a class - we could make the field the right size or hide the field if its not needed.

**Comment by iamrobert** [comment]
Hi Bootstrap has the ability to add before and after input:

http://codepen.io/anon/pen/JYGPXR

````
<div class="input-prepend input-append">
  <span class="add-on">$</span>
  <input class="span2" id="appendedPrependedInput" type="text">
  <span class="add-on">.00</span>
</div>

````



Could this work?

**Comment by ggppdk** [comment]
Actually i am thinking to do this with jquery inputmask:
 prefix: '',
 unmaskOnSubmit: true

But this is more important work being done into the field, to make it easier to configure and display numbers and currency and other custom types !
![improved_text_field](https://cloud.githubusercontent.com/assets/5092940/9837306/4a33d7da-5a43-11e5-9d4e-8ffbb9ac171c.png)
![improved_text_field0](https://cloud.githubusercontent.com/assets/5092940/9837307/4a3457be-5a43-11e5-8c58-ba79e37cde6a.png)
![improved_text_field2](https://cloud.githubusercontent.com/assets/5092940/9837305/4a321a26-5a43-11e5-995f-274b976936d7.png)
![improved_text_field3](https://cloud.githubusercontent.com/assets/5092940/9837308/4a3752de-5a43-11e5-9e6e-e04f1000d3e1.png)
![improved_text_field4](https://cloud.githubusercontent.com/assets/5092940/9837309/4a39963e-5a43-11e5-82f1-684373be184c.png)
![improved_text_field5](https://cloud.githubusercontent.com/assets/5092940/9837310/4a39e1b6-5a43-11e5-971d-9950bdd633d6.png)


- Also i think we may need a JForm text-select element for the prefix, Joomla does not have such and it will make easier to add Euro into the prefix while allowing user to type too, otherwise we will need 2 parameters for prefix and to for suffix too

**Comment by ggppdk** [comment]
The option to execute 
- custom PHP code for formating output value is being added to text field,
but i see that it will be useful in ALL single property fields, 

this will greatly enhance usefulness of the fields and make custom output possible,
without need of custom field value template file in most cases

**Comment by iamrobert** [comment]
This is very exciting!

**Comment by micker** [comment]
very  powerfull

**Comment by ggppdk** [comment]
Finished this with commits:
acd2f41, f290d8a
