### ISSUE TITLE
PHP notices in fields manager when listing fields that are assigned to an unpublished type

### ISSUE THREAD

**Issue by iamrobert** [FLEXIcontent/flexicontent-cck#287]
If a FLEXIcontent type is unpublished - it gives the following php notice:

Notice: Undefined offset: 13 in ..\administrator\components\com_flexicontent\views\fields\tmpl\default.php on line 589 
Notice: Trying to get property of non-object in ..\administrator\components\com_flexicontent\views\fields\tmpl\default.php on line 589

![download](https://cloud.githubusercontent.com/assets/8617673/9836552/97812e90-5a50-11e5-9913-b47f3abb98b1.png)

Publishing the content type - removes the warning.

It is this code:

````
<?php
if (count($row->content_types))
	foreach($row->content_types as $type_id) echo '<span class="badge">'.JText::_($this->types[$type_id]->name).'</span>';
	else
echo '<span class="badge badge-warning">'.JText::_('FLEXI_NONE').'</span>';
?>

I'm not sure how to add the if published

**Comment by ggppdk** [comment]
Ok the SQL query does not retrieve unpublished types, this should be simple to fix
