### ISSUE TITLE
Fields with same labels can not be distinguished in various places of backend configuration 

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#288]
It is rare but in some situations, we need to create fields with same label

Then in backend configuration we cannot identify these fields only by seeing their label in a select drop-downs

e.g.
we want to select fields in fieldgroup or in cascading,
we will see 2 fields with same label making it difficult to distinguish them

Solution would be to use:

Label [field-name]
or
Label [field-id]

**Comment by ggppdk** [comment]
Added with 129df3a

Only the fields that have the same label will be appeneded with ID, thus avoiding this for the usual case that labels are different.
This was added for parameter of type "filelds" and of type "filters"
