### ISSUE TITLE
Joomla 3.4.4 and FC don't work and v3.0.7

### ISSUE THREAD

**Issue by ldoliv** [FLEXIcontent/flexicontent-cck#289]
After install, just go to edit one item. It gives SQL error.

FLEXIcontent 3.0.7-dev

**Comment by ggppdk** [comment]
so we are using v3.0.7-dev and not v3.0.8 or v3.0.9-dev ?

**Comment by ggppdk** [comment]
Hello

also besides having new version, which you should check

- most important is, why have you not written the error text of the SQL above ?!

in general, please check our forums and better post in the forums,
to confirm a bug
http://www.flexicontent.org/forum/

also regardless of this issue, please see changelogs of v3.0.7, v3.0.8 and v3.0.9-dev
https://github.com/FLEXIcontent/flexicontent-cck/releases

finally please post the error text here

**Comment by ldoliv** [comment]
The error I'm getting is:
DateTime::__construct() [<a href='datetime.--construct'>datetime.--construct</a>]: Failed to parse time string (Never) at position 0 (N): The timezone could not be found in the database

**Comment by ggppdk** [comment]
But this is not an SQL error, 
- it is an exception of PHP class DateTime
maybe you were confused by word "database" that the message has

- this has been answered in our forums, plus it is in our changelog of v3.0.8 (released a week ago), you should have a message of new version in FLEXIcontent's backend dashboard

(change log in both places)
- here in GitHub
- in our latest download at flexicontent.org
http://www.flexicontent.org/downloads/latest-version.html


please use forums for bug reports before opening an issue here

**Comment by ldoliv** [comment]
Ok, thank you

**Comment by ggppdk** [comment]
thanks for feeback
