### ISSUE TITLE
Administrator ORDER non-functional at front-end

### ISSUE THREAD

**Issue by noxidsoft** [FLEXIcontent/flexicontent-cck#295]
Re-ordering articles/items within a category, doesn't change anything at the front-end.

Joomla 3.4.1-3.4.4
Chrome Version 45.0.2454.93 (64-bit)
PHP 5.5.26

The screenshots are from a localhost, but I can confirm the same issue occurs on a 2 x production servers. Please test this away from your dev servers before asking for access to our server(s), it's a gov one, so access can't be given to third parties.

<img width="1404" alt="screen shot 2015-09-22 at 11 18 57" src="https://cloud.githubusercontent.com/assets/729135/10009150/d2467af4-611b-11e5-966b-52d5b4ab0f7f.png">
<img width="820" alt="screen shot 2015-09-22 at 11 19 07" src="https://cloud.githubusercontent.com/assets/729135/10009151/d247547e-611b-11e5-97ef-7761596f4309.png">

**Comment by micker** [comment]
flexicontent version @

**Comment by noxidsoft** [comment]
Ahhh, the one thing I forgot to add the version of, my bad.

FLEXIContent 3.0.8 - 9 Sept 2015

**Comment by ggppdk** [comment]
You have set the wrong order, you want to order items in "Joomla" category view,
the ordering that you have set is for "FLEXIcontent" category view

- in items manager please use (click FILTERS) and set "Order type" = Joomla

Explanation (see popup description of it)
- FLEXIcontent ordering is per category,
because in FLEXIcontent an item can belong to many categories,
- so it has multiple orderings, 1 ordering per category,
this applies too, if item is only in 1 category

**Comment by ggppdk** [comment]
Please confirm, if you have still have an issue, i will re-open this

**Comment by noxidsoft** [comment]
Oh dear, that's embarrassing. Am I able to set this permanently for every session and every authorised user? e.g. in "Configuration" set an option to always load "Joomla" Order Type, as opposed to "FLEXIcontent" ?

**Comment by ggppdk** [comment]
I see,

we have some component parameters for items manager, like default backend order, and extra columns and extra filters,

we can add a parameter for default backend order too

**Comment by noxidsoft** [comment]
That would allow further flexibility as in our case where the client wants to keep their native Joomla views at the frontend but use FLEXIcontent to manage from the backend.

Do you think I should override for now, as in, change the code to put "Joomla" ordering in first place for the dropdown?

**Comment by ggppdk** [comment]
Closed in favour of: #301
