### ISSUE TITLE
Menu item - breadcrumb pathway depth setting is being ignored

### ISSUE THREAD

**Issue by ldoliv** [FLEXIcontent/flexicontent-cck#297]
Hello I'm using, FLEXIcontent 3.0.9-dev2 
if i Choose "root" or "level5" it's the same, parent categories are added anyway to the breacrumbs path for article items under this menu item.
What i Mean is:
/bedrooms (category menu item - WORKS FINE)
/bedrooms/item/65-familly-suite (NOT OK, parent categories are being included)
![image](https://cloud.githubusercontent.com/assets/6535818/10107174/2c309d64-63b1-11e5-82eb-e9b701c9178e.png)
My categories have only a max depth of 2

Please check this issue. Thanks!

**Comment by ggppdk** [comment]
This is done deliberately.
Before activating menu item parameters, a check is done that:

- current menu item matches the current view, if it does not then menu parameters are not used

you have a
- category menu item and 
- 2nd example that you provided is item view

but you can argue / suggest about a behaviour change

**Comment by ldoliv** [comment]
Yes, they have the same id but differente views.
/bedrooms has menu item id Itemid: "452"
/bedrooms/item/65-familly-suite has menu item id Itemid: "452"

So how can i affect the breadcrumb path, so that it only starts to add parent categories at a high depth, say 5 for the item view ?

**Comment by ggppdk** [comment]
I see, the the breadcrumb depth parameter of the menu,
should be used
- if the item belongs to the item belongs to the category
- it in any case, without any checks ?

**Comment by ldoliv** [comment]
Sorry I don't understand your question "it in any case, without any checks ?"

**Comment by iamrobert** [comment]
Is this also linked to the category issue I am having?
http://www.flexicontent.org/forum/21-troubleshooting/54125-duplicate-urls.html#57500

**Comment by ggppdk** [comment]
Changed behaviour with 6f8407b
