### ISSUE TITLE
Add microdata support to fields Date/Publish Up/Down 

### ISSUE THREAD

**Issue by ggppdk** [FLEXIcontent/flexicontent-cck#299]
Relevant forum thread:
http://www.flexicontent.org/forum/30-feature-requests/54120-microdata-support-for-date-publish-up-down-field.html

**Comment by ggppdk** [comment]
These seem to be what we need to use:

dateCreated 	Date 	The date on which the CreativeWork was created.
dateModified 	Date 	The date on which the CreativeWork was most recently modified.
datePublished 	Date 	Date of first broadcast/publication.

**Comment by micker** [comment]
i didnt implement  yet because need  more works
<time itemprop="startDate" datetime="2011-05-08T19:30">May 8, 7:30pm</time>
need to add without use user format date

**Comment by ggppdk** [comment]
Added microdata supported to fields created, last modified, date with commit 0903a6a
Alternatively prefix/suffix/opentag/closetag parameters can still be used
