### ISSUE TITLE
Photo/video gallery and Hours of operation fields

### ISSUE THREAD

**Issue by Lyquix** [FLEXIcontent/flexicontent-cck#306]
Hello guys, I just wanted to let you know that we will be working on some js/css to use with the default photo gallery to make it work as a photo/video gallery. The plan is to use one of the meta data fields available for each photo (e.g. link, title, alt, or description) to insert a Youtube or Vimeo URL. With js/css will pop up a lightbox and if this URL is available a video player is loaded and started on the spot. As you can see the uploaded image only serves as a thumbnail for the video.

We will also be updating an "Hours of Operation" field: it allows to enter hours of operation for a business. You can set different hours for each day of the week, or group them in weekdays and weekends. We might add some more options as we do that work.

**Comment by ggppdk** [comment]
Hello,
are you speaking of doing work on the image/gallery field ?

**Comment by Lyquix** [comment]
Not initially, we will develop some custom JS for the project that uses the existing output from the field. I will then share it with you so that you can evaluate if you would like to add it to the codebase.

**Comment by Lyquix** [comment]
Here is an example:
https://www.pennoni.com/how-to-work-here

We used an image field, with the URL extra info field enabled. We developed JS code that provides the lightbox and checks if the URL value is a YouTube URL, in which case it loads the player when you open that thumbnail.

Further thoughts on this:

* Perhaps we can integrate this in the existing media field, or maybe we create a new media gallery field. This would be specific for multi-media and provide the gallery and lightbox functionality
* I would like to incorporate some of the nice code we developed for the sharedmedia field (fetching media info from API)
* Maybe it is an opportunity to evolve the images field: treat images as a special content item (not just mere files); control access to the original and thumbnails; use db-mode always; create a sensible folder structure for storage

**Comment by micker** [comment]
i think the best way will be to add template system to image galerie field
- 1 template peer galerie type with js import
=> 1 elastic slide, fancybox etx ...
it will be good to add and re use new script to create specific galerie
=> and maybe leave basic galerie template and create a advanced pack with more script

**Comment by micker** [comment]
added
