### ISSUE TITLE
Improve relation field, revising UI and adding AJAX loading for the listed items

### ISSUE THREAD

**Issue by ggppdk** [FLEXIcontent/flexicontent-cck#309]
The relation fields needs improving in both its UI and make it AJAX load the items, thus reducing item form load time and memory requirements in large websites

**Comment by ggppdk** [comment]
A relevant forum thread is:
http://www.flexicontent.org/forum/27-field-plug-ins-core/54145-enable-double-click-to-select-items-on-relation-field.html

**Comment by gardenho** [comment]
I believe it would be a great enhancement if the relation field item selector showed the item ID appended to the beginning of the item title much the same way it appends (p) currently to indicate published status.  This would allow for easier and quicker selection when categories contain thousands of items.

**Comment by ggppdk** [comment]
Closing this is issue
- added new compact UI
- ajax loading
- new option to for for selected items to be sortable and new ordering for ('Manual order')
- fixed the submit related feature
- restructure configuration
- other ...

@gardenho 
for any other enhancement  please open new issue
