### ISSUE TITLE
Plupload script does not work without FLASH and custom language files of the script are not loaded

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#322]
plusupload script have 2 problem
- no upload zone => display a message for enable flash existing solution, click twice on button for changing uplaod system
maybe need to change runtime order like  runtimes : 'html5,flash,silverlight,html4',
- script includes custom language files
http://www.plupload.com/docs/Plupload-in-Your-Language
but these are not loaded

**Comment by micker** [comment]
with firefox image is dipslay in queue twice (upload only one filed)

**Comment by ggppdk** [comment]
Added loading of language files
- the for this is the sames as for the language files of select2 JS

**Comment by ggppdk** [comment]
FLASH error with Plupload script,
seems to be happening in linux installations ?

**Comment by micker** [comment]
Not only on windows too ff ans chrome
Le 11 nov. 2015 6:00 PM, Georgios Papadakis <notifications@github.com> a écrit :FLASH error with Plupload script,
seems to be happening in linux installations ?

**Comment by ggppdk** [comment]
The message about flash is misleading / wrong, correct message is:

There was some JS error or JS issue, plupload script failed to start

**Comment by ggppdk** [comment]
Fixed and updated plupload script with: 7dd6b4f
