### ISSUE TITLE
Fieldgroup field needs a parameter for forcing field label to hide when field has no value

### ISSUE THREAD

**Issue by ggppdk** [FLEXIcontent/flexicontent-cck#335]
When a field does not have a value in a fieldgroup it is oftern desirable to hide the label.

We need a parameter with fields that should not display their label if no value was given to them

**Comment by micker** [comment]
+1

**Comment by ggppdk** [comment]
Also this parameter of fieldgroup field, should skipping adding empty containers for the field values
Added with: 0135bb3
