### ISSUE TITLE
Fields: minigallery and file, do not save values when inline-edit mode is disabled

### ISSUE THREAD

**Issue by miken912** [FLEXIcontent/flexicontent-cck#340]
FLEXIcontent v3.0.9-2015_10_31 (v3.0.9-rc)

Not saved photos are not added photos in the admin interface. when the use of the field minigallery

**Comment by ggppdk** [comment]
Hello try with this one
https://github.com/FLEXIcontent/flexicontent-cck/releases/tag/v3.0.9-2015_11_06

resave item if needed

**Comment by miken912** [comment]
Updated. Resave item. Not work

**Comment by ggppdk** [comment]
Fixed with: d47f347

**Comment by miken912** [comment]
Correction partial!
![qip shot - screen 244](https://cloud.githubusercontent.com/assets/11311850/11025932/158f6f14-86c4-11e5-996d-8b06f5da0271.jpg)

**Comment by ggppdk** [comment]
I see will fix this too

**Comment by ggppdk** [comment]
Fixed upload too, with: 5227875
