### ISSUE TITLE
Joomla template override of image icons seem to be broken

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#344]
i think it's realy an old bug
override image like this documentation seems doesn't work
http://www.flexicontent.org/documentation/faq/69-templating-module-plugin-content/293-overriding-frontend-flexicontent-icons-via-template.html
putting image in /templates/my-template/images/
but override doesn't work 
flexicontent.helper/php line 2716
thanks

**Comment by ggppdk** [comment]
Yes,
this sounds like a bug, we either switch to font-icons or fix this

Which icon are you trying to override ?

**Comment by micker** [comment]
i try hear login

**Comment by ggppdk** [comment]
Better solution, which wanted to do for quite some time ... added 
- Font-Based icons
with: cb92362

See below, also the new style for table of contents is shown

![font_icons_support](https://cloud.githubusercontent.com/assets/5092940/11614432/463e5ef8-9c4b-11e5-8da1-126ce4b597c2.png)
![font_icons_support2](https://cloud.githubusercontent.com/assets/5092940/11614433/48fbb92e-9c4b-11e5-9997-1694916a6389.png)
![font_icons_support3](https://cloud.githubusercontent.com/assets/5092940/11614434/4b57247e-9c4b-11e5-8344-31eaab0746db.png)
