### ISSUE TITLE
About adding RANDOM ordering option to item listing views

### ISSUE THREAD

**Issue by Lyquix** [FLEXIcontent/flexicontent-cck#347]
Hello all! I am currently working on a project where I need to order related items in RANDOM order.

And then I noticed that the option for random order is not available for the Relation fields, nor the Categories.

I can add that option to the code, but I wanted to check with you first if there is any reason for NOT having that option. Thank you!

**Comment by ggppdk** [comment]
Hello, you can make a pull request

----
- all existing order cases are inside file:

site/classes/flexicontent.helper.php
static function _getOrderByClause(...)

(open file and search to find):
```
case 'random':
	$order_col	= 'RAND()';
	$order_dir	= '';
	break;
```

----
-- the above case is used by form element (parameter) type="fcordering"

admin/elements/fcordering.php

currently used by universal module only

----
- You can add a new case in the site/classes/flexicontent.helper.php, or just try using the existing case, and then (try) changing files (for existing case use:  value="random"):

admin/models/forms/category.xml
admin/config.xml
and to the frontend menu items:  site/views/category/*.xml
and:  plugins\flexicontent_fields\relation\relation.xml


&lt;option value="random"&gt;FLEXI_ORDER_RANDOM&lt;/option&gt;

- also add the language string to the backend ini file of the component (search for:)
```
; Core field / property orderings options
```

**Comment by Lyquix** [comment]
Ok, we will take care of it and submit a pull request

**Comment by ggppdk** [comment]
Merged

**Comment by ggppdk** [comment]
Please note that the randomization will happen on the 2nd page too, thus some items of previous page may appear in subsequent pages.

Future improvement:
- store (e.g. 2000) ids of into session per URL,
eg for the last 20 opened URLs (including alll filtering variables and excluding page number)

the above is also one of the needed things to start implementation of endless scroll feature too

**Comment by ggppdk** [comment]
Thinking again best is to use the same SEED in the mysql, and change it every 1 hour ?

**Comment by Lyquix** [comment]
I didn't think about what should be the behavior for pagination across multiple pages. 

To be honest we were inly thinking of the relation and relation-reverse fields but thought it would be a good option to have in categories as well. 

Perhaps we should wait to see for a real use case before we create a more complicated mechanism? 
For me it is hard to think a situation where you need a category view sorted randomly AND need pagination at the same time. 

I like your thoughts of having a seed rotating once per hour because it will work nice when having pagination. However I wonder if it will no longer be perceived as "random", and look like it is a custom order that changes periodically.

**Comment by ggppdk** [comment]
well, it will be an enhancement for future work on the random order case ))
