### ISSUE TITLE
Phone Numbers field: add <a href="tel:"> tag

### ISSUE THREAD

**Issue by Lyquix** [FLEXIcontent/flexicontent-cck#352]
Hello guys, we would like to add an option for wrapping the phone numbers in a <a href="tel:"> tag.
If you agree with that we can make the changes and send a pull request.

**Comment by ggppdk** [comment]
Sure this would be useful, but maybe it should be turned on via a parameter in field's configuration

**Comment by Lyquix** [comment]
Correct, that's what we had in mind. I will create another pull request for this.

**Comment by Lyquix** [comment]
I sent a pull request

**Comment by micker** [comment]
great adding thanks !

**Comment by ggppdk** [comment]
Merged
