### ISSUE TITLE
Updated AceSEF plugin for FLEXIcontent, also fix pagination

### ISSUE THREAD

**Issue by Lyquix** [FLEXIcontent/flexicontent-cck#353]
The AceSEF extension for FLEXIcontent is super outdated and for FC 3.x doesn't work. Do you know who developed this extension in the first place? Was it JoomlaAce? Do you have any contact with them?

**Comment by ggppdk** [comment]
I think it was written by ACESEF authors,
- to update the plugin we would need to study the current joomla article

also FLEXIcontent 3, has an updated category view to render all type of listing except search (which need to be SEF only in regards to menu item)

- single-category &view=category&cid=nnn
- multi-category &view=category&layout=mcats&cids=nnn,nnn
- my-items &view=category&layout=myitems  [&cid=nnn]
- tags &view=category&layout=tags&tid=nnn    (*replace old view=tag)
- favourites &view=category&layout=favs [cids=nnn]   (*replace old view=favourites)

**Comment by Lyquix** [comment]
Thank you. I have sent them a support request. 

Should we take an active role in these kinds of integrations? I have been suffering with this one until I realized the 2.x and 3.x differences was the cause.

**Comment by ggppdk** [comment]
Well i think we can update this ourselves, 

where is the doc for writting an ACESEF plugin ?
http://www.joomace.net/support/docs/acesef

**Comment by Lyquix** [comment]
I will ask them for documentation

**Comment by ggppdk** [comment]
Currently looking at it, need to also test / update pagination in the SH404SEF plugin

**Comment by ggppdk** [comment]
Just for ACESEF, fix is not possible without changing ACESEF router code

**Comment by Lyquix** [comment]
I have not received any answer from JoomAce, even though we have bought support service. A lot of other people are complaining about this issue. I think it is time to move on, we will replace AceSEF with some other solution. We are considering sh404sef. What do you think?

**Comment by sitefaitbienfait** [comment]
Hi,

I don't have any pagination problem with Joomla 3.4.8, FC 3.0.10 and SH404 4.7.2.3180

**Comment by ggppdk** [comment]
I installed same version 4.7.2.3180 too
- category pagination is working,

About Table of Content in item view, i will test

**Comment by Lyquix** [comment]
SH404 works well. The problem was with AceSEF. It looks like AceSEF is no longer maintained.

**Comment by ggppdk** [comment]
There is an issue with Table of Content with single content items that are multi-paged
Fixed it here:
https://github.com/FLEXIcontent/flexicontent-cck/issues/435
With commit: 8ead4a3

About ACESEF plugin i have updated the plugin, pagination is still broken, the author needs to fix this
- will not do more work for ACESEF. Maybe in the future

Closing this
