### ISSUE TITLE
Enhancements for relation and relation_reverse fields

### ISSUE THREAD

**Issue by Lyquix** [FLEXIcontent/flexicontent-cck#357]
Hello guys, we are looking to develop the following enhancements for the relation and relation_reverse fields. 

Please let me know if you agree with them. If yes, we can add the necessary fields in the xml files and the corresponding php code. We will take care to make the new default fields match the current behavior, so that there are no changes after upgrade.

### relation ###

Viewing Item List

* Item count (set a maximum number of items to display)

### relation_reverse ###

Reversing

* Scope (example: products and services connect to projects with the same relation field, I can create two relation reverse field for connecting back from projects to products and services separately)
  * By Category
  * By Type
  * Published items only
  * Use publish up/down dates
  * Same language only
  * Item owned by

Viewing Item List

* Item count (set a maximum number of items to display)

**Comment by micker** [comment]
It will be good can you enchanced sélect système ?
Like  multiselect script to use autosuggestion  In title 
Le 11 nov. 2015 7:09 PM, Lyquix <notifications@github.com> a écrit :Hello guys, we are looking to develop the following enhancements for the relation and relation_reverse fields. 

Please let me know if you agree with them. If yes, we can add the necessary fields in the xml files and the corresponding php code. We will take care to make the new default fields match the current behavior, so that there are no changes after upgrade.

relation

Viewing Item List

Item count (set a maximum number of items to display)

relation_reverse

Reversing

Scope (example: products and services connect to projects with the same relation field, I can create two relation reverse field for connecting back from projects to products and services separately)

By CategoryBy TypePublished items onlyUse publish up/down datesSame language onlyItem owned by


Viewing Item List

Item count (set a maximum number of items to display)

**Comment by Lyquix** [comment]
Micker, yes we will work on this

Can you explain your comment about the item form?

**Comment by micker** [comment]
hi that i think for now relation field take too much place in item form
not realy powerfull when we have too many item
maybe we can use multiselect script to tip wanted item (with auto suggestion)
add slider panel for filtering or other idea
Goal : less space easier to use
you understand ?

**Comment by Lyquix** [comment]
Yes, I understand your comments now. We use relation fields a lot, here are my thoughts:

* I agree, the field can be too big, specially when you are not working with it. Maybe we can collapse the field when not in use, similar to the way we collapse the image field thumbnails list when not in use. 
* Also, when you are not working with it the visible information should focus on the selected items: if I am reviewing an item, I can to see what is related, not the whole list of available items
* When you are working with it, it is useful for it to be big, specially if you are working with a long list of items
* I think we need to improve the way we display the lists of available and selected items. We have had situations where we need additional info from an item is needed. In some cases the titles can be identical, so having additional info like author, date, etc. can be useful.
* The current filtering functionality is very useful, but if we add other info like author, it should filter by that too
* Custom sorting: in some cases we have been in situations where we needed the related items to be sorted in a custom order - not the category custom order. It would be great to have the ability to select and order in the field.

Let me know what you think. We may not be able to develop all of these enhancements now, but maybe some.

**Comment by micker** [comment]
Great idea
Le 12 nov. 2015 3:28 PM, Lyquix <notifications@github.com> a écrit :Yes, I understand your comments now. We use relation fields a lot, here are my thoughts:

I agree, the field can be too big, specially when you are not working with it. Maybe we can collapse the field when not in use, similar to the way we collapse the image field thumbnails list when not in use. Also, when you are not working with it the visible information should focus on the selected items: if I am reviewing an item, I can to see what is related, not the whole list of available itemsWhen you are working with it, it is useful for it to be big, specially if you are working with a long list of itemsI think we need to improve the way we display the lists of available and selected items. We have had situations where we need additional info from an item is needed. In some cases the titles can be identical, so having additional info like author, date, etc. can be useful.The current filtering functionality is very useful, but if we add other info like author, it should filter by that tooCustom sorting: in some cases we have been in situations where we needed the related items to be sorted in a custom order - not the category custom order. It would be great to have the ability to select and order in the field.

Let me know what you think. We may not be able to develop all of these enhancements now, but maybe some.

**Comment by micker** [comment]
about place maybe we can use multiselect script like categories select
=> display only on text field, tip item wanted => use enter to validate
we can reduce space and allow select item more simply

**Comment by ggppdk** [comment]
Please note that the relation field needs to be made AJAX, 
- to avoid preloading load lists in very large web-sites (25,000+ items)
and the UI needs to be improved

we have this issue open:
https://github.com/FLEXIcontent/flexicontent-cck/issues/309

@Lyquix 
also have you used/tried the "automatic relations" field, i believe i have given it to you ?

**Comment by Lyquix** [comment]
Please review the following commit:

https://github.com/FLEXIcontent/flexicontent-cck/commit/9ec2a9e450878abafc6f96804f5dfdea915d9015

I have implemented the following:

Relation field: item count limit

Relation reverse field: scope parameters (by category, type, published dates, owner), and item count

Please note that we had to enhance a function in flexicontent.fields.php.

I did not do any enhancements to the UI for item form yet.

**Comment by ggppdk** [comment]
Also recent commit: bc4f261
- Fixed using relation field as a filter (display and item matching), also item counting for it is now correct

**Comment by ggppdk** [comment]
@Lyquix 
I ll test your change, maybe these should better be in v3.0.10

**Comment by Lyquix** [comment]
@ggppdk I notice that the changes in commit https://github.com/FLEXIcontent/flexicontent-cck/commit/9ec2a9e450878abafc6f96804f5dfdea915d9015 have not yet been included in the releases. Is there a problem? Is there anything I can do to help?

**Comment by ggppdk** [comment]
Hi the commit is on the --master-- branch,
- new releases now come from the --v3.0.x-stable-- branch, which is our branch for official releases till v3.1 is done

i have not tested commit 9ec2a9e, it looks safe, maybe we can commit to v3.0.x-stable branch ?

- so far only included specific commits with fixes into --v3.0.x-stable-- branch, using:

git checkout 3.0.x-stable
git cherry-pick nnnnnn
git push

**Comment by ggppdk** [comment]
i have re-opened this issue and added v3.0.14 milestone,

**Comment by ggppdk** [comment]
Merged into v3.0.x-stable branch with: 4e6e044
