### ISSUE TITLE
Custom field ordering cases for frontend ordering selector, not possible to add both ascending and descending for same field

### ISSUE THREAD

**Issue by tevez15** [FLEXIcontent/flexicontent-cck#362]
Hi, 

I have a suggestion for you, on config of component we can use fields to filter, ASC or DESC, but the field, just can be used 1 time, something like:

40:int:asc, 40:int:desc

FC just use the last one.

Can you change this, to use both?

**Comment by ggppdk** [comment]
Fixed with 2611ecf

Fixed custom field not possible to be used more than once in the frontend ordering selector, e.g. as both ascending order and descending order
