### ISSUE TITLE
Limit number of images on backend items manager, change default display method to: display_single_total

### ISSUE THREAD

**Issue by tevez15** [FLEXIcontent/flexicontent-cck#363]
HI,

It's possible create a limit for image field, when we add to BO list?

Now, he show me all images of that field, in most of the cases, I have 20 images. 
![capture](https://cloud.githubusercontent.com/assets/6087425/11241581/d1c67426-8df3-11e5-8faf-afaf05a7dd16.PNG)

**Comment by ggppdk** [comment]
We can select to show 1 image with an image counter, and then popup it will JS image gallery in popup

maybe you can do via CSS add no wrap to the container and overflow hidden
or set a height to the container and again overflow hidden

**Comment by tevez15** [comment]
Yes, but the image counter is used to limit in front end to, I just want limit in BO.

I used what o suggest, in css, I hidden the all images except the first one.

**Comment by ggppdk** [comment]
Do you mean display of field in items manager ?
instead of only the field name use:
```
imgFieldname:display_single_total
```
display_single_total will show the 1st image together with a total

**Comment by ggppdk** [comment]
But this makes sense, default behaviour of image field
- if backend items manager is the current view is detected

should be to for using display method:
display_single_total
