### ISSUE TITLE
Can't remove file from file field

### ISSUE THREAD

**Issue by mshou** [FLEXIcontent/flexicontent-cck#367]
Hello,

I'm using FLEXIcontent 3.0.9-rc4.
Can't remove file from file field, and "My files" page don't pop up,only with "allow multiple values"  enable.
 
![image](https://cloud.githubusercontent.com/assets/15908034/11243840/4800b904-8e02-11e5-896e-8b536ecd975d.png)

**Comment by ggppdk** [comment]
Hello
yes i confirmed both
when multiple is disabled
- not possible to remove value
- the JS for opening "My Files" in popup is not added
the 2nd should be very easy to fix, 
the 1st we have done similar work in image field

will fix both, milestone 3.0.9

**Comment by ggppdk** [comment]
Fixed with fe08dec

please test with current Github version (on testing / development website)
(click the zip, and then install via joomla extension installer)

**Comment by mshou** [comment]
Tested, problem fixed. 

Thanks.

**Comment by ggppdk** [comment]
See also maybe these should have milestone 3.0.9
#369 
#349
