### ISSUE TITLE
Image Field - required not working properly

### ISSUE THREAD

**Issue by ldoliv** [FLEXIcontent/flexicontent-cck#385]
Hello,

I'm using FLEXIcontent 3.0.9-rc6c, Joomla 3.4.5.
My image field is requred, I select and existing image from the list, but required error still appears when I try to save the article.

![image](https://cloud.githubusercontent.com/assets/6535818/11405515/289cc6c2-93a0-11e5-9ca1-38cec206f8ec.png)

**Comment by ggppdk** [comment]
Fixed with 0b34b9f
