### ISSUE TITLE
[Field needs to be marked as filterable, TODO: add info message above the parameter] Parameter "locked filters" not working

### ISSUE THREAD

**Issue by ldoliv** [FLEXIcontent/flexicontent-cck#387]
Hello,

I'm using the latest version of flexicontent and joomla.

I'm trying to restrict the category view by type, but all types show. I think this is a bug.

In category -> Alpha-Index, Search, Filters -> enable Use locked filters
Locked Filter values: 8##9

I also tried in the menu item overriding the parameter but result is the same. Does not work.

Please check this.

**Comment by ggppdk** [comment]
The field must be marked as a filter in field manager, otherwise it will not work

**Comment by ldoliv** [comment]
Sorry, is working. I forgot to enable filter

**Comment by ldoliv** [comment]
Yes thank you :)

**Comment by ldoliv** [comment]
you can close.

**Comment by ldoliv** [comment]
I enabled the filter option in the field and is now working. Thank you

**Comment by ggppdk** [comment]
There was a thought to display a warning, but in some cases you may want to disable the filter FLAG and do not have the warning either.

so adding a warning is not desirable in all cases, thus it was not added.

- the bad is that several users ask the same question as you,

I have reopened this issue, to make this improvement
- Add an small alert-warning box above the locked filters values to say:

"If field is not marked as filterable in fields manager then it will be ignored"

**Comment by ldoliv** [comment]
Yes, I think it's a good idea, specially if many forget or don't know about this.

**Comment by ggppdk** [comment]
Almost no-one is aware of this until it happens, and then everybody thinks it is a bug,
- a short inline (1-line) message will avoid confusion and lost time

**Comment by ggppdk** [comment]
Adde a warning icon next to the parameter with: 496b062
