### ISSUE TITLE
Textfields disappeared FLEXIcontent version 3.0.9-rc7 on update?

### ISSUE THREAD

**Issue by iamrobert** [FLEXIcontent/flexicontent-cck#392]
My text fields have disappeared with the latest update.

Warning
JFolder: :files: Path is not a folder. Path: C:\z2015\UniServerZ\www\ky\plugins\flexicontent_fields\text\tmpl\

Screen shot
![image](https://cloud.githubusercontent.com/assets/8617673/11475383/27715878-97b8-11e5-84c5-775b8ae01b2c.png)

**Comment by iamrobert** [comment]
hmm - the files when you upload the zip the tmpl files didn't copy accross.

**Comment by sitefaitbienfait** [comment]
Hi,

Yes, same with the flexicontent_fields core plugin. 
The tmpl folder + files are missing. I had some warnings on front-end : include[...]/plugins/flexicontent_fields/core/tmpl/categories/field.php): failed to open stream: No such file or directory in [...]/plugins/flexicontent_fields/core/core.php on line 255
After uploading the tmpl folder, it seems Ok too

**Comment by ggppdk** [comment]
You are right !

The /tmpl/ folder for categories/tags (core) and for text field were not added to the installation XML files
core.xml
text.xml

**Comment by ggppdk** [comment]
Added to XML files with: 6eb4491

**Comment by ggppdk** [comment]
Thanks for reporting
