### ISSUE TITLE
CSV Import failed with mysql error

### ISSUE THREAD

**Issue by sitefaitbienfait** [FLEXIcontent/flexicontent-cck#398]
Hi,
I use FC 3.0.9-rc7 (2015-11-30) with Joomla 3.4.5
I'm trying to import some contents but i get an error on the chrome console : 

GET : http://url/administrator/index.php?option=com_flexicont…rt.importcsv&items_per_call=5&itemcnt=0&6bf58ab0f744e7ad57e8e85d28cea9f4=1 500 (You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1 SQL=SELECT i.id AS value_id, i.title AS value FROM bmg3o_content AS i WHERE i.id IN ())

Is someone else having this issue?

Regards

**Comment by sitefaitbienfait** [comment]
And i have the same message : 
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1 SQL=SELECT i.id AS value_id, i.title AS value FROM bmg3o_content AS i WHERE i.id IN ()
when i edit an item, and change the item state from Published to Trash (in the backend item form)

**Comment by sitefaitbienfait** [comment]
I was unable to create new content with the same error : 
1064 :You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1 SQL=SELECT i.id AS value_id, i.title AS value FROM bmg3o_content AS i WHERE i.id IN ()
Downgrading to 3.0.9-rc6 fixes the problem

**Comment by ggppdk** [comment]
Fixed with: 7a35272

SQL error was occuring in the relation field 's basic and advanced search indexing (2 functions inside the field)
- the code does not check if field has a value during item saving

in v3.0.9-rc7, the field was fixed so that 
- its filtering, 
- text search, 
- and item counting for the filtering values
work properly, and these recent changes introduced the new bug

**Comment by sitefaitbienfait** [comment]
Nice !
Thanks a lot Georgios
