### ISSUE TITLE
Flexicontent doesn't have a Page Display tab in the menu items

### ISSUE THREAD

**Issue by lungkao** [FLEXIcontent/flexicontent-cck#400]
Flexicontent Don't  have Page Display tap

i want use  Page Class in menu 
![screen shot 2558-12-08 at 8 17 21 pm](https://cloud.githubusercontent.com/assets/2047778/11656609/f1a095d8-9de8-11e5-979f-6ea9506d3b39.png)

**Comment by ggppdk** [comment]
Which type of menu item ?

**Comment by ggppdk** [comment]
Closing as invalid
