### ISSUE TITLE
File field: title label still shows even if file properties editing is disabled

### ISSUE THREAD

**Issue by Lyquix** [FLEXIcontent/flexicontent-cck#405]
The title label still shows:

![](http://i.imgur.com/ykLWozU.png)

even when the file properties editing is disabled:

![](http://i.imgur.com/aRD3iSv.png)

**Comment by ggppdk** [comment]
Actually it is displayed deliberately when file title is disabled
it displays this:
```
($file_data->altname && $filename_original!=$file_data->altname ? $file_data->altname : '-')
```

**Comment by Lyquix** [comment]
From the user perspective, it seems like an error. The user uploads a file and the title tag remains with just the - in it.

**Comment by rubenreyes2000** [comment]
This issue can be closed
