### ISSUE TITLE
Image field: how are thumbnails secured ?

### ISSUE THREAD

**Issue by Lyquix** [FLEXIcontent/flexicontent-cck#406]
The image field configuration allows settings to control access to the ORIGINAL image file, stored in /components/com_flexicontent/uploads

However, the thumbnails that are created, are always stored in /images/stories/flexicontent, and are accessible to anyone.

Shouldn't we protect thumbnails as well? Should it be by default if you select DB-mode or enable the setting to prevent direct access to image source? Or maybe a separate access setting for thumbnails?

**Comment by ggppdk** [comment]
- the idea is to protect original files
limiting their access makes them unable to server their purpose,
which is to be directly accessible via URLs

to protect the thubmnails one can use watermark

**Comment by ggppdk** [comment]
About image field, 

the setting to disallow access to original images folder with .htaccess password
- it is only when image field is in Folder mode "ItemID+FieldID" folders

When in DB-mode the original images are in /components/com_flexicontent/uploads/ and are always protected with .htaccess password from direct access

**Comment by Lyquix** [comment]
If we have categories/items that are only available to registered users, having unsecured thumbnail images would allow for non-registered users to access those images.

I think we should have an option to store thumbnails in a protected folder, and have a Joomla URL to access them (for example: `index.php?option=com_flexicontent&view=thumb&id=12345`). In that way we can control access to them.

**Comment by rubenreyes2000** [comment]
This issue can be closed
