### ISSUE TITLE
Missing translation string

### ISSUE THREAD

**Issue by irbian** [FLEXIcontent/flexicontent-cck#427]
https://github.com/FLEXIcontent/flexicontent-cck/blob/5313e62014ecfdf637005ec8f1d31029584204fd/plugins/flexicontent_fields/image/image.php#L2341

**Comment by ggppdk** [comment]
Since this is shown in item form
- and not in configuration (which are lower priority and in rare cases language strings are missing until we are satisified with the original texts)

fixed with: 4eaf5b7
