### ISSUE TITLE
Small page builder for template editor

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#429]
it will be great to add small page builder in template editor :
- using column option in row with responsive grid
- rezize width by drag and drop
- some css option like : background, border, font-size, box-shadow, padding, margin

**Comment by Jabe64** [comment]
I really like the idea but I imagine it as a major feature for some later version (3.4?).

Some real WYSIWYG Template Editor would be amazing but will also take a lot of time to develop.

Something like Gantry:
https://www.youtube.com/watch?v=H0RCz-ziJoo

Or other inspiration resources:
http://css3please.com
http://codecanyon.net/item/live-theme-editor/12750918 (For OpenCart)
http://www.cssauthor.com/bootstrap-editors/ (Bootstrap Editors)

There was some JavaScript library for getting and setting CSS stylesheet rules (but it doesn't seem to be updated anymore and doesn't seem to support LESS):
https://github.com/Box9/jss

For me there are more important implementation to do earlier like calculation field (planned for 3.3) to enhance rankings.

**Comment by micker** [comment]
less support was added in 3.0.10 => we can add more option for customize easier color template
i think we need to add more option with cascading rule
and enchance position manipulation

**Comment by ggppdk** [comment]
Will make a new FAQ / tutorial out of this answer

Regarding LESS v3.0.10 adds it,  please see pics

- the less files used are inside the ./less/ subfolder:
less/**item**.less
less/**category**.less
less/include/**config**.less
less/include/**auto_item_config**.less
less/include/**auto_category_config**.less

- recompile as needed of **item.less, category.less** to **item.css, category.css** if you change any less file inside the subfolder /less/ this is done by checking file modification times

About **editing** LESS files
1. the less/config.less is editable
2. the auto_* ... are created automaticall by XML parameters that are
<field ... **cssprep="less"**
- thus you can easily add parameter for styling in your item.xml and category.xml that are converted to a less CSS variable that you can use inside your item.less and category.less
- **the parameters** with **cssprep=less** appear with a "less" marker in their label (see picture)
- the less variables are like (see picture):
(auto_item_config.less)  @FCI_parameter-name
(auto_category_config.less) @FCC_parameter-name 

![less_support2](https://cloud.githubusercontent.com/assets/5092940/12249642/aba31dc0-b8c9-11e5-9a43-d28c6248d63e.png)

![less_support3](https://cloud.githubusercontent.com/assets/5092940/12249944/d3926190-b8cb-11e5-83ca-408ad524ecb4.png)

![less_support](https://cloud.githubusercontent.com/assets/5092940/12249643/aba5aec8-b8c9-11e5-9f7c-97004b0baeca.png)
