### ISSUE TITLE
Question: Does Apply work in 3.0.10-RC2d?

### ISSUE THREAD

**Issue by iamrobert** [FLEXIcontent/flexicontent-cck#431]
When I click apply in 3.0.10-RC2d - it closes the article rather than remaining on the page?

Has something changed?

**Comment by ggppdk** [comment]
Saving works but redirection is wrong, and it is in other forms too

**Comment by iamrobert** [comment]
Also batch fails..

**Comment by ggppdk** [comment]
Backend controller 'task' calculation is partly broken, fixing it

**Comment by ggppdk** [comment]
Fixed in v3.0.10-RC2e,

thanks for report, the new code was setting task in JInput but some views / code still use JRequest, we need to set into both for now
