### ISSUE TITLE
FLEXIbreak and SH404SEF: TOC only links to 1st page

### ISSUE THREAD

**Issue by bropa** [FLEXIcontent/flexicontent-cck#435]
With FLEXIbreak plugin „Display method: Active page :: Paginate via Reload“ all pages of TOC are linked to 1st page. Also the parameter "showall=" (without value) is adding to url.
Sh404SEF does save all limitstart variants as duplicate url and set url which contains "limitstart=1" as default.

FLEXIcontent 3.0.10-RC2e 
sh404SEF 4.7.2.3180 (latest)

![screen](https://cloud.githubusercontent.com/assets/15979516/12332696/43c5c6ca-baf0-11e5-89e2-71d2bee8bffb.jpg)

**Comment by ggppdk** [comment]
Fixed with: 8ead4a3
