### ISSUE TITLE
Improving FLEXIcontent administrator backend Theme/CSS in J3x

### ISSUE THREAD

**Issue by iamrobert** [FLEXIcontent/flexicontent-cck#44]
I have been working on a new administrator template for J3x + FLEXIcontent for my clients. Its currently a WIP and is semi-responsive. I would love some help!

1. Download it from github:
https://github.com/iamrobert/flexi

2. Install it using the extension manager: http://docs.joomla.org/J3.x:Installing_a_template

**Comment by ggppdk** [comment]
Backend CSS layout were revised in v3, closing this
