### ISSUE TITLE
"Search-engine robots" set in type is ignored

### ISSUE THREAD

**Issue by ldoliv** [FLEXIcontent/flexicontent-cck#445]
Hello,

I'm using flexicontent FLEXIcontent 3.0.10-RC2e, I set robots to "no index, no follow" in the article type, but it is ignored.
In the article I have "Search-engine robots" set to "Use global".

Works if I set in article, but not in type.

Please check if this is a bug, thank you.

**Comment by ggppdk** [comment]
Fixed here: ae9ca51 together with limit parameter in categories being ignored in favour of component setting.

you may click "download zip", install via Joomla installer and confirm fix
