### ISSUE TITLE
Relation/Relation Reverse field: custom field ordering not working

### ISSUE THREAD

**Issue by Lyquix** [FLEXIcontent/flexicontent-cck#456]
Hello guys, I have found a bug in the Relation and Relation Reverse fields - we are trying to sort a list of related items by the value of a text field, but it is not working. We found that only the ordering by core fields works, and selecting any of the non-core fields has no effect.

I also noticed that the parameters are not the same as in the Category view. In the fields we don't have a parameter for *Enable overrides CORE order*

Fields settings:
![](http://i.imgur.com/B8HxY9e.png)

![](http://i.imgur.com/0TP5sXj.png)

Category settings:
![](http://i.imgur.com/fXAtjco.png)

**Comment by ggppdk** [comment]
Added missing parameter to enable custom field ordering (needed by FLEXIcontent v3.0.0+) and fixed item list generating code to use it

**Comment by Lyquix** [comment]
Thank you! We will test it
