### ISSUE TITLE
Add a warning to change LESS template files instead of CSS files

### ISSUE THREAD

**Issue by bropa** [FLEXIcontent/flexicontent-cck#457]
If i save template of Columned listing the css file is resetted to default file, all changes are deleted.
This issue is since some newer versions of flexicontent.

FLEXIcontent 3.0.13 
Joomla! 3.4.8

**Comment by ggppdk** [comment]
Yes, it is normal
- the item.css and category.css files are created by *.less files automatically

instead edit the files: *.less
- you can add CSS rules into them, and of course LESS directives too

**Comment by bropa** [comment]
Hm, ok, i see!! But then its irritating that i could "save" category.css although this is not saved permanent. A disabled/removed save button would be helpful, i think (:

**Comment by ggppdk** [comment]
Right we need to disable editting of CSS file when the LESS file is present too 

or even better when someone clicks to edit the CSS file, display a message and load the LESS file instead, 3.0.14+ milestone

**Comment by ggppdk** [comment]
@bropa
please note that to report unconfirmed bugs, you should post:
http://www.flexicontent.org/forum/index.html

in your case you did report 2 User interface issues,
- that indeed need to be addressed as they cause confusion

but neither of them is a bug

**Comment by ggppdk** [comment]
Added warning with 781b195
