### ISSUE TITLE
Limit on number of fields allowed in template positions?

### ISSUE THREAD

**Issue by Lyquix** [FLEXIcontent/flexicontent-cck#460]
Hello guys, today we noticed that when adding a lot of fields in a template position, many fields are not saved. Only 14 fields are saved in the position, the others are dropped.

This is happening on 3.0.13

**Comment by ggppdk** [comment]
In DB table:
PPP_flexicontent_templates

the "fields" column should be of type text, is it ?

**Comment by Lyquix** [comment]
No, it is not, it is VARCHAR(100).

This is part of a 1.5 -> 3.5 we are doing, maybe we messed up something in the process.

Thank you!

**Comment by Lyquix** [comment]
Hmm... it is VARCHAR-255, this is part of a 1.5 > 3.5 upgrade, I guess we messed something in the process. Thank you! :+1:
