### ISSUE TITLE
Category view items retrieval: add types scope

### ISSUE THREAD

**Issue by Lyquix** [FLEXIcontent/flexicontent-cck#461]
Just wanted to get your thoughts on adding types scope to Category parameters (and/or Category view menu item). 

We have had situations where we need to hide certain content types from the category view, without moving them to a separate category (in order to keep the same URL parents). So far we have been able to just filter them using logic in the template, but it can create issues with the number of items actually displayed when we have pagination.

Let me know your thoughts. If you agree with this enhancement, I can work on it.

**Comment by ggppdk** [comment]
What about using parameter:
- locked filters values
in category setting or menu
![locked_filter_values](https://cloud.githubusercontent.com/assets/5092940/13026552/4c74ed0e-d234-11e5-9308-051e4806e09f.png)

**Comment by micker** [comment]
=> block categorie to type scope will be interesting if we can block front-end submitting too
very easy to create a categorie linked to type with front-end submission loked too (categorie, type, template) without too much configuration (for now we need to create a link submit with specific rules and link to categorie option)
ex : categorie add an option to exclusive type => we can only submit and view type selected and for front and backend. Many type we doesn't need multi type in same category (categorie film linked to type film)

**Comment by Lyquix** [comment]
@ggppdk - Thank you I will test Locked Filters

@micker - I wasn't thinking about blocking categories to only some content types, but that would be useful too, both in frontend and backend

**Comment by ggppdk** [comment]
Besides locked filters, 
you can use specific categories for every type

- in type configuration you can select a specific category sub-tree to be used for the type
item submission will only be allowed to the happen inside the selected sub-tree
