### ISSUE TITLE
Date/Time field enhancements

### ISSUE THREAD

**Issue by Lyquix** [FLEXIcontent/flexicontent-cck#464]
Would you be in favor of enhancing the UI of the date/time field to something like:

https://eonasdan.github.io/bootstrap-datetimepicker/

Would it make sense to allow time-only option for this field? Or should it be a separate time-only field type?

**Comment by Lyquix** [comment]
I can work on enhancements if you agree

**Comment by micker** [comment]
Yes its realy great rsevents use it and its realy good

On jeu., févr. 18, 2016 at 5:07 PM, Lyquix < notifications@github.com [notifications@github.com] > wrote:
Would you be in favor of enhancing the UI of the date/time field to something
like:

https://eonasdan.github.io/bootstrap-datetimepicker/
[https://eonasdan.github.io/bootstrap-datetimepicker/]

Would it make sense to allow time-only option for this field? Or should it be a
separate time-only field type?

**Comment by Lyquix** [comment]
Here is another option. I don't know if this is too unconventional, but I like it :)

http://felicegattuso.com/projects/datedropper/

**Comment by ggppdk** [comment]
I ll add layout support to date field,
- it will be more clean to implement this, using layouts:

tmpl/field_default.php

- then you can add:

tmpl/field_datepicker.php
tmpl/field_datedropper.php

and add 2 options in the "form_layout" parameter in the XML file

i will add this by Saturday, if i don't remind me on Monday

**Comment by Lyquix** [comment]
That's a great idea!

**Comment by micker** [comment]
When i use rsevents i am crying because search is too strange display is too limited but i need this because we have Récurrence and subscription...

**Comment by Lyquix** [comment]
We will be working on adding a layout for better date/time pickers

**Comment by micker** [comment]
Great

On Thu, Apr 28, 2016 at 4:39 PM, Lyquix < notifications@github.com [notifications@github.com] > wrote:
We will be working on adding a layout for better date/time pickers

**Comment by Lyquix** [comment]
We realized that it is better if we develop a Joomla plugin that can update the date picker for the whole site, not just the FC field. We are almost done with it and will share it with you.

Also, we realized that we don't have an FC field for Time only (the `date` field allows for date and date-time values only). We started developing a `datetime` field that will allow for date, date-time and time values. When we are done I will share with you. 

I wasn't sure it was a good idea to modify the date field because the search and filtering functions may be affected if we store values that are only time. Or do you think it is okay to modify the `date` field to allow for time-only values and store them as `0000-00-00 hh:mm:ss`?

**Comment by micker** [comment]
it will be very good thanks for sharing
if we want to kick calendar component, i think we realy need a more powerfull date field :
- start en ending for period
- recurrence mode

**Comment by Lyquix** [comment]
Guys: here is the first part of our enhancements: a new date-time picker for Joomla:

https://github.com/Lyquix/plg_system_datetimepicker

I am finishing the new FLEXIcontent datetime field, I will end it to you next week.

**Comment by rubenreyes2000** [comment]
I think time-only fields are now better handled with a Text field and the validation rule set to a time format.

I think you can close this issue.

**Comment by micker** [comment]
ok cool
