### ISSUE TITLE
Feature request: Multiple values for International Address field

### ISSUE THREAD

**Issue by jimiero** [FLEXIcontent/flexicontent-cck#469]
Would be nice that in the field, you can provide multiple values.

For example you may have that listing in USA -> New York, but also in Greece -> Athens

Currently seams you're restricted to enter only 1 address

**Comment by ggppdk** [comment]
It is in the to-do, the field code is mostly updated to support this

**Comment by jimiero** [comment]
Cool, that would rock, let me know if you need help with testing

**Comment by jimiero** [comment]
@ggppdk any ETA when you think this may be available ?

**Comment by jimiero** [comment]
@ggppdk would love if you can offer some status here do you think it can come with this also ? https://github.com/FLEXIcontent/flexicontent-cck/issues/601

Rgds

**Comment by ggppdk** [comment]
Finished work on it, field now supports 
- multiple values per field
- multple fields in same form
