### ISSUE TITLE
Address field interactive direction

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#474]
i found an tutorial about interactive direction
the idea :
- option for direction, none | in google map (actual option) | in same view
  http://dreamdealer.nl/tutorials/getting_directions_with_google_maps.html
  what did you think @ggppdk @Lyquix ?

**Comment by Lyquix** [comment]
This is interesting. We have not needed something like this. Generating a link to Google Maps with the directions view already loaded has not been a problem.

For example in this case: http://dev.riconnect.info/access/offices
If you search an address (for example Philadelphia), the list below is sorted by closest, and the "Get Directions" links are updated to use the searched address as the starting point.

**Comment by micker** [comment]
The link is intresting but the problem is for end user experience,  we propose to go outside site
With direction inside same page user arent go out
