### ISSUE TITLE
Flexicontent search field is not responsive for Apple devices

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#475]
we have a small difference between android display and apple system
iphone display
![3lv2cjp](https://cloud.githubusercontent.com/assets/2539440/13406125/265f49ac-df22-11e5-847a-e1c2ab7fd5e4.png)
android display
![snip_20160229201804](https://cloud.githubusercontent.com/assets/2539440/13406134/2ce0477c-df22-11e5-8997-e0dee0bdc057.png)
Strange not ?

**Comment by ggppdk** [comment]
Maybe this is related to the specific template / specific site

e.g does it happen if you use Joomla protostar template or other template ?

**Comment by micker** [comment]
sorry not i tested with protostar same way
![snip_20160301044654](https://cloud.githubusercontent.com/assets/2539440/13417102/e175fb1e-df68-11e5-9514-16738cdd294d.png)

**Comment by ggppdk** [comment]
I have looked at it
it is CSS issue, we force a minimum width of 180px for the text search input

and in your example the container and screen are too small,
will update CSS

**Comment by micker** [comment]
ok thanks !

**Comment by ggppdk** [comment]
Fixed with 7e72da4 and also made some small updates to module layout
