### ISSUE TITLE
Implementing Microdata intergration

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#48]
could we plan a micro data integration
ex in global config : microdata tabs
itemprop name =>dropdownlist with flexicontent field
itemprop dateCreated =>dropdownlist with flexicontent field date type
itemprop url => SEF ou native
itemprop text => select texte area field
itemprop creator => user or custom field
itemref => title or custom field
itemprop; location =>dropdownlist with flexicontent field
itemprop affiliation =>dropdownlist with flexicontent field
itemprop colleague =>dropdownlist with flexicontent field
etc ...

**Comment by micker** [comment]
an idea for micro data
1 adding  <article itemscope itemtype="http://schema.org/<?php $Typemicrodata; ?>"></article> in template
2 in type adding option to select type (corporation, article recipe ...) via dropdown
3 for each field an dropdown to choose type of micro data  via dropdown
4 in each render field add <span itemprop="<?php $Propmicrodata; ?>">
what do think about this basic implementation
If you are agree i can do it

**Comment by micker** [comment]
Maybe we can add 'itemscope itemtype=...' in fieldgroup too
it will perfect

**Comment by ggppdk** [comment]
We are modifying template code to add microdata 

- is it better instead of modifying template,
to modify the fields and add a wrapping <div itemprop="...">value</div> container to add the microdata

- or different/extra to indicate if template or the field should add the microdata properties ?

**Comment by ggppdk** [comment]
Implemented in v3.0.8, closing this,

we will open another issue for 
- an enhancement list to existing solution

**Comment by iamrobert** [comment]
This is great. Would it be possible to add color from: https://schema.org/Product?
https://github.com/FLEXIcontent/flexicontent-cck/pull/298
