### ISSUE TITLE
Unpublishing via Joomla Featured articles listing, asks for temporary data to be updated

### ISSUE THREAD

**Issue by ldoliv** [FLEXIcontent/flexicontent-cck#487]
Hello, I have version 13.

In the backoffice, when **unpublishing featured articles** through the menu -> content -> featured articles.
**Articles still show** in the Flexicontent universal content module, I don't think it's only for the module that this happens, maybe also in flexicontent component category view filtering by featured.

It works fine if I unpublish articles through the flexicontent menu -> Components -> Flexicontent -> Items or Content -> articles.

If the problem is on joomla side, please add a filter by featured to the flexicontent list view in backoffice, so that we can filter by featured articles.

I noticed that if I logout and login again, I have this every time I update it through the featured articles menu.
![image](https://cloud.githubusercontent.com/assets/6535818/13873969/d06a962c-ecec-11e5-87ba-59ab8cc22aae.png)
and once I update this then It already works like it should.

Please check, thank you!

**Comment by ggppdk** [comment]
I think we will either need to disallow (redirect) the backend "Featured Articles" listing or maybe detect the changing task in our system and update the needed data
