### ISSUE TITLE
Google autocomplete search of address international field is only searching 1 type

### ISSUE THREAD

**Issue by ggppdk** [FLEXIcontent/flexicontent-cck#492]
Currently the **Autocomplete Google-Maps Search** only searches 1 type:
- Address  [geocode]

thus e.g. business places are not found

https://developers.google.com/maps/documentation/javascript/places-autocomplete#map_controls
https://developers.google.com/places/supported_types#table3

- if we leave this blank then all will be searched, but we can improve this further

**Item form**
we can add a drop down select or radio field (inside item form) with label "Search Type"
with options according to:

- Address
- Exact Address
- Business Address
- Region
- City

Inside **field configuration**
we can add parameter to select allowed type of searches

- Address [geocode]
- Exact Address [address]
- Business Address [establishment]
- Region [(regions)]
- City [(cities)]

**Comment by ggppdk** [comment]
For now we can just hard code all types, google says 
- it will support old API that uses multiple types, till February 16 2017

so we can leave this enhancement to be done in v3.0.15
and for now use these 3 types:
```
new google.maps.places.Autocomplete(
  document.getElementById("'.$elementid_n.'_autocomplete"),
  { types: [ "geocode", "address", "establishment" ] }
);
```

**Comment by micker** [comment]
great

**Comment by ggppdk** [comment]
Hmm i thought it worked with multiple types, but it seems to only allow 1 type,

my initial test was wrong ?

- i will add "select type" drop-down, next to the autocomplete search field
(as described in the original post)

**Comment by ggppdk** [comment]
Here is current work:

that adds 
- default limiting values
- and optionally allow user to select too

![search_types_in_address_field_2](https://cloud.githubusercontent.com/assets/5092940/14014708/e58d1fc8-f1bc-11e5-97b0-85d50c87b052.png)
![search_types_in_address_field_1](https://cloud.githubusercontent.com/assets/5092940/14014709/e5be7b5e-f1bc-11e5-965d-5b05df44ca3b.png)

**Comment by ggppdk** [comment]
- but i have noticed the business name / title is not added anywhere
- it is just lost

we need 1 more field to keep the business name / title returned by the Google search

**Comment by ggppdk** [comment]
Done with: 3369761

- Fixed business results not returned
- Added storing and display of business name
(NOTE: in vewing TAB : delete contents of Address format parameter and save)
- Added drop down selector for search types (by default ALL)
- Added ability to limit to specific countries
- Added default value for: search type and country
