### ISSUE TITLE
Add support for "Show all pages" link to all modes of flexibreak plugin (multi-paged items) and minor UI improvements

### ISSUE THREAD

**Issue by ggppdk** [FLEXIcontent/flexicontent-cck#504]
Currently only JS pagination mode is allowed to uses "Show all pages" link.

**Comment by ggppdk** [comment]
![multi-page-plg-improved](https://cloud.githubusercontent.com/assets/5092940/14249102/c1ec7fc4-fa80-11e5-908a-630e71eb9100.png)

**Comment by micker** [comment]
:+1:

**Comment by ggppdk** [comment]
Closing this

- Better SEO of page break content plugin (multi-page items) with/without SH404SEF

 a. real links to pages but navigate via JS
 b. Identify hastags in URL and treate the as limitstart
- easier configuration with more display options
- added showall for all modes and verified JS will work in cases of showall=1 
- added 2 new modes TABs and Sliders (like Joomla pagebreak)
