### ISSUE TITLE
mod_flexicontent finds neither "item" or "category" view.

### ISSUE THREAD

**Issue by david-nowinski** [FLEXIcontent/flexicontent-cck#505]
Hello,

A "big" issue in the universal module is that somehow, it doesn't detect any of possible view. It is neither "category" nor "item", so nothing at all is displayed...

I have placed a module through a shortcode in the main description field. The module is called correctly.

I don't know why exactly but using only flexicontent category menus, the items have an option of "com_content" with view as "article".
i have properly set in the type that I want the view to be redirected but it doesn't seem to happen.

The fix is quite easy, in the helper in mod_flexicontent (v3.0.14-rc2a), you must replace the line 823 with :
`$isflexi_itemview = ($option == 'com_flexicontent' && $view == FLEXI_ITEMVIEW && JRequest::getInt('id')) || ($option == "com_content" && $view = "article" && JRequest::getInt('id'));`

**Comment by ggppdk** [comment]
So you mean code that decides if module must be displayed or not be displayed ?

**Comment by ggppdk** [comment]
So you mean to detect Joomla article view and treat it as FLEXIcontent item view

**Comment by ggppdk** [comment]
Added with b6bbe71

Made this change and other modifications in the universal module helper file so that Joomla article and category views are treated as FLEXIcontent item and category views
