### ISSUE TITLE
Issue with frontend language switching of items when using Falang instead of Joomla associations

### ISSUE THREAD

**Issue by ldoliv** [FLEXIcontent/flexicontent-cck#517]
Hello,

I have, Joomla 3.5.1, FLEXIcontent 3.0.14-rc2a, Falang 2.2.2.

My settings:
Flexicontent global config:
![image](https://cloud.githubusercontent.com/assets/6535818/14454386/3d459590-0092-11e6-9800-66a61aefa2a8.png)

Menu Items have language "all" and am translating them in falang.
For articles I'm using the translate button in flexicontent.

I think this issue was addressed by **disabling "Item Associations" in language filter plugin**, **but there is an issue when changing language between articles that don't have menu item**:
https://.../pt/media-noticias/item/**335**-algardata-na-btl-2016
Incorrect generated:
https://.../es/media-noticias/item/**335**-algardata-na-btl-2016

Enabling "Item Associations" in language filter works correctly when changing language for articles without any menu item:
https://.../pt/media-noticias/item/**335**-algardata-na-btl-2016. 
the correct url is generated when changing language:
https://.../es/media-noticias/item/**339**-algardata-en-btl-2016

Doesn't work correctly for menu Items:
https://.../pt/contactos
I get:
https://.../es/site_content/11-institucional/216-contacto
Should be:
https://.../es/contacto

So we lose either way.

**The ideal would be to make it work with item associations enabled, because in the backoffice it's easy to find the translated article with the associations.**

Please fix this. Thanks!

**Comment by Igcorreia** [comment]
Any update?

**Comment by ggppdk** [comment]
You may create a **copy** of the website
and send me super-admin access with email or with PM

thus together with the above description i will be able to test more easy

**Comment by ldoliv** [comment]
Hello I sent you via email access to the site on Tue 03/05/2016 09:44

**Comment by ldoliv** [comment]
Can I send you access to your email ggppdk@gmail.com ?

**Comment by ggppdk** [comment]
yes

**Comment by ldoliv** [comment]
I sent to your email did you receive ?

**Comment by ggppdk** [comment]
Yes i see it ))

**Comment by ggppdk** [comment]
I only see a "Falang Language switcher" module in the web-site
- this will switch language
- but it will not switch the current item

You need to create a Joomla language switcher module, for switching items via associations
The Joomla language switcher module will do both
- switch language
- and switch the associated item, because it will create links that point to every associated item of the corresponding language

please test it

**Comment by ldoliv** [comment]
I created a Joomla Language Switcher module, but It's empty, no links to change language.
In mod_falang helper.php getList function on line 106 has 
` $language->link = JRoute::_($cassociations[$language->lang_code] . '&lang=' . $language->sef);`
Raw link is correct: index.php?option=com_flexicontent&view=item&cid=11:quartos&id=411:basic-twin-adriana&lang=en&Itemid=452&lang=en
Just noticed it has 2 '&lang=en', but the output from JRouter is incorrect:
`/en/hoteis/adriana-beach-club-hotel-resort/quartos/item/411-basic-twin-adriana`
It should be:
`/en/our-hotels/adriana-beach-club-hotel-resort-en/rooms-adriana/item/411-basic-twin-adriana`

Why is JRouter not giving the correct url ?

**Comment by ldoliv** [comment]
Just to give an update, on a fresh install, Joomla 3.6.2, Falang 2.7.0, Flexicontent 3.1.0:
/pt/noticias/6-news2-pt

Changing to EN:
/en/noticias/5-news2-en

Fetches the correct article but doesn't change 'noticias' to news. Correct:
/en/news/5-news2-en

Don't know what's going on.

**Comment by ggppdk** [comment]
The problem is that menu item aliases are supposed to be translated by the falang module,
but this does not happen.
This is not specific to FLEXIcontent component, it happens with other components too
moving milestone to later
