### ISSUE TITLE
Filter for relation fields: item ordering and hiding unpublished items

### ISSUE THREAD

**Issue by Lyquix** [FLEXIcontent/flexicontent-cck#523]
I don't know if this is a bug or a setting that I cannot find:

I am setting filters using Relation fields. The generated drop down list is not following any specific ordering. I have tested changing the Relation field Viewing settings using ordering by core and user fields, and there is no change.

Also, the filter drop down list includes Unpublished items.

**Comment by Lyquix** [comment]
@ggppdk @micker --- have you seen this?

**Comment by ggppdk** [comment]
I have missed this one

What do you mean with "Setting filters using relation fields"
Do you mean a relation field being used as a category/search view filter ?

Maybe post a picture

**Comment by Lyquix** [comment]
Yes, we are using relation field as a category view filter.

**Comment by Lyquix** [comment]
Looks like it was a bug on my side. Sorry about that.

**Comment by Lyquix** [comment]
Reopening this: this is a real issue - I test using FC standard code and I was able to replicate it: the drop downs include unpublished items and they don't follow any specific ordering.

**Comment by ggppdk** [comment]
About unpublished items, do you mean the item form ?
- there is a parameter for this, in the relation field configuration

**Comment by Lyquix** [comment]
No, I don't mean item form. I mean category filters.

**Comment by ggppdk** [comment]
Ok, i see
- will fix unpublished items in the category filter (should be easy)
- about order will see check and make sure it is alphabetic like other filters

But first will address the 2 performance issues of item form 
both related to using **AJAX**
- **relation field in large websites**: ajaxify item list (more work) and optimize item list query (little work)
- avoid loading parameter all layouts: ajaxify this like universal module, (we have another issue for this)

**Comment by Lyquix** [comment]
@ggppdk in regards to ordering, it would be better if it follows the ordering settings for relation field viewing

**Comment by Lyquix** [comment]
@ggppdk : is there a commit regarding this?

**Comment by ggppdk** [comment]
No but this is 3.0.15 milestone, and rather little work, all things for 3.0.15 requiring a lot of work are done

**Comment by Lyquix** [comment]
Sounds good. Here is what we did:

* added condition for state and publish_ip and publish_down
* grab sorting setting from field params and apply it to the query

```
	function onDisplayFilter(&$filter, $value='', $formName='adminForm', $isSearchView=0)
	{
		if ( !in_array($filter->field_type, self::$field_types) ) return;
		$date = JFactory::getDate();
		$now = $date->toSql();
		//Create order clause dynamically based on the settings of the field
		$order = $filter->parameters->get( 'orderby', 'alpha' );
		$orderby = flexicontent_db::buildItemOrderBy(
			$filter->parameters,
			$order, $request_var='', $config_param='',
			$item_tbl_alias = 'ct', $relcat_tbl_alias = 'rel',
			$default_order='', $default_order_dir='', $sfx='_form', $support_2nd_lvl=false
		);
		// WARNING: we can not use column alias in from, join, where, group by, can use in having (some DB e.g. mysql) and in order-by
		// partial SQL clauses
		$filter->filter_valuesselect = ' ct.id AS value, ct.title AS text';
		$filter->filter_valuesfrom   = null;  // use default
		$filter->filter_valuesjoin   = ' JOIN #__content AS ct ON ct.id = CAST(fi.value AS UNSIGNED) AND ct.state = 1 AND ct.publish_up < "'.$now.'" AND (ct.publish_down = "0000-00-00 00:00:00" OR ct.publish_down > "'.$now.'")';
		$filter->filter_valueswhere  = null;  // use default
		// full SQL clauses
		$filter->filter_groupby = ' GROUP BY CAST(fi.value AS UNSIGNED) '; // * will be be appended with , fi.item_id
		$filter->filter_having  = null;  // use default
		$filter->filter_orderby = $orderby;
		
		FlexicontentFields::createFilter($filter, $value, $formName);
	}
```

If you like it I can make a commit. Let me know.

**Comment by ggppdk** [comment]
yes the inteneded behaviour, sounds good,  no PR, you can commit it and i will test too

**Comment by Lyquix** [comment]
Done: https://github.com/FLEXIcontent/flexicontent-cck/commit/0976390f0757ae2f682844826d3724641cd6a60d

**Comment by ggppdk** [comment]
Great,

Just a note usually instead of:
```
$now  = $date->toSql();
```

we would prefer
```
$_nowDate = 'UTC_TIMESTAMP()';
```

because if we want to return the SQL query text via a Joomla cache call, then the 2nd choice is always same text, but the 1st is always different,

It looks good i will test and then also commit change with the "now" date, thanks

**Comment by Lyquix** [comment]
Thank you @ggppdk ! that's a great advice, I am making a commit to fix it.
