### ISSUE TITLE
Redirect template

### ISSUE THREAD

**Issue by Lyquix** [FLEXIcontent/flexicontent-cck#525]
Hey guys, we developed a redirect template for FLEXIcontent. Here is the description:

The Redirect template allows to force redirects on categories and items. The redirect URL can be set on the template, content type, or the individual category and item. This template is useful when you need to organize your content in categories but don't need the category page to be visible. You can also use this to mix content items with redirect items.

You can check it here:
https://github.com/Lyquix/flexicontent_templates/tree/master/redirect

Feel free to incorporate it to the FLEXIcontent core if you think this may be useful.

**Comment by micker** [comment]
Great addition thanks did you test my flexi googlemaps module?  I will be interesting by your returns

**Comment by Lyquix** [comment]
No, I didn't, send me the URL

**Comment by micker** [comment]
https://github.com/micker/mod_flexigooglemap thanks for return
TODO : finishing doc, adding flexicontent field display in infowindows

**Comment by Lyquix** [comment]
Micker, here is my feedback:

* In address field, it would be easier if it shows a list of fields of type addressint, than typing the name
* I love the pin clustering option!!! I think I will use it for my template
* For the infowindow, it may be useful to have a textarea field where you can create your own display for the item where you mix html and placeholders like {{item->title}} of {{fieldname}}

**Comment by micker** [comment]
For adresse fiel good idea need to code it...
For template that in to-do waiting g
@georgios return (after his holiday)

On Thu, Apr 28, 2016 at 4:37 PM, Lyquix < notifications@github.com [notifications@github.com] > wrote:
Micker, here is my feedback:

 * In address field, it would be easier if it shows a list of fields of type addressint, than typing the name
 * I love the pin clustering option!!! I think I will use it for my template
 * For the infowindow, it may be useful to have a textarea field where you can create your own display for the item where you mix html and placeholders like {{item->title}} of {{fieldname}}

**Comment by ggppdk** [comment]
> In address field, it would be easier if it shows a list of fields of type addressint, than typing the name
you can replace **type="text"** for **type="fields" field_type="relation"** :
```
<field
	name="fieldaddressid"
	type="fields" field_type="relation"  fieldnameasvalue="0"
	...
/>
```

> For the infowindow, it may be useful to have a textarea field where you can create your own display for the item where you mix html and placeholders like 
i was supposed to do this

**Comment by micker** [comment]
@Lyquix i added selecting address field selection in last commit (it display name and id of field in module administration)
@ggppdk thanks for type but i use sql field to display namefield (idfield) in dropdown, we can speak about {{fieldname}} replacement when you can

**Comment by ggppdk** [comment]
Now that we have solved the performance issue of forms, when having layouts with have many parameters we can include many more templates into the CORE package

3.0.18 milestone
thanks

**Comment by ggppdk** [comment]
@Lyquix 

to avoid, sites that have these templates already, from having their template files overwritten, the template folder name should be different ... just making a note here so that i remember !!!

**Comment by rubenreyes2000** [comment]
I think this issue can be closed
