### ISSUE TITLE
Multi-level relationships

### ISSUE THREAD

**Issue by Lyquix** [FLEXIcontent/flexicontent-cck#528]
Hello guys

We are looking to work on enhancing the relation / relation reverse field, or creating new fields for handling multi-level relations.

In many of our projects we have found the need to connect items that are related to each other via a 3rd item. 

For example: Physicians are related to Treatments they perform, and Treatments are related to Conditions. This is a multi-level relation between Physicians and Treatments.

This multi-level relation field should be able to jump through multiple relations or reverse relations.

Please let me know if you have any thoughts or ideas. Thank you!

**Comment by ggppdk** [comment]
I think the way to go is to add a parameter in the relation field to select another relation field

then need to think how what should be displayed in such a case
so can you explain this more:
> This multi-level relation field should be able to jump through multiple relations or reverse relations

Also there is an open issue to create basic items that are not tied to com_content ... and define such relations too
Please read this:
https://github.com/FLEXIcontent/flexicontent-cck/issues/277

**Comment by Lyquix** [comment]
Let me explain more with a more complex example: each letter is a different content type, and the arrow indicates the "direction" of relation (on one way we use relation field, in the opposite direction we use relation reverse field)

A > B < C > D < E

I would like to have a field that connects A with E. As you can see some relations use relation fields, some others use relation reverse field.

I think in this complex situations it is better to have a separate field (multi-level relation) where I can create this chain of relations. The logic will work like this:

* A > B is a relation field. We get the list of distinct B items related to A (minus any scope limits)
* B < C is a relation reverse field, so the code needs to be a little different. We get the list of distinct C items that are related to the list of B items (minus any scope limits)
* C > D is a relation field. We get the list of distinct D items related to all C items  (minus any scope limits)
* D < E is a relation reverse field, so the code needs to be a little different. We get the list of distinct E items that are related to the list of D items (minus any scope limits). The D items are also sorted as specified in the field parameters.

So yes, this will require multiple SQL queries to execute each step (or may a super complex single SQL query).

For the display we can use the same logic we have in relation and relation reverse fields.

**Comment by ggppdk** [comment]
I think the best is to do this with 
- the non-com_content types, that we want to introduce in v3.1+

**Comment by rubenreyes2000** [comment]
This issue can be closed

**Comment by micker** [comment]
@rubenreyes2000 did you want to do more for flexicontent dev ? did you want to speak with me about some futur feature ? or exchange about your ideas ? my skype micker31

**Comment by rubenreyes2000** [comment]
@micker we have ideas but we have limited capacity... plus you guys are more advanced in php/joomla development. I am happy to share with you how we currently use FLEXIcontent and what features we would like to see in the future. We will continue to help with small code contributions. Just now I will open a new Issue to discuss some improvements to the Phone Number field that we are working on right now. I will send you a private message via Skype.
