### ISSUE TITLE
Show alert when leaving page with un-saved order changes or even better add a floating SAVE Order button

### ISSUE THREAD

**Issue by Lyquix** [FLEXIcontent/flexicontent-cck#545]
After changing order of items and fields, if user tries to abandon the page without saving changes, there should be a javascript alert to warn and ask if they really want to leave.

This will prevent major frustration when users are making many changes to items or field ordering.

**Comment by ggppdk** [comment]
Yes, i was thinking of doing something for this too

and maybe also ... always triggering instant save if number of items in the website is e.g. <2000
- problems with doing instant saving would only appear in very large websites

thus we can match joomla behaviour ... which is good for small websites

**Comment by ggppdk** [comment]
As said in previous answer, the reason of not doing instant save reason was to avoid problems large websites, ... you can find this issue in the **Joomla issue tracker**, 

but it is not good idea to force it in small websites, so will do both:
- instant save for small websites
- add a **floating save button** (will not add the warning , the floating SAVE Order button is more user friendly)

**Comment by Lyquix** [comment]
Sounds good!

**Comment by rubenreyes2000** [comment]
I think this issue can be closed
