### ISSUE TITLE
Adding per type item creation buttons in backend as submenu to add item

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#55]
In content menu under an "Add item" submenu
- It will be good to add link for creating item of specific type

Example
Add article
Add type 1
Add type 2

That done a link to item with type auto selected, do you think it possible ?

**Comment by ggppdk** [comment]
The item's manager could be made to have tabular look,

1 tab for every type since every type may have custom columns too.

So this will be good in terms of UI

**Comment by micker** [comment]
Good idea but we need to think to keep a lighter ux lol

**Comment by iamrobert** [comment]
You also might consider tabs to accordions for smaller screens:
http://aexmachina.github.io/tabcordion/

so - FLEXIcontent can work with mobile.

-- 
Robert Stark
Web + Graphic Designer
http://www.iamrobert.com
0918 44 88 24

**Comment by ggppdk** [comment]
Right we will do, in v3.1 or later v3.0 is almost done
