### ISSUE TITLE
Problem to see original image

### ISSUE THREAD

**Issue by tevez15** [FLEXIcontent/flexicontent-cck#566]
Hi,

the original image path have this problem: 
`images/stories/flexicontent/item_21_field_23/original/./accao_social_icon.png`

he have **/./**

**Comment by micker** [comment]
where do we have this error ? image field, front end template ?
flexicontent version ?

**Comment by tevez15** [comment]
latest version on github... I tested in modules.

**Comment by ggppdk** [comment]
Fixed with 3943eed
