### ISSUE TITLE
Thumbnail images ignore EXIF rotation data

### ISSUE THREAD

**Issue by Lyquix** [FLEXIcontent/flexicontent-cck#571]
The thumbnails created by the image field discard or ignore the rotation info set in EXIF metadata of JPEG images.

This causes images generated by cell phone cameras, which include EXIF rotation, to produce thumbnails with wrong rotation.

**Comment by Lyquix** [comment]
Perhaps we can add the parameter ar=x when generating thumbnails to make sure the resulting images preserve the EXIF rotation.

**Comment by ggppdk** [comment]
For thumbnail generation via URL yes

and for thumbnail generation via PHP code in our image-gallery field:

https://github.com/FLEXIcontent/flexicontent-cck/blob/master/plugins/flexicontent_fields/image/image.php#L2683

```
$phpThumb->setParameter('ar', 'x');
```

**Comment by Lyquix** [comment]
I made the changes on commit https://github.com/FLEXIcontent/flexicontent-cck/commit/101f87888297da8154bd18a7313bfa531463c67f
Please check it

**Comment by ggppdk** [comment]
Ok i checked every file that you changed, it looks good, also added 1 case that you missed: 
- image.php layout  of fileselement view  in backend

 admin/views/fileselement/tmpl/image.php


so did it work in your tests, is the image rotated according to EXIF ?

**Comment by Lyquix** [comment]
Yes, it works

**Comment by rubenreyes2000** [comment]
I think this issue can be closed
