### ISSUE TITLE
Customize noUi js for filters, and add new range field, with slider display as default display

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#584]
i think i will add option to customize noUi display :
- width
- bar color
- tooltip color
  goal : achieve simply this display

![snip_20160622101910](https://cloud.githubusercontent.com/assets/2539440/16259420/ecaf9960-3862-11e6-803a-da2c8fb7d4d7.png)

Maybe directly in field configuration
what do you think ?

**Comment by ggppdk** [comment]
This is possible per field via CSS, 
since you have unique container id for the fields
and then the noUI slider has enough CSS class

**Instead i see, that we have not added the new range field**
- that was meant to be added ... when we implemented usage of the slider for the filters

(with similar flexible configuration as for the filter)

And we don't need to rediscover the wheel , the code that we used for customizing filter configuration will be copied and modify to create the new field

**Comment by micker** [comment]
That i propose is to add some display option in field configuration likz less option in field template


On Sat, Jun 25, 2016 at 8:52 PM, Georgios Papadakis < notifications@github.com [notifications@github.com] > wrote:
This is possible per field via CSS,
since you have unique container id for the fields
and then the noUI slider has enough CSS class

Instead i see, that we have not added the new range field

 * that was meant to be added ... when we implemented usage of the slider for the filters

(with similar flexible configuration as for the filter)

And we don't need to rediscover the wheel , the code that we used for customizing filter configuration will be copied and modify to create the new field

**Comment by micker** [comment]
Or an other idea will a css administration in global config with principal value to customize flexicontent display with less option
Less option in template become override
Possible ?

On Sat, Jun 25, 2016 at 8:52 PM, Georgios Papadakis < notifications@github.com [notifications@github.com] > wrote:
This is possible per field via CSS,
since you have unique container id for the fields
and then the noUI slider has enough CSS class

Instead i see, that we have not added the new range field

 * that was meant to be added ... when we implemented usage of the slider for the filters

(with similar flexible configuration as for the filter)

And we don't need to rediscover the wheel , the code that we used for customizing filter configuration will be copied and modify to create the new field

**Comment by ggppdk** [comment]
XML to Less parameters are not subject to inheritage,
that is because the CSS files only exist once, creating multiple CSS is not best, as we would need to make even more checks and re-compiles, but also we have the problem that 1 CSS files per field maybe too much

**Comment by micker** [comment]
xml to less i understand
maybe a page to generate flexicontent.css in user template by less paramter ?
