### ISSUE TITLE
Filters of field type "relation" slow down category view significantly

### ISSUE THREAD

**Issue by rubenreyes2000** [FLEXIcontent/flexicontent-cck#588]
Category view loading slows down dramatically when filters are enabled.

Some info about the environment:
6 subcategories
800+ items across subcategories
6 filters (all Relation fields)
50 items per page

The server response time:
Without filters: 1 second
With filters: 9 seconds

Is there anything that can be done to speed up the server response? Can filters be cached?

**Comment by ggppdk** [comment]
Yes especially if you have textarea fields,
because we have single table for all fields

- in such sites / cases you need to configure and use filters in search view

a solution would be for category to use the search index tables created by the search view

for now you need to use search view !!

**Comment by ggppdk** [comment]
Besides using the search view
- to improve performance in category you can disable "Faceted" filter behaviour in most or ALL fields,
this way the filter creation will occur once and then be cached

**Comment by ggppdk** [comment]
Search index tables for filtering the search view 
- are heavily optmized for performance

but forcing search view index into the category, 
- will need work in order for transition to be automatic, 

as most sites have not configured search view index or have different configuration for it
so which configuration we will use for updating the index ?

i think will need to add a message to backend for this

**Comment by ggppdk** [comment]
I noticed that you said that filters are relation fields 
- the effect that i describe is for much larger categories
e.g. views with 5,000 items per category
speaking of sites with 50,000 items or site with a lot of content in textarea fields

in this case it is the DB query used for filtering the relation field is not optimal

**Comment by lyquix-owner** [comment]
Here is some additional research:

1) as I mentioned before, turning Filters OFF in category makes it loads much faster.

2) Filters ON, changed all filters Faceted Filters to "No show all values", and "Page configuration", and the category loads very slow

3) Filters ON, but removed all filter fields from "Select Filters" and the category still loads very slow

**Comment by ggppdk** [comment]
I think problem is with the relation field fitlering
- probably only 1 way to fix properly : introduce an extra DB table
still we may be able to improve current query, without new DB table

Contact me via email,
- but please note that i will need to be allowed to have a local copy of the web-site !

**Comment by ggppdk** [comment]
We now have (recently added)
- value_integer COLUMN (of type INTEGER) in the value tables, which also has an appropriate INTEGER INDEX

making use of it, should offer great improvement, and resolve this

value_integer, value_float, value_date columns,
are currently only used to speed up -order- by CUSTOM field

**Comment by ggppdk** [comment]
Should be little work to make use of new column, changing milestone ...

**Comment by lyquix-owner** [comment]
Thanks @ggppdk !!! We will test it.

**Comment by ggppdk** [comment]
Done, performance in category view should now be better, replaced type cast with DB table column. with commit 492285e

Please test.

**Comment by lyquix-owner** [comment]
Will do, thank you!
