### ISSUE TITLE
Test / info message: No update needed for com_content asset with extra rules message appears randomly

### ISSUE THREAD

**Issue by iamrobert** [FLEXIcontent/flexicontent-cck#589]
Hi ggppdk,

Could you think of why I keep on seeing this message randomly:

"No update needed for com_content asset with extra rules"

![issue](https://cloud.githubusercontent.com/assets/8617673/16687744/f81bac2a-454c-11e6-9bda-042fb336e75d.png)

administrator/index.php?option=com_flexicontent&controller=items&task=items.add&typeid=23&maincat=10

Is something needing to be updated in my template?

**Comment by ggppdk** [comment]
there are 2 of these,

- you should see it only when you login to backend and on the first FC screen that is visited

 i left it there to make sure of recent changes in ACL
- to be compatible with J3.6.0 and with ACL manager component

i will remove it in the v3.0.15 final , in fact i will remove it in next commit

**Comment by iamrobert** [comment]
Thanks for the detailed explanation - ggppdk!

**Comment by ggppdk** [comment]
Done
