### ISSUE TITLE
Translating an item creates a bug

### ISSUE THREAD

**Issue by iamrobert** [FLEXIcontent/flexicontent-cck#596]
Hi,
I am seeing the following error when trying to translate an item (J3.6):

Notice: Undefined property: stdClass::$cats in C:\z2016\UniServerZ\www\g\administrator\components\com_flexicontent\views\items\tmpl\copy.php on line 42

Warning: Invalid argument supplied for foreach() in C:\z2016\UniServerZ\www\g\administrator\components\com_flexicontent\views\items\tmpl\copy.php on line 42

**Steps to reproduce:**
1. Click item checkbox
2. Click translate
/administrator/index.php?option=com_flexicontent&view=items

**Image of problem:**
![issue](https://cloud.githubusercontent.com/assets/8617673/16855003/f6c5ed60-4a45-11e6-82a2-c64d500c3811.png)

**Comment by ggppdk** [comment]
Yes, the "items" DB model of the items manager was changed to allow rendering CORE fields and also render them faster
- that is why the property name has changed
