### ISSUE TITLE
Add new plugin to the CORE contributed by Lyquix

### ISSUE THREAD

**Issue by ggppdk** [FLEXIcontent/flexicontent-cck#599]
Currently , located in repository:
https://github.com/Lyquix/plg_fc_businesshours

@Lyquix 
Name of the plugin looks good, **do you agree to keep the same name**, 
- if i see any compatibility break i will rename it, so that your websites that have it already will not break ?

**Comment by lyquix-owner** [comment]
Feel free to change any part of the code as needed
