### ISSUE TITLE
Plans for a db for countries > cities ?

### ISSUE THREAD

**Issue by jimiero** [FLEXIcontent/flexicontent-cck#601]
Heya,

Do you guys have a plan to add a countries > cities db for flexicontent, we could find a good db over the internet and use it, and with the time we can maybe maintain it by adding cities missing but in a matter that wont affect already added records in flexicontent.

Been looking for something like that for ages and at this time seams there no joomla CCK that can handle this in a nice way.

Could be maybe an extend of international address field, and in frontend side, would be nice that in filters for example when you select a country to automatically show a list of the cities corresponding for that country loaded by ajax

Also ability to use them as direct filter links like:

search-results/country/city/

**Comment by micker** [comment]
good idea but how to find a good db ?

**Comment by jimiero** [comment]
We can all make some research over internet and can share here what we find, but of course we need to have flexicontent leaders permission :)

**Comment by micker** [comment]
You already van use an SQL request on many flexicontent field like select

On Tue, Jul 19, 2016 at 11:34 AM, jimiero < notifications@github.com [notifications@github.com] > wrote:
We can all make some research over internet and can share here what we find, but of course we need to have flexicontent leaders permission :)

**Comment by jimiero** [comment]
@micker what about the relation between country > cities ? will that also be possible with that ? Will it allow you to add new entries in the db without affecting flexicontent records you added before ?

**Comment by lungkao** [comment]
i have database form Eshop

**Comment by jimiero** [comment]
@lungkao is that db is better this this one ? https://www.maxmind.com/en/free-world-cities-database

**Comment by ggppdk** [comment]
We have given thought of it, and had discussed this with micker i think,
make this be a new field or add  a drop down parameter + a button to create the table ?

**e.g. a parameter that looks into a folder for SQL files of common cases**
- and then displays a drop-down of available cases ?
- and a button "create DB table"

But if creating new field, it must be easier for user to find it
- the new field button, should list virtual choices

and redirect to a "select" or selectmultiple field with the relevant configuration

To be honest a small "new field wizard" is good to have but that is another topic,

Will do this: add a drop down parameter that list available SQL files
- for start will add countries and cities
- about skipping choices i think we do need it as  lungkao said

**Comment by jimiero** [comment]
@ggppdk that sounds good, this awesome add + the other feature to add multiple country/city inside international address field will simply rock

**Comment by micker** [comment]
maybe we can add sql file in flexicontent site to share value :
-country
-city
-region
etc

**Comment by lyquix-owner** [comment]
Wouldn't it be better if we do an integration with Google Places? I have experience dealing with GIS and maintaining geo-data is a nightmare. It is a lot of data, we will never have it completely up to date, we need to deal with translations, etc.

The Address International plugin is already integrated with Google Places. The logic can be changed to extracts only countries and cities.

By the way - we will need to define "city" and "region"... there are all kinds of areas and definitions around the world for that.

**Comment by ggppdk** [comment]
Ok the country / cities / regions are special case

The sql files should be for static cases,
- but also allow these to get updates, in terms of new records and labels

so maybe they should be XML files and imported as SQL,
- we have already such an implementation for this

**Comment by jimiero** [comment]
@lyquix-owner using Google Places may cause issues on countries where google may be blocked, like China, another issue with this is it will allow people to type city names and they may use non-english names causing confusion

**Comment by jimiero** [comment]
@ggppdk any decission on this ?

**Comment by ggppdk** [comment]
Rather simple to do this (since we already have implemented 'presets')
1. add support for it in select(mulitple) fields via a "preset' parameter that will automatically populate the "fields" with a appropriate SQL query
2. Provide a link to a download package that will load them into an SQL table

but the suggested:
https://www.maxmind.com/en/free-world-cities-database

seems to many language errors

**Comment by jimiero** [comment]
@ggppdk do you have an example somewhere which I can use ?
