### ISSUE TITLE
Feature request: Form multi-steps

### ISSUE THREAD

**Issue by jimiero** [FLEXIcontent/flexicontent-cck#602]
I've been looking on the forum for this but I see nothing related, would be nice an option which can allow you to split your form into multiple steps

**Comment by ggppdk** [comment]
Yes, this maybe simpler than you imagine,

we can do this JS based like this:

- Use multiple tabs, aka if you want multi-steps then you are asked to create TABs
- run form validation at 1 TAB at a time

and do not allow to go to next TAB until previous tab is good

**Comment by jimiero** [comment]
@ggppdk tabs with validation may be good but what I mean is to load steps pages separately and have also steps in the url like:

submit-form/type-form/step-name1/

next:

**Comment by ggppdk** [comment]
We can achieve to have different URLs too
using anchors:  #step1  (also the anchor name could be customizable)

**Comment by jimiero** [comment]
@ggppdk yes but the tabs will be all in that page, I want to make something clean so that people don't get lost in tabs

**Comment by ggppdk** [comment]
Of course the TABs will be either 
- hidden
- or appear disabled

**Comment by jimiero** [comment]
@ggppdk so can you add this feature to be used ?

**Comment by ggppdk** [comment]
Will happen in v3.2
