### ISSUE TITLE
phpThumb bug - PNG alpha transparency not maintained

### ISSUE THREAD

**Issue by lyquix-owner** [FLEXIcontent/flexicontent-cck#607]
I just wanted to let you know that the version of phpThumb in use in 3.1.0 has a bug where alpha transparency of PNG images is not maintained after resize. I sent the issue to the developers of phpThumb: https://github.com/JamesHeinrich/phpThumb/issues/65#issuecomment-235963245

**Comment by lyquix-owner** [comment]
I solved it by rolling back to phpthumb version used in FC 3.0.14-rc

**Comment by ggppdk** [comment]
It would be much better to try to use the older phpThumb version, instead of going back to FC 3.0.14-rc

**Comment by lyquix-owner** [comment]
The latest commit https://github.com/JamesHeinrich/phpThumb/commit/e9a8ceaa7f808bb2098e849bc68e4d142825e390 fixed it

**Comment by ggppdk** [comment]
nice, I ll include this change in phpThumb version shipped with FC

**Comment by ggppdk** [comment]
Fixed with f27a74b
