### ISSUE TITLE
Google map field and snazzymaps

### ISSUE THREAD

**Issue by id-pop** [FLEXIcontent/flexicontent-cck#608]
Hi,
Is there a way to use snazzymaps style in the google map field display ?
Thanks a lot !

**Comment by ggppdk** [comment]
I see micker add a parameter for it here:
https://github.com/FLEXIcontent/flexicontent-cck/commit/a25e4efefd7d42dfdeb6704ed8a883ef99f4c969

Can you test ?

**Comment by micker** [comment]
tested that work
