### ISSUE TITLE
Enhancements to filter system

### ISSUE THREAD

**Issue by Lyquix** [FLEXIcontent/flexicontent-cck#62]
As we work on various projects the ability to filter items in a category is one of the most powerful features of FLEXIcontent. However, we have found some limitations that we would like to help address and I am looking for your comments and guidance.

1) Filtering by "Related Items" and "Related Reverse" fields

The most pressing enhancement is to add the ability to filter by Related Items. One real-life example is a blog / news category in a healthcare website where we want to allow visitors to filter articles by the medical specialty they are related to.

2) Flexibility in presentation and functionality of the Filters

The filters that come out of the box are very powerful, but for some projects it is necessary to use different/custom styling and functionality. We are thinking that it would be very useful to have a PHP object (or function that returns an object) that contains all the necessary information for assembling the filters. That way we can have our custom category templates generate the filters as we need.

3) Custom query filters (search?)

We have encountered some rare situations where the filter functionality cannot be reasonable achieved by just matching the value of a field, but require more complex logic. We were wondering if we could create a plugin for the purpose of custom queries/search where we can have our custom logic, and that returns an array of item id's.

Let me know your thoughts. If you give me some guideance on what part of the code I need to look, we can start working on this.

**Comment by rubenreyes2000** [comment]
This issue can be closed
