### ISSUE TITLE
About prettyCheckable change in 3.2.0-dev

### ISSUE THREAD

**Issue by JeBy777** [FLEXIcontent/flexicontent-cck#620]
I've noticed that since moving to 3.2.0-dev the prettycheckable checkboxes are now in the black theme? Is it possible to change the theme somewhere or if not add the option for it? Also, when trying to disable prettycheckable on a field with the "Apply JS library" option on NO, it still applies the JS library.

**Comment by ggppdk** [comment]
That is not "prettycheckable" JS

- it is CSS that use a background image

maybe add a less variable for the background image ?
maybe default image needs to be changed to something more generic looking ?

**Comment by micker** [comment]
Maybe gray or black display in global configuration?

On Fri, Aug 19, 2016 at 8:01 AM, Georgios Papadakis < notifications@github.com [notifications@github.com] > wrote:
That is not "prettycheckable" JS

 * it is CSS that use a background image

maybe add a less variable for the background image ?
maybe default image needs to be changed to something more generic looking ?

**Comment by ggppdk** [comment]
I have made old background image be same dimensions as new
and changed the checkboxes to use the old one: checks.png
and kept the new one for radios: checks2.png

https://github.com/FLEXIcontent/flexicontent-cck/commit/42972f38f9b78cf4a9573cbf014319ae75a80415

**Comment by ggppdk** [comment]
Changed new styling to have white background for both checkbox and radio
