### ISSUE TITLE
Custom Textarea field not showing for featured items in universal content module

### ISSUE THREAD

**Issue by ldoliv** [FLEXIcontent/flexicontent-cck#626]
Hello,

I'm using the latest release of flexicontent and joomla 3.6.2.
In universal content module I have 1 featured item, I have added the custom textarea field in the custom fields featured section, but doesn't show. After inspecting the html in chrome the field is there but empty.

It works fine for standard items but not for featured.
Please help.

**Comment by ggppdk** [comment]
since it is working for "standard" items, if this is happening then it should happen with all fields added to the specific parameter, will test

**Comment by ldoliv** [comment]
I have other custom fields added for the feature and they are displaying. For some reason the textarea is empty. The html container for the field is there but empty.

**Comment by ggppdk** [comment]
I tested and it works, do you have feature 'skip items' on-empty field value ON ? I made some relevant fix
