### ISSUE TITLE
default option for image rezize function

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#630]
hello i think we need to change behavior of option for new rezize option
1 enable it on global config
2 enable global config in image field
Maybe display an message in post installation about this last option
why ? because if we didn't do it user need to check all his image field option and after activated global config ... too much work for a great new option !

**Comment by ggppdk** [comment]
I think adding an inline note message in component configuration that these parameter appear

Saying that:
- it effects ALL fields, and if this is not desired then customize per field

I think the above is enough to let user know about how it work

**Comment by micker** [comment]
ok but for now if user a 10 fields and wanted to have one config he need to update all field ..

**Comment by ggppdk** [comment]
Then he sets big global and then cinfigures only 1 field

**Comment by ggppdk** [comment]
Actually what you proposed makes Global configuration difficult
- you can not set a global limit they way you suggest

because by default you suggest to ignore the global limit
- and you propose that you need to edit all fields in order to set to the "Use global"

**Comment by ggppdk** [comment]
I see now that default setting in the fields is not "Use component", strange, i thought it was
i will update the XML files and check default inside PHP code too

**Comment by ggppdk** [comment]
mmm,
 i miss-read you initial post, i thought you proposed the opposite, because i was sure the setting in fields was "Use component setting"  (Use global)

i will fix

**Comment by ggppdk** [comment]
With commit: 0b4d89d
Changed parameters of file/image/minigallery field, for resizing images on upload (upload manager) to inherit from component by default
