### ISSUE TITLE
Adding access override in submition link

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#632]
what do you this if we add level access to initialize content when we create it in front link submission ?
reagrds

**Comment by ggppdk** [comment]
we can add this, 
- but why not add this to the submit menu item ? 

we need to add it to the URL too ?
can you provide more details why we need it to the URL too ?

**Comment by micker** [comment]
maybe it will be a good idea
adminstrator can create submission link with access auto selected
i think it will be good for intranet
