### ISSUE TITLE
Field Group fields do not inherit default value after 1st group

### ISSUE THREAD

**Issue by JeBy777** [FLEXIcontent/flexicontent-cck#635]
Only the 1st field group will have the default value on for example a select field. The others will display the "Select" value.

Also, when adding a field group, the value of a text field gets copied and the new value doesn't get saved. It's only when you re-edit the item and edit the text field that the field gets saved.

**Comment by ggppdk** [comment]
About saving, 
- are you using latest FLEXIcontent from github  ?

Both "master" or "3.1.x-stable" will do as they are same in this

**Comment by JeBy777** [comment]
Yes I am. I always update whenever I see new commits :) I pinpointed the problem now: It only happens when you EDIT an item and create a new field group after an already saved field group. The value of the text field gets copied to the new field group, you can edit it, but it does not get saved until you edit it again after save (I guess this is a Javascript/jQuery duplication issue).

**Comment by ggppdk** [comment]
> but it does not get saved until you edit it again after save (I guess this is a Javascript/jQuery duplication issue).

if it does not get saved, **it points to a wrong fieldname**, the fieldnames are update via JS, if javascript execution stops with an error the fieldnames may not be updated
- please check for javascript errors during clicking copy

i am testing, as we want to make next offical release

**Comment by JeBy777** [comment]
I double checked if I had any javascript errors and I do not. Have you been able to recreate this bug in your installation?

**Comment by ggppdk** [comment]
I am fixing the save bug, 

about default values, i will see what is best behaviour

**Comment by ggppdk** [comment]
I fixed an issue with "untranslatable" broken recently in fielgroup display, please test
- if you still have an issue send me a PM with super-admin via flexicontent forum, so that i can view what is happening, bug maybe trigger with specific fields configuration

**Comment by ggppdk** [comment]
About default value of text field, yes it should be used, i think it should be adding more values, because that is what we do with default values of other fields, 
so i commited this change too

**Comment by ggppdk** [comment]
Fixed in default value not used by text field and a couple of other fields in recent commits, closing this
