### ISSUE TITLE
Invalid URLs in Atom feed

### ISSUE THREAD

**Issue by lyquix-owner** [FLEXIcontent/flexicontent-cck#636]
Hello guys

I am observing invalid URLs in Atom for Joomla 3.6.2 + FC 3.1.0-rc:

Note how the protocol+domain is repeated in all URLs
https://www.lyquix.com/blog?format=feed&type=atom

This doesn't happen in RSS feeds:
https://www.lyquix.com/blog?format=feed&type=rss

In contrast we don't see it in Joomla 3.5.1 + FC 3.0.14-rc2a
https://www.rothmaninstitute.com/stories/news-and-blog/?format=feed&type=atom
https://www.rothmaninstitute.com/stories/news-and-blog/?format=feed&type=rss

**Comment by ggppdk** [comment]
Ahhh, that is a Joomla bug at class JDocumentRendererFeedAtom,

we have not changed the URLs, we are passing absolute URLs,
- a workaround is if Joomla version >= 3.6.0 then pass relative URLs, if earlier version then pass absolute

**Comment by ggppdk** [comment]
Fixed with: 16fbf0b

It seems that relative URLs will work in J3.5.x and will be converted to absolute,
- so since JDocumentRendererFeedAtom does not detect absolute URLs,

changed URLs to be relatives, the JDocumentRendererFeedAtom and JDocumentRendererFeedRss will make them absoluted
