### ISSUE TITLE
Add loading of Google Maps API via loadFramework(), to avoid double loading

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#641]
The google maps  module and the address-international field both load the Google Maps API, this causes double loading that causes a warning to be added to browser JS console. Also it may cause problems in the future

We need to provide an FLEXIcontent API call to loadFramework() , for loading Google Maps API

**Comment by lungkao** [comment]
OpenStreetMap api not good ?

**Comment by micker** [comment]
At first Need to update adress field to use it not ? 



Le 6 oct. 2016 16:16, à 16:16, Pisan Chueachatchai <notifications@github.com> a écrit:

**Comment by ggppdk** [comment]
Added
