### ISSUE TITLE
Custom icon to address field (Concept question)

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#642]
Regarding a future enchancement for googlemap module and internationl-address field (address with googlemap) 
- we can add custom marker for each item

The goal will be, that item authors, can select icon to be used when the location is show in the googlemap.

Question about doing this, i think we can use 2 ways :

**1st way**: By adding an icon list in address field and using it googlemap module
**+** more simple to use just, since just selecting icon from list, and relative simple to manage too (just configuration)
**-** but we need to select and add specific icons in our assets, (still the administrator can select custom folders)

**2nd way**: Allow to add icon via an image field
**+** more flexible selection of image
**-** more work to integrate, need to create 1 more field and set it up to have a proper size for showing as icon in the map
**-** item author may select not so proper images
**-** a little longer load loading times

But i think it will be a great enchanced for display multiple location,
what did you think about being the best approach ?

**Comment by lungkao** [comment]
Look Good

**Comment by ggppdk** [comment]
@micker , @lungkao 

I have made some updates to this issue description,
indeed a marker icon
- per address is the way to go, to make this address field more useful

now, about selecting markers,
- i think to use a folder with a set of default markers, and then only administrator will have access to it to add more markers
