### ISSUE TITLE
Export CSV return

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#643]
My return for csv export
1 adding it on backend that a very good feature with filter !!
2 on first line with name of field, need coma for best separation
![img_07102016_142159](https://cloud.githubusercontent.com/assets/2539440/19190015/4d9d9bb4-8c9b-11e6-9e34-5df4ab96f824.png)
3 if user use select dropdown to display more item that doesn't work, export list only initial number of item
4 can we remove openned windows ? or being smaller (cosmetic suggestion) lol

Thats realy good !

**Comment by ggppdk** [comment]
Should be fixed with: 7da5697
