### ISSUE TITLE
Issue with article link when article title starts with a number

### ISSUE THREAD

**Issue by ldoliv** [FLEXIcontent/flexicontent-cck#644]
Hello,

I'm using FLEXIcontent v3.1.0-rc2
I'm using Universal Flexi Content Module to display articles and there links.

If the article title starts with a number I get a 404 error content not available, could not be found error.
If I place a letter in the alias it works.

Please fix this I should not have to worry about changing the alias, It should just work.
Thank you.

**Comment by ggppdk** [comment]
I tested with current master branch (item alias:  12-test-item)
- with and without a direct menu item pointing to the item, also tried menu item with and without number (menu alias: 12-aaa)

using the URLs created by modules templates: "news" / "carousel"
and i can not replicate this, please test with it,

Maybe you can provide some more details about the configuration that this is triggered

**Comment by ldoliv** [comment]
I found out it was a plugin causing this issue. Sorry for that. You may close this issue it's working fine.
Thank you.

**Comment by ggppdk** [comment]
Thanks for feedback, closing
