### ISSUE TITLE
google maps marker

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#646]
Hello in my test site new googlemap module works ... i tested in live site and it work ...
it realy strange in som site i have a problem with loading image marker
https://github.com/FLEXIcontent/flexicontent-cck/blob/master/modules/mod_flexigooglemap/tmpl/default.php#L199
in some case this line doesn't return good url, i think its a https problem ..
need to explore more ...

**Comment by ggppdk** [comment]
If your current page is https then you can not reference http objects not even images, it is browser policy

https://github.com/FLEXIcontent/flexicontent-cck/blob/master/modules/mod_flexigooglemap/helper.php#L95

Fixed this image URL and 2 more URLs with 3857af5
Please confirm it is good now

**Comment by micker** [comment]
that not good because 
https://github.com/FLEXIcontent/flexicontent-cck/blob/master/modules/mod_flexigooglemap/helper.php#L95
doesn't work ... url of item are added in images url ...
like https://site.com/item/itemname.html/images/mod_googlemap/icon.png
not https://site.com/images/mod_googlemap/icon.png
maybe need to add complete url in $markerdisplay;

**Comment by ggppdk** [comment]
Fixed map's markers when viewing page via https with: 6a01dbe
