### ISSUE TITLE
Pagination with auto-loading infinite scroll (feature request)

### ISSUE THREAD

**Issue by lungkao** [FLEXIcontent/flexicontent-cck#647]
on mobile Instead of clicking on pagination links (very small for use)  

scroll down to reach more content. The older articles will auto-populate as you scroll down through the page.

**Comment by micker** [comment]
Its done by georgios it will an pro paid feature



Le 13 oct. 2016 01:52, à 01:52, Pisan Chueachatchai <notifications@github.com> a écrit:

**Comment by micker** [comment]
close duplicate https://github.com/FLEXIcontent/flexicontent-cck/issues/38
