### ISSUE TITLE
Input placeholder text not escaped when displaying inherited values in category edit form

### ISSUE THREAD

**Issue by lyquix-owner** [FLEXIcontent/flexicontent-cck#648]
We are having an issue with placeholder text no being correctly escaped and breaking the HTML

We are observing this in Category > Layout > Layout Parameters

I have a text field like looks like this:

![](http://i.imgur.com/sCke6JT.png)

After analyzing the HTML we found that the placeholder text is not correctly escaped. You can see the value is correctly escaped.

The string used for placeholder text is the corresponding value from the parent category.

```
<div class="container_fcfield">
<input
 placeholder="Stories: <span class=" lighter">News, Events, Articles, Videos and Ambassadors<span>"
 type="text" 
 name="jform[layouts][custom-events][cat_title_override]" 
 id="jform_layouts_custom-events_cat_title_override" 
 value="Stories: &lt;span class=&quot;lighter&quot;&gt;Events&lt;span&gt;" 
/>
</div>
```

**Comment by lyquix-owner** [comment]
I got it to work by updating this line passing $_v through htmlentities().

https://github.com/FLEXIcontent/flexicontent-cck/blob/3a97fb7186b2aec0d82d8739dfbace2476873bfb/admin/views/category/view.html.php#L357

Probably the whole function getInheritedFieldDisplay should be updated to escape values and placeholders?

**Comment by ggppdk** [comment]
I see,
yes indeed we should escape as HTML can be value of parameters,
and configuration forms that will try to display the inheritted values as placeholders break

No need to PR for this, i will verify that method: **getInheritedFieldDisplay()**
does it everywhere that it is need

**Comment by lyquix-owner** [comment]
Perfect 👍

**Comment by ggppdk** [comment]
I have fixed the issue with category edit form , and also added of inherited values as placeholders to type edit form
