### ISSUE TITLE
Characters like ! as filter value no longer work (happend when  JRequest was replaced for JInput)

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#650]
After changing code to use JInput class instead of JRequest for filtering, characters like é and ! do not work as filter value.

(A recent commit fixed é like-characters, but not characters like !, still do not work)

**Comment by ggppdk** [comment]
The fix that fixed UTF-8 characters e.g. ε é, has fixed characters like !,
please clean cache and retest

I have test just now and ! character inside field filter values works too

**Comment by ggppdk** [comment]
Ok confirmed,
that the fix that fixed UTF-8 characters e.g. ε é, has fixed characters like ! too
closing this
