### ISSUE TITLE
Date Fileld - Range Filter not working

### ISSUE THREAD

**Issue by ldoliv** [FLEXIcontent/flexicontent-cck#652]
Hello,

In this last release FLEXIcontent v3.1.0, date filter interval stopped working. 
For example:
If article has date 2016-10-18, in category view you do start date 2016-10-17 and end date 2016-10-19, no items show.
Also setting only start date or only end date doesn't work. Only shows if start date and end date are exactly 2016-10-18.

**Comment by ggppdk** [comment]
It should be because replacing JRequest with JInput, that is the only relevant thing,
this was fixed in recent days,

Please test with latest github, i remade the v3.1.0 package (it was originally marked as "pre-release")

**Comment by ggppdk** [comment]
I tested , date filtering is broken, i ll make a fix ASAP

**Comment by ldoliv** [comment]
Yes, I tested with latest. Not working.
Thanks

**Comment by ggppdk** [comment]
Fixed with: 32afcd1
