### ISSUE TITLE
Reduce installation package to less than 4MBytes by moving all non-critical 3rd party libraries to seperate package

### ISSUE THREAD

**Issue by ggppdk** [FLEXIcontent/flexicontent-cck#658]
1 big package is problematic as in many websites the usual default is 4 MBytes

**Comment by micker** [comment]
Removing unused language
Removing some php library (not used)
Removing some js library (jquery, fontansownone, pretycheckable select2) with 2 options : loading by cdn or using personnal with relative url option

**Comment by micker** [comment]
remove site/libraries/echarts 3.66MO https://cdnjs.com/libraries/echarts
remove site/libraries/jsquery 1.19MO https://code.jquery.com/
remove site/libraries/plupload 800ko https://cdnjs.com/libraries/plupload
remove site/libraries/thsplitlib 1.74 Mo

**Comment by micker** [comment]
that already done close
