### ISSUE TITLE
Add layout parameters to menu items too

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#659]
Hello to finish better administration we need to add some option in menu link :
- Adding ajax loading for template option for layout tab
- Showing option herited from category

**Comment by micker** [comment]
![linkmenu](https://cloud.githubusercontent.com/assets/2539440/19799091/09a97e54-9cf5-11e6-9c4f-83bb5507ad59.png)
![blog option](https://cloud.githubusercontent.com/assets/2539440/19799092/09c077f8-9cf5-11e6-8856-e5fdaa14a9fc.png)

**Comment by ggppdk** [comment]
This is issue is duplicate to this one:
https://github.com/FLEXIcontent/flexicontent-cck/issues/560
