### ISSUE TITLE
Deprecate groupmarker field in favour of form_design field

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#670]
To enchance this field i propose to add 2 new options :
Slider option to toggle many field at once
Column option : using bootstrap class for basic config (1-2-3-4 columns)

**Comment by ggppdk** [comment]
Also the fields name is confusing,

- Deprecate it in favour of field named "form_design"
and title it "Add custom HMTL, Tabs / Fieldsets / Slider to your form"
