### ISSUE TITLE
Language Association gets lost (deleted) when editing items/articles from front-end

### ISSUE THREAD

**Issue by woluweb** [FLEXIcontent/flexicontent-cck#671]
Hi,

I run a site with latest FlexiContent version (3.1.1).
I have noticed the following bug for multilingual sites : 
- Language Association gets lost (deleted) when editing items/articles from front-end
- but Language Association keeps working fine when editing from back-end

I found a workaround by changing FlexiContent configuration : 
Item Form - FrontEnd > Basic Editing > Existing Items > Allow language modification > CHECK Associations

But that is only a workaround : 
- now that it is checked, I don't have the issue anymore
- but by default it is unchecked, and then
  - it is fine that simple Editors may not change Language Association from front-end
  - but still FlexiContent should not delete the existing Association I guess :-)

Txs,

Marc

**Comment by ggppdk** [comment]
This has been fixed long ago
