### ISSUE TITLE
  FLEXIContent can't save translate language on Falang 

### ISSUE THREAD

**Issue by lungkao** [FLEXIcontent/flexicontent-cck#672]
FLEXIContent can't save translate language on Falang  
i use Flexicontent 3.1.1  Falang 2.6 and 2.7

**Comment by ggppdk** [comment]
I have made a fix,
you may test
https://github.com/FLEXIcontent/flexicontent-cck/releases/tag/v3.1.2-dev-build1

**Comment by lungkao** [comment]
good job
