### ISSUE TITLE
404 page for articles where the title starts with a number

### ISSUE THREAD

**Issue by ldoliv** [FLEXIcontent/flexicontent-cck#673]
Hello,

I'm using FLEXIcontent 3.1.1 and Joomla! 3.6.4
I get 404 page for articles where the title starts with a number.

For exemple: /municipio/noticias/396-12-propostas-em-votacao-no-orcamento-participativo-lagos-2017
I get 404 error saying content 39612 wasn't found.

Could you please let me know what could be causing this issue ?

**Comment by ggppdk** [comment]
It happened when we replaced
```php
JRequest::getInt('id', 0);
```
```php
$jnput = JFactory::getApplication()->input->get('id', 0, 'int');
```

First used to return: 362, thus you got your correct Item
Second returns: 36212, which is obviously wrong

This is surely fixable, we will get string instead then type-cast to "integer" with 
$id = (int) $id;

**Comment by ggppdk** [comment]
Hmmm, no, my previous comment was not correct,
$id = $jinput->get('id', 0, 'int');
will return 362 and not 36212, when you have 362-12-... in the URL as id

I cannot replicate this, send me access via PM in our forum or via email
