### ISSUE TITLE
About automatically adding all images to item form, after uploading them via the AJAX multi-uploader

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#675]
The multi-uploader is friendly and allows to 
- select and upload multiple images at once, while having an AJAX with progress indication

but after it, user is required to select every image, 1 at a time and assign them as image gallery values

Relevant forum thread is:
http://www.flexicontent.org/forum/30-feature-requests/55420-multiple-image-loads.html#65241

**Comment by ggppdk** [comment]
There are 3 things to do regarding this

1. Allow assigning multiple values at once via checkboxes at the rows and adding a button "Assign (use) selected images"
2. besides the above also in the uploader, add CHECKBOX option next to the upload button: "Assign (use) all images after upload"
3. besides the 2 above things, also add an option to the image field to handle the CHECKBOX of number 2, like this:

a. by default check it
b. by default check it and make it readonly,
c. by default check it and hide it

**Comment by micker** [comment]
cool

**Comment by romagromov** [comment]
Is it possible to make upload process same as in this video?

https://www.youtube.com/watch?v=B298BdeIso4

**Comment by ggppdk** [comment]
Automatic adding of uploaded  This was done quite some time ago, but forgotten to close

**Comment by l-arnold** [comment]
What I would like to see would be an easy import, after the fact, of various data.  Images,  Text files etc.

The import tool only works for New Items and it would be helpful to update items.  Doing "multiple" image files to a gallery for instance, via CSV would be helpful.  For instance, one is likely to define a new gallery after the items have been made.

Nice to see that per item a group of items can be dropped on.  I did not know that.  Still with a large database it is easier to have columner updates.

Is there a way to tweak the code for this?  I will study.
Thank you,

**Comment by ggppdk** [comment]
Our CSV import Tool, was changed recently to support updating existing items,

some individual fields like image-gallery field may need some fixes to work with updating too
did you test latest version from github (click download ZIP and install in a test site via Joomla extension manager)

**Comment by micker** [comment]
We need to create à tuto and exemple for field like address sharemedia ect

Le 7 mai 2017 à 19:23, à 19:23, Georgios Papadakis <notifications@github.com> a écrit:

**Comment by l-arnold** [comment]
I am new here to Flexi but I will definitely try the new tool. Thanks for the update and quick response.

**Comment by l-arnold** [comment]
I am hearing the "latest version" needs a full version of Flexicontent (zip) to test the importer tool.

Is there a "importer" only version of this?  Might be easier for me to test.  Could potentially put a Git on it and just pull it in (that said I have not configured flexicontent for git pulls yet.  I have done it for other systems though (Odoo) so shouldn't be "beyond the pale".  
I hate to get a bunch of Community Tech Support going on this but I would like to try the new Importer.
thanks.

**Comment by l-arnold** [comment]
Is this requiring the full "flexicontent" pull or can I focus just on the importer element?
