### ISSUE TITLE
add multi category on mod_flexigooglemap

### ISSUE THREAD

**Issue by lungkao** [FLEXIcontent/flexicontent-cck#676]
add multi category on mod_flexigooglemap

**Comment by micker** [comment]
yes but only for fixed category mode (no dynamic filtering)

**Comment by ggppdk** [comment]
@lungkao
Added, please test and confirm it is working

copied the category parameters and code from universal content module
- we already have a helper method for getting categories like this:

1. selected categories only
2. only children of selected categories
3. selected categories + children categories
4. selected categories + parents categories
5. selected categories + children categories + parents categories

**Comment by lungkao** [comment]
good job  work http://kingdomride.com/

**Comment by ggppdk** [comment]
Ok we added multi-category to the google maps module,
but note this:

- for a complete solution, a new a **"google-maps"** layout for **universal content module** is the way to go

Without the above, we will be continuously rediscovering the wheel and duplicating code from universal content module into the google-maps module

The down-side is that the users are not immediately aware when creating modules in module manager 
that the universal content module has such powerful layout(s), like carousel and google maps, etc

Probably something more is needed to be added at FLEXIcontent dashboard
