### ISSUE TITLE
Lighter FLEXIcontent package

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#687]
hello a reminder for lighter package :
- remove site/libraries/echarts 3.66MO https://cdnjs.com/libraries/echarts
- remove site/libraries/jsquery 1.19MO https://code.jquery.com/
- remove site/libraries/plupload  800ko https://cdnjs.com/libraries/plupload
- remove site/libraries/thsplitlib 1.74 Mo

Adding post-installation instruction for install connex librarie or language 
And loading button to load via official CDN on global config

**Comment by JoshuaLewis** [comment]
I'm all for lighter FlexiContent. Thanks for making this PR. :-)

**Comment by micker** [comment]
closed same  https://github.com/FLEXIcontent/flexicontent-cck/issues/658
