### ISSUE TITLE
Item Manager Select is missing Trashed

### ISSUE THREAD

**Issue by iamrobert** [FLEXIcontent/flexicontent-cck#69]
In the FLEXIcontent Item Manager, when you select the dropdown manage for State there isn't a trashed.

![image](https://cloud.githubusercontent.com/assets/8617673/5056999/ccc6212c-6ce0-11e4-9ecd-f844ddc771c2.png)

Its confusing for the user as the user needs to select from "State Groups".

![download](https://cloud.githubusercontent.com/assets/8617673/5057022/279a216a-6ce2-11e4-9e08-98d45d8e1faa.png)

If an item is trashed - it should be in the state box - shouldn't it?

**Comment by ggppdk** [comment]
Done recently
