### ISSUE TITLE
Blanc screen after install on latest Joomla / missing php7.0-zip

### ISSUE THREAD

**Issue by mvhconsult** [FLEXIcontent/flexicontent-cck#696]
Hey,

I am getting a blanc screen for nearly all content related admin pages after a successful install. No errors seen.

PHP error (sensored)
[Tue Feb 07 14:32:24.823793 2017] xxx mod_fcgid: stderr: PHP Fatal error:  Class 'ZipArchive' not found in /SENSOR/public_html/components/com_flexicontent/classes/flexicontent.helper.php on line 7497, referer: https://DOMAIN/administrator/index.php?option=com_installer

PHP7
Apache
Ubuntu 16

Solution
apt-get install php7.0-zip

Requesting update of checks at install: check for this library in php7

**Comment by micker** [comment]
hello you need to install ziparchive library in your serveur simply
flexicontent work well on php7.1

**Comment by mvhconsult** [comment]
Yes, hence the request to add the check during install, so people do not need to figure this out via error messages.

**Comment by micker** [comment]
its relay a rare case (2 people return with error in one year) but we can check it

**Comment by ggppdk** [comment]
The code was removed for github repository already
this was because ZipArchive at that particular place, was not really needed,

Only the multi-file download task will now make obligatory use of it
@mvhconsult can you make a test install with current github version ?

**Comment by ggppdk** [comment]
The code was removed for github repository already
this was because ZipArchive at that particular place, was not really needed,

Only the multi-file download task will now make obligatory use of it

@mvhconsult can you make a test install with current github version ?
Just click "Download ZIP" on github and install via Joomla installer

**Comment by mvhconsult** [comment]
I have installed version FLEXIcontent v3.2.0-dev-build1 24-Jan-2017, which installed fine.
However, I decided not uninstall the zipArchive library, so no test there, sorry.

**Comment by ggppdk** [comment]
> I have installed version FLEXIcontent v3.2.0-dev-build1 24-Jan-2017, which installed fine.
> However, I decided not uninstall the zipArchive library, so no test there, sorry.

Good, and since now,
only the multi-file download task will now make obligatory use of zipArchive library,
we can close this
