### ISSUE TITLE
Question: template form fields from additional XML file

### ISSUE THREAD

**Issue by lyquix-owner** [FLEXIcontent/flexicontent-cck#697]
Hello

This may be a strange question: is there a way we can configure the template category.xml and item.xml to read and render additional parameter fields from other xml files?

Let me explain in more detail what I am trying to accomplish:

As you may know, we developed our own custom FC template, which you can find here: https://github.com/Lyquix/flexicontent_templates. One of the main objectives of this custom template is to provide us with all the necessary functionality so that we don't need to modify code to achieve different template needs. Anything we need can be achieved via parameters, and overrides. As we make improvements and fixes to the main template, we can update all templates across all our clients without worrying about customizations on each site.

We are facing the following challenge: we need to add some custom parameters to a category. We don't want to add these parameters to our category.xml because they are specific to a client project. Also, these parameters will be managed by non-technical users, so we need to provide a UI that is more friendly than a textarea field where we can pass data in a specific format. So we were thinking: it would be great if we could just create an additional xml file category-custom.xml that would be automatically read and render.

One idea I had was to create a form field in category.xml using a custom form field type, like "extraxml". Then, the PHP code in the elements folder would read and render category-custom.xml. 

Before I start working on that functionality, I wanted to hear your thoughts. I think this might be useful for the core FC templates, providing a way for developers to extend the core templates, on each category or content type, without having to modify core files.

Let me know your thoughts. Thank you!

**Comment by micker** [comment]
its a good idea !
i think to futur goal is :
- kill item and item_html5
- remove ALL unnecessary div (i think we have too much div and class ...)
- adding framework compatibility like uikit or bs3
=> the perfect tool can be a template builder like helix framework but .... a dream

**Comment by micker** [comment]
maybe we can start a commun work for new basic templates for flexicontent and PR it in core ?

**Comment by lyquix-owner** [comment]
Yes, we will start some work on it.

**Comment by micker** [comment]
cool
what did tou pofer for process ? i propose
1 some mockup
2 define basic option
3 php code
what do you think ?

**Comment by lyquix-owner** [comment]
@micker I will start with the functionality for reading additional xml. I don't think I need design for that.

**Comment by micker** [comment]
ah sorry my poor englsih

**Comment by lyquix-owner** [comment]
Here is some that I found:

XML provides a standard for extending a file with the contents from another file:

https://www.w3.org/TR/REC-xml/#sec-external-ent
http://stackoverflow.com/questions/5121052/can-we-import-xml-file-into-another-xml-file

However, it seems like the way Joomla parses XML files don't allow for this to happen:

http://stackoverflow.com/questions/12737985/include-xml-in-xml-joomla

So this is what we did:

1) Small change to file `/components/com_flexicontent/classes/flexicontent.helper.php` line 5211, added LIBXML_NOENT to line below:
`$doc = simplexml_load_file($tmplxml,null, LIBXML_NOENT); `

2) On our category.xml file added the following code after `<?xml version="1.0" encoding="utf-8"?>`
```
<!DOCTYPE install PUBLIC "-//Joomla! 2.5//DTD template 1.0//EN" "http://www.joomla.org/xml/dtd/1.6/template-install.dtd" [
       <!ENTITY extend SYSTEM "extend.xml">
    ]>
```
and in the part of the file where we want to include the additional files we added `&extend;`

3) Created a new XML file extend.xml, with the following code:
```
<?xml version="1.0" encoding="utf-8"?>
<field name="extend_sep" type="separator" hr="false" default="Extra-Parameters" description="Extra Parameter section" level="level1" menu="hide" />
<field name="segment_1_img" type="media" field_type="image" default="" label="Segment 1 Image" description="Upload an image to use for segment 1 banner" fieldnameasvalue="1"/>
<field name="segment_2_img" type="media" field_type="image" default="" label="Segment 2 Image" description="Upload an image to use for segment 2 banner" fieldnameasvalue="2"/>
<field name="segment_3_img" type="media" field_type="image" default="" label="Segment 3 Image" description="Upload an image to use for segment 3 banner" fieldnameasvalue="3"/>
```

The good news: the fields are rendered as expected!
The not-so-good news: even though the form and POST request include the field values, they are not stored in the database.

Screenshots:

![](http://i.imgur.com/8eTLJWO.png)

![](http://i.imgur.com/mSI4cA6.png)

We didn't want to touch Joomla core files, but maybe it will be necessary.
Any of you have any ideas?

**Comment by lyquix-owner** [comment]
Hey guys, do you have any comments?

**Comment by rubenreyes2000** [comment]
Guys I am submitting a PR for this. It is a super minor change that will enable this functionality. Has no effect or harm on existing template XMLs.

**Comment by micker** [comment]
thanks for pr !
