### ISSUE TITLE
PHP fatal error with image custom fields

### ISSUE THREAD

**Issue by sakiss** [FLEXIcontent/flexicontent-cck#703]
## How to reproduce
1. Add an image (image or gallery) field to an item
2. Try to edit the item

## Result
 0 [] operator not supported for strings 

Call stack	
blabla
12		FLEXIUtilities::call_FC_Field_Func() /components/com_flexicontent/classes/flexicontent.fields.php:456
13		plgFlexicontent_fieldsImage->onDisplayField() /components/com_flexicontent/classes/flexicontent.helper.php:6158

## Environment
PHP 7.1.2
Joomla 3.6.5
FC 3.1.1

## Misc.
The error is generated in the file: plugins/flexicontent_fields/image/image.php
More specifically in line 929
`$field->html[] = '`

The $field->html is used all over that function. Other times as a string others as an array.
That causes conflict.
Possibly that error is not generated in lower php versions due to more elastic handling of datatypes

**Comment by ggppdk** [comment]
Yes, this will happen with FLEXIcontent v3.1.1
but this issue is already fixed in this repository

see here:
https://github.com/FLEXIcontent/flexicontent-cck/blob/master/plugins/flexicontent_fields/image/image.php#L767
```php
		$field->html = array();  // Make sure this is an array
```

**Comment by sakiss** [comment]
That works. Thanks!

**Comment by ggppdk** [comment]
This has been fixed quite a while ago, closing
