### ISSUE TITLE
Can you please consider to write a Content Provider plugin for Widgetkit to retrieve and render Flexicontent fields?

### ISSUE THREAD

**Issue by grabit** [FLEXIcontent/flexicontent-cck#711]
Yootheme has developed a widget system called Widgetkit. It can find content from various provider systems (Twitter, Instagram) but also from some CCK (Joomla content, K2, ZOO) It would be great to add Flexicontent to that list.

The documentation: http://yootheme.com/widgetkit/documentation

Here is the link to the info for creating a content provider plugin: http://yootheme.com/widgetkit/documentation/customizing/custom-content.

If you need the files I can help.

**Comment by step-it** [comment]
I'm looking for the same feature: can you seriously consider this, also considering to ask for a reasonable fee for that plugin?

**Comment by l-arnold** [comment]
I need this as well.  I did notice there is a Widgetkit based gallery setting in some of the gallery image fields.

**Comment by l-arnold** [comment]
This looks "somehow easy".  That said, it is worth looking at the detail.

https://yootheme.com/widgetkit/documentation/customizing/custom-content

**Comment by step-it** [comment]
I know it's hard to tell it exactly, but I'm wondering if you have an extimated beta release date...
Thanks & regard

**Comment by ggppdk** [comment]
Hello this has a v3.2.1 milestone

Now working on v3.2.0,
to finish "reviews" feature,
also need to release new version since v3.1.1 has frontend date filter broken in J3.7.x
so adding this in v3.2.0 is unlikely

but due to interest for this i have added higher priority not miss it

**Comment by l-arnold** [comment]
I saw the 3.2.xx branch.  Does this have some traction?  I expect the last update with Joomla 3.7.4 was a big milestone to be sure.

**Comment by ggppdk** [comment]
Will work on this next week, please ask for update in mid of next week

**Comment by step-it** [comment]
Just posting a reminder: do you have news?
Thans & Regards.

**Comment by step-it** [comment]
Any news about? Is this job in progress or not? Thanks :)

**Comment by ggppdk** [comment]
Hi with the release of 3.2.1.2 +
we hope to have a solid that can last longer and allow work on things like this one

please make a reminder here next week

**Comment by step-it** [comment]
OK, and thanks for your unchanged availability :)

**Comment by step-it** [comment]
This is just a reminder: any news? Regards

**Comment by micker** [comment]
Did you have a return about yootheme ?

Le 24 sept. 2017 à 12:31, à 12:31, MMC Edizioni <notifications@github.com> a écrit:

**Comment by step-it** [comment]
Still waiting for: I use WidgetKit since many years, and FC too, and also asked for that interface since a long time :)
It would be nice to finally get them working together by using official FC plugin

**Comment by ggppdk** [comment]
Creating such a plugin would be much easier work for us than it would be for yootheme
I will review time needed if time needed is 1 full day's work then will do

**Comment by step-it** [comment]
A further reminder :) Any news about that? Thanks

**Comment by webiedesign** [comment]
I am happy to contribute funds for this development as well.

**Comment by ggppdk** [comment]
@webiedesign 

please contact me via PM in FLEXIcontent forum

**Comment by grabit** [comment]
Any news about that?

**Comment by ggppdk** [comment]
> Any news about that?

Yes find time for this during next 5 days

**Comment by webiedesign** [comment]
any news on this ?

**Comment by ggppdk** [comment]
@webiedesign 

Hi sorry for late return on this,
it is in priority together with the syncing / mapping FLEXIcontent tags with Joomla tags

will work on this during this weekend !!

**Comment by step-it** [comment]
Any news about that topic? I would like to use it in my new project, where I plan to also use FC PRO version when available.... Please update, thanks :)

**Comment by ggppdk** [comment]
Working on it for a while this morning

For now it has the same options as 'Joomla' Content Provider, 
lets see what we can add to it

![widgetcontentproviderfc](https://user-images.githubusercontent.com/5092940/42217070-7feee602-7ecc-11e8-8496-0f054bb77c12.png)

**Comment by step-it** [comment]
It seems to be a very good starting point

**Comment by step-it** [comment]
Got results? News? Thanks :)

**Comment by mekamak** [comment]
Thanks
