### ISSUE TITLE
Menu Item - JEvents

### ISSUE THREAD

**Issue by stewart9643** [FLEXIcontent/flexicontent-cck#714]
Trying to create a menu item for a article page in blog configuration. If I select new category than I get a Save and Close button that doesn't work. If I select an existing category than I have no way to confirm my selection.
3.3.0-dev   Release date: 2017-01-24

**Comment by ggppdk** [comment]
@stewart9643
You description combined with the title "JEvents" is not clear

Maybe you posted in wrong repository otherwise please post a picture
