### ISSUE TITLE
Category items list ordering by RANDOM

### ISSUE THREAD

**Issue by lyquix-owner** [FLEXIcontent/flexicontent-cck#715]
Hello

In a previous issue we discussed adding the option for https://github.com/FLEXIcontent/flexicontent-cck/issues/347

This works very well except for the cases where you have pagination: moving among pages randomizes the items every time, which doesn't provide a good user experience.

Currently we randomize the items by using `RAND()` in the `ORDER BY` clause of the SQL query:

site/classes/flexicontent.helper.php
static function _getOrderByClause(...)

```php
case 'random':
	$order_col	= 'RAND()';
	$order_dir	= '';
	break;
```

It is possible to provide a seed to the `RAND()` function, an unsigned 4 bytes integer (0 - 4294967295). When providing the same seed the results are sorted the same way.

I propose we use this functionality to ensure that individual users get a proper experience: the items are randomized, but they don't change on every page view. To accomplish that I propose using the user's Joomla session ID. I think this provides a good balance of stability for individual users and sessions, while providing the desired randomization across different users.

Here is how I'd do it:

```php
case 'randomNEW':			// we may want to create a new sorting type for this
	$s = JFactory::getSession();
	$sid = $s->getId();	// get session id
	$sid = str_split(md5($sid), 8);	// convert to array of hex strings (4 bytes each)
	$seed = null;
	foreach($sid as $b) {
		$b = hexdec($b);		// convert hex to decimal
		if($seed == null) $seed = $b;
		else $seed ^= $b;		// perform xor operation to keep it to 4 bytes
	}
	$order_col	= 'RAND(' . $seed . ')';
	$order_dir	= '';
	break;
```

I know, the whole md5 > hex > dec > xor thing might be an overkill but it seems to be relatively a simple way of using the complete session ID string and convert it to an unsigned 4 bytes integer.

I tested this and it works. Let me know what you think.

**Comment by ggppdk** [comment]
@lyquix-owner

Thanks, yes, wanted to somehow fix pagination for random order
and your suggestion to SEED it like this, looks proper

Added your fix with commit: b60cdff89
