### ISSUE TITLE
Upload one image doesn't work

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#719]
hello in new uploader
if we use
<img width="65" alt="capture d ecran 2017-03-21 a 15 17 31" src="https://cloud.githubusercontent.com/assets/2539440/24552409/9495e606-1626-11e7-9631-72e7b2a5a5ae.png">
we have this error
<img width="1017" alt="capture d ecran 2017-03-21 a 15 04 10" src="https://cloud.githubusercontent.com/assets/2539440/24552422/a59481ba-1626-11e7-93dd-3b51f2ea11a0.png">

**Comment by sitefaitbienfait** [comment]
Hi,

It seems to work in frontend but i have same error in backend.

**Comment by ggppdk** [comment]
@sitefaitbienfait 

Did you try the current github version
or did you download some nightly-build package ?

**Comment by micker** [comment]
On github for me

Le 21 avr. 2017 à 22:36, à 22:36, Georgios Papadakis <notifications@github.com> a écrit:

**Comment by ggppdk** [comment]
Fixed with 2808001
