### ISSUE TITLE
New style for tabs

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#720]
hello i think we need lighter design and lighter css
i propose to update css of default tabs like this
![snip_20170404163807](https://cloud.githubusercontent.com/assets/2539440/24662439/58462116-1955-11e7-8c3f-b70fc6cadaf2.png)
in backend we can choose icon + light color
=> goal is less css and lighter display wihtout css modification
are you agree ?

**Comment by micker** [comment]
maybe we can add it in backend for lighet admin but not sure

after i this we need to remove all unwanted border or dashed underline => web designer took less time to override style

**Comment by supachaiteasakul** [comment]
Hi, @micker 

The new style for tabs look like clean and lightweight can be usability for user, But can make that to support responsive style too or not?

Thanks

**Comment by micker** [comment]
i don't understand tabs are responsive

**Comment by micker** [comment]
what do you think about this
![snip_20170405111352](https://cloud.githubusercontent.com/assets/2539440/24698451/ff80d7dc-19f0-11e7-9785-39aa66ff1f94.png)

**Comment by micker** [comment]
and this in backend
![snip_20170405111457](https://cloud.githubusercontent.com/assets/2539440/24698490/25570f3a-19f1-11e7-982d-677d87e4ee97.png)

**Comment by micker** [comment]
much lighter not ?

**Comment by micker** [comment]
and maybe
![Uploading snip_20170405113054.png…]()

**Comment by supachaiteasakul** [comment]
Hi, @micker 
I think screenshot2 from  remove background label like joomla it lighter, But you can try remove icon in label and before tab title like joomla too for fast load and lighter test?

Thank you

**Comment by micker** [comment]
hello i didn't think its a problem to load icons ?

**Comment by micker** [comment]
done
