### ISSUE TITLE
add fieldname for different class for  li class 

### ISSUE THREAD

**Issue by lungkao** [FLEXIcontent/flexicontent-cck#722]
`<div class="flexi infoblock <?php echo $bottom_cols; ?>cols group">
			<ul class="flexi">
				<?php foreach ($item->positions['bottom'] as $field) : ?>
				<li class="flexi">
					<div>`
add fieldname for different class
`<li class="flexi <?php echo $field->name; ?>">`

**Comment by ggppdk** [comment]
Done (lvbox + fieldname CSS classes) 
with commit bc5681aae
