### ISSUE TITLE
embed.ly become paid service

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#723]
hello embed.ly become paid (99€/year for video) service video field is now broken .... @Lyquix @ggppdk 
Do you have some idea ?

**Comment by lyquix-owner** [comment]
wow, $99/month for API access...

I don't know of another similar service, but I will research. Maybe we will need to connect to specific APIs as we had done initially (Youtube, Vimeo)

**Comment by lyquix-owner** [comment]
This seems to be a viable alternative: https://noembed.com/

**Comment by ggppdk** [comment]
Yes we should replace it ASAP
Lets try to replace it with https://noembed.com/ or other

Also it is good that we kept the native API support in the code for the common cases

**Comment by micker** [comment]
Interesting code... Need to sûre that free ! I see that code can be use for image... Good feature too

Le 24 avr. 2017 à 23:13, à 23:13, Lyquix <notifications@github.com> a écrit:

**Comment by lyquix-owner** [comment]
Ok, here is a very quick and dirty solution (untested):

1) Replace:
```js
ajax_url = "https://api.embed.ly/1/oembed?url="+encodeURIComponent(url)+"&key='.$embedly_key.'&maxwidth=1280&wmode=transparent&secure='.$force_ssl.'&autoplay='.$autostart.'&callback=_cbfunc_'.$field_name_js.'";
ajax_type = "html";
```
with:
```js
ajax_url = "https://noembed.com/embed?url="+encodeURIComponent(url);
ajax_type = "json";
```



2) Replace:
`embedlyCallback_'.$field_name_js.'(response, element_id);`
with:
`noembedCallback_'.$field_name_js.'(response, element_id);`




3) Replace function `embedlyCallback_` with:
```js
function noembedCallback_'.$field_name_js.'(data, element_id)
{
	element_id = typeof element_id === "undefined" || !element_id  ?  fc_elemID_'.$field_name_js.' : element_id;    // *** element_id not set if called as callback
	
	if (typeof data === "object" && typeof data.error == "undefined") {
		
			var urlregex = /(http:|ftp:|https:)?\/\/[\w-]+(\.[\w-]+)+([\w.,@?^=%&amp;:\/~+#-]*[\w@?^=%&amp;\/~+#-])?/;
			if (data.html.match(urlregex) != null)
			{
				toggleMETArows_'.$field_name_js.'(element_id, 1);
				var embed_url = data.html.match(urlregex)[0];
				setEmbedData_'.$field_name_js.'("noembed:"+data.provider_name.toLowerCase(), embed_url, element_id);
				setMetaData_'.$field_name_js.'({title: data.title, author: data.author_name, duration: data.duration, description: data.description, thumb: data.thumbnail_url}, element_id);
				jQuery("#fcfield_sm_mssg_" + element_id).html("");
			} else {
				jQuery("#fcfield_sm_mssg_" + element_id).html("IFRAME SRC parameter not found in response");
			}
	}
	else {
		var errorText = typeof data === "object" ? data.error_message : data;
		jQuery("#fcfield_sm_mssg_" + element_id).html("<span class=\"alert alert-warning fc-iblock\"><i>'.JText::_('PLG_FLEXICONTENT_FIELDS_SHARED'.$_MEDIA_.'_SERVER_RESPONDED_WITH_ERROR', true).'</i><br/><br/>"+errorText+"</span>");
	}
}
```

**Comment by micker** [comment]
I will test it asap

Le 25 avr. 2017 à 16:24, à 16:24, Lyquix <notifications@github.com> a écrit:

**Comment by micker** [comment]
tested and worked ... can you do a pr ?

**Comment by lyquix-owner** [comment]
@micker - I don't think I will be able to get work on this until next week. If anyone else is available and can do some further testing, please don't wait for me.

**Comment by ggppdk** [comment]
> I don't think I will be able to get work on this until next week.

@lyquix-owner 

Ok, thanks,
you spent some good time on this, to suggest the above mentioned solution
will test and commit the code you provided above

**Comment by micker** [comment]
done c93adac

**Comment by ggppdk** [comment]
Closing this since
embed.ly was replaced with  noembed.com
thanks @lyquix-owner and @micker
