### ISSUE TITLE
www.flexicontent.org link broken

### ISSUE THREAD

**Issue by iamrobert** [FLEXIcontent/flexicontent-cck#725]
Hi,

Just a little issue - on the flexicontent site top menu - Project > Source Code Repository - its been broken for awhile:

![link-broken](https://cloud.githubusercontent.com/assets/8617673/25604976/5042143e-2f3a-11e7-9c87-d1190b553f00.jpg)

**Comment by ggppdk** [comment]
Thanks, i have updated the broken link
