### ISSUE TITLE
feature request : Image Field Fallback (when image missing)  Category parameter

### ISSUE THREAD

**Issue by lungkao** [FLEXIcontent/flexicontent-cck#727]
feature request : Image Field Fallback (when image missing)  Category parameter

**Comment by ggppdk** [comment]
You mean image field should read and use this category parameter ?

PS: We have parameter in blog layout 
- to add a default image per item type
it is not as you request but you may find useful

**Comment by lungkao** [comment]
Image Field Fallback same FLEXIcontent - Universal module

 can use images Field  and use introtext image when image field has no value  if  no  introtext image and  image field has no value use default image 

some web use joomla article run up to 1000 item if use images Field  old item can't show introtext image and some item don't have  introtext image


![screen shot 2560-05-12 at 6 33 23 am](https://cloud.githubusercontent.com/assets/2047778/25976127/02bba748-36dd-11e7-9d7c-485f9d30e29f.png)
