### ISSUE TITLE
Submit form (front) blocked category is ignored

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#734]
Hello on last Git 
1 create a link to submittion
2 use override and set a defaut category
=> category selector is displayed and no catégory was selected

**Comment by ggppdk** [comment]
I made an update to these yesterday , but nothing should have changed , regarding the override, maybe i broke something, i ll check and fix in afternoon together with save as copy for frontend

**Comment by micker** [comment]
cool thanks

**Comment by ggppdk** [comment]
Fixed with 3b93086
