### ISSUE TITLE
[backend] new ajax-apply button needs to -reload- form when changing item type

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#735]
if we change type and use new apply button (without reload) nothing was changed need to use apply and reload, it will a bug for end user

**Comment by ggppdk** [comment]
Aaa yes

there are cases that we will need to force the AJAX "apply" button , to also do a reload
- and this is 1 of them

since this case is easy to detect, we should force a reload indeed,
i will do this change

**Comment by micker** [comment]
ok cool

**Comment by ggppdk** [comment]
Fixed / Done with ad2b511

When changing item, ajax-apply will be replaced with an apply-reload
and furthermore:
Form field validation will be skipped
