### ISSUE TITLE
[item form field] html tag are remove

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#739]
hello 
if i use
`<div class="alert alert-info">Lorsque le colloque est passé, pensez à : <br/>
- changer de catégorie l'événement <br/>
- supprimer le contenu du champ "S"inscrire" <br/>
- mettre en ligne les actes dans les publications et sur Calameo <br/>
- ajouter des informations dans cet onglet</div><br/>
`
render is
`Lorsque le colloque est passé, pensez à : - changer de catégorie l'événement - supprimer le contenu du champ "S"inscrire" - mettre en ligne les actes dans les publications et sur Calameo- ajouter des informations dans cet onglet`

**Comment by ggppdk** [comment]
which field ?
where exactly ?

**Comment by micker** [comment]
sorry github revrite my code
in html item form field
we try to insert html tag like <div class <br/ ....
they aren't render in form

**Comment by micker** [comment]
Solved with https://github.com/FLEXIcontent/flexicontent-cck/commit/17422d1af4babae7da8c8190b990e864708d0551
