### ISSUE TITLE
Field name generation like alias

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#740]
It will be good to generate field-name like alias

Example:
`Company Address` can be `company_address`

It will be more user-friendly than `field42`

**Comment by ggppdk** [comment]
Done with 306fc0c
Added to field-names language transliteration out of field's label

Same done for tag-aliases based on tag title, plus allowed unicode aliases if this is enabled in Joomla's global configuration

**Comment by sitefaitbienfait** [comment]
Hi,
Withe this commit : 306fc0c, is it possible that the name field is updated even if it was alread defined by user?
I used to name my field this way : 'type_field' like : 'book_author'
When i edit my field, the field name is renamed in 'book-author' (and i lost field placement in template manager and in my custom item, category, and module templates).

May be we could check if fieldname is empty before rename it.
Sorry for my poor english
Regards

**Comment by ggppdk** [comment]
if existing names are changed then it is surely a bug !

existing field names should not be changed **unless they have bad characters !!**
as if they are change,
then it breaks (as you descrubed) the field references by its name inside the PHP code 

i ll check this ASAP, re-opening

**Comment by ggppdk** [comment]
@sitefaitbienfait 
what exactly are the value of  both 
Lable and **Field name** that you had ?

I tested with the following and the fiedname was not changed
Label: Book author
Fieldname: book_author

**Comment by micker** [comment]
tested
1 create field withaout field name : Code postal
=> field name become code-postal great
2 rename field name to code_postal_offre => become  code-postal-offre

**Comment by ggppdk** [comment]
What is happening is not replacement of _ with -
instead the current alias is disgarded completly
and the default alias uses transliteration for the language characters and - for spaces

Did you type some accented character into the fieldname ?

i saved fieldname code_postal_offre 
without problem

**Comment by ggppdk** [comment]
JApplicationHelper::stringURLSafe() does not allow underscore,
solution is not to call it if fieldname is alread ALL-Ascii characters

Fixed with df3b281b8
