### ISSUE TITLE
Improve UX and SEO by adding ability to loop the next / previous links of Navigation field (next / previous item)

### ISSUE THREAD

**Issue by lipatovroman** [FLEXIcontent/flexicontent-cck#744]
It is good UX and SEO if add ability to loop the links of navigation field
so that 
- instead of "No next item" we get link to the first item
- instead of "No previous item" we get link to the last item

Relevant forum topic:
http://www.flexicontent.org/forum/30-feature-requests/55964-looped-navigation-field.html #

**Comment by ggppdk** [comment]
Done with: 999c10a
