### ISSUE TITLE
Master field with/without prompt text

### ISSUE THREAD

**Issue by prathumwan** [FLEXIcontent/flexicontent-cck#745]
If you add a new item with master/child fields, and the prompt text option of master field is set to "add no prompt", the dependend field show "no data found". Looks like the ajax part not get triggered.
![fc_master_with_no_prompt](https://user-images.githubusercontent.com/16284417/27541420-0c8c11a0-5aae-11e7-9a46-1f2591def211.jpg)

**Comment by ggppdk** [comment]
I have made a fix for this
please confirm that it is now working

**Comment by prathumwan** [comment]
No, same situation.
Happen only for new item, existig item is ok.

Can give you access to my test site if that helps.

2017-06-28 19:47 GMT+07:00 Georgios Papadakis <notifications@github.com>:

**Comment by prathumwan** [comment]
please look again and do this example:

I used 2 select fields, master and slave

**field test1 select (add prompt:yes)**
1::one%%
2::two%%
3::three%%
4::four

**field test2 select (master: test1)**
1blue::one blue::_NA_::1%%
1red::one red::_NA_::1%%
2blue::two blue::_NA_::2%%
2red::two red::_NA_::2%%
3blue::three blue::_NA_::3%%
3red::three red::_NA_::3%%
4blue::four blue::_NA_::4%%
4red::four red::_NA_::4

1) add a NEW item with the default settings (prompt yes). This is the left column in the attached image. The master field show "please select", slave show "no data found" (this change later when removing the prompt)

2) change the master field to "no prompt" and add a NEW item. This is the right column in the attached image. The problem is that the first availible value is now shown at master field "one" and "no data found" at field2. You can not select "one" because its already selected and field 2 is empty. You need choose e.g. value "two" at master field and then change back to "one" to get options for field2. If master field has only 1 value there is no way to select a value from field 2.
![fc_master_and_prompt_option](https://user-images.githubusercontent.com/16284417/27651090-4ffaa834-5c61-11e7-9eb1-6a90d207754c.jpg)

**Comment by ggppdk** [comment]
It should be working now, you can test

**Comment by prathumwan** [comment]
tested and looks good, confirm that it is fixed now.
thanks
