### ISSUE TITLE
Add 3rd type of UX styling for labels ... of fields and of label properties

### ISSUE THREAD

**Issue by ggppdk** [FLEXIcontent/flexicontent-cck#748]
We now have 
label layouts
- table-based
- bootstrap addon style (prepended to the form elemets)

a good UX , modern style is the label as placeholder, that on input
- either hides completely, 
- or it shrinks and moves above

(we will support both the above)

only noticable disadvantage is more vertical space
but has many other advantages , that i will not write here now

Since our form layouts are are already implemented, adding 1 more is not too much time-consuming
- this is more than worthwhile the time to do it ...

http://forms.viewflow.io/demo/registration/

**Comment by micker** [comment]
+10000

**Comment by ggppdk** [comment]
Here is an early picture of how the new layout looks when applied to
- extended-weblink field

![inner_labels2](https://user-images.githubusercontent.com/5092940/27792980-d19aa078-6004-11e7-8142-4488dad61e59.png)

**Comment by micker** [comment]
great display

**Comment by prathumwan** [comment]
ergonomic and good usability

**Comment by ggppdk** [comment]
As a start added this new styling to fields:
- extended weblink
- weblink
- email

Later more custom fields and also core properties will use this mode , will do some of this work in v3.2.1+
