### ISSUE TITLE
Fields don't work in category view

### ISSUE THREAD

**Issue by exstreme** [FLEXIcontent/flexicontent-cck#749]
Adding custom fields in any of "Available zones" (above-description-line1
above-description-line1-nolabel
above-description-line2
above-description-line2-nolabel
under-description-line1
under-description-line1-nolabel
under-description-line2
under-description-line2-nolabel
renderonly)
But in category_items.php I become empty positions. By example
`
			<?php if (isset($item->positions['above-description-line1'])) : ?>
			<div class="lineinfo line1">
				<?php foreach ($item->positions['above-description-line1'] as $field) : ?>
				<div class="element">
					<?php if ($field->label) : ?>
					<span class="flexi label field_<?php echo $field->name; ?>"><?php echo $field->label; ?></span>
					<?php endif; ?>
					<div class="value field_<?php echo $field->name; ?>"><?php echo $field->display; ?></div>
				</div>
				<?php endforeach; ?>
			</div>
			<?php endif; ?>
			`

**Comment by ggppdk** [comment]
Maybe the current category view is using a different FLEXIcontent template layout

To make sure that you are editing the correct file
add a:
```<?php
echo 'current file: ' . __FILE__;
?>```

Does the above produce any output ? (does it get printed ?)

**Comment by exstreme** [comment]
I've only one category
Create my custom template, but changing template on default give same results.

**Comment by ggppdk** [comment]
I cannot confirm this, probably you are using a different template than what you believe to be using

Here is our support forum
http://www.flexicontent.org/forum/

Please open a new thread there
