### ISSUE TITLE
field selectmultiple display only first value in fieldgroup

### ISSUE THREAD

**Issue by charlynancy54** [FLEXIcontent/flexicontent-cck#751]
When a field selectmultiple is in fieldgroup, only the first value of the selectmultiple field is displayed.

**Comment by ggppdk** [comment]
Please note

**that if field already had values**
and then you put it inside a fieldgroup

-- then this is normal

same applies for checkbox / checkboximage field

you will need to re-edit and readd any values

So did the field already had values ?

**Comment by charlynancy54** [comment]
No field already didn't have values.
It happens on a site that didn't have this dysfunction (before FLEXIcontent v3.2.0-dev-build)

**Comment by charlynancy54** [comment]
i believe that happened since end of june (i hope that could help you to find when something changed about this)

**Comment by ggppdk** [comment]
I cannot replicate this issue,
maybe it manifests with specific configuration

let's continue discussion in the flexicontent.org forum
please see my answer there

i will leave this open till i have a look at it at the site

**Comment by ggppdk** [comment]
I have found the issue our viewing layout needs to be updated due to the new structure of our indexable fields

all variables
`self::*`

must be made:
`static::*`

I have already made a fix, i will commit it soon
