### ISSUE TITLE
Post - update problem. No website and admin access

### ISSUE THREAD

**Issue by mekamak** [FLEXIcontent/flexicontent-cck#752]
Post - update problem. No website and admin access.
flexicontent-cck-3.2.x-stable
HTTP ERROR 500

**Comment by ggppdk** [comment]
If this is a live site

Then send me a PM with joomla admin access and FTP
by using PM in our forums:

www.flexicontent.org

**Comment by ggppdk** [comment]
Also,
if you installed github version before the commit that changed version number to 3.2.0-rc1

then the installation should have failed ... before that commit the installation process was broken due to the now removed extendedweblink field

**Comment by ggppdk** [comment]
@mekamak 
why have you closed this ?
is the issue resolved ?, if yes the please post back some feedback

**Comment by mekamak** [comment]
I made the previous version with backup
