### ISSUE TITLE
There is a problem when installing v3.2.0-rc1

### ISSUE THREAD

**Issue by mekamak** [FLEXIcontent/flexicontent-cck#754]
The new installation is still a problem.
flexicontent-cck-3.2.x-stable

**Comment by micker** [comment]
Can you explain more ?

Le 17 juil. 2017 à 15:07, à 15:07, Mehmet <notifications@github.com> a écrit:

**Comment by mekamak** [comment]
FlexiContent 3.2 stable, problem with installation, problem with updating.

**Comment by mekamak** [comment]
https://www.youtube.com/watch?v=YlGm3WxOPFI&feature=youtu.be

**Comment by ggppdk** [comment]
It looks like a php fatal error, eg a needed library missing, please go to global configuration and set error reporting to maximum and  joomla debug to on

**Comment by mekamak** [comment]
JROOT/language/tr-TR/tr-TR.lib_joomla.ini : error(s) in line(s) 360

**Comment by mekamak** [comment]
There is also a problem with the english installation

**Comment by ggppdk** [comment]
Without seeing the actual error message , there is little we can do

Please open a new issue in our forum
and send me a PM with super admin access via our forum

**Comment by mekamak** [comment]
Thank you so much. Was a new website. I'm setting it up again.
If you do a new installation with the latest version, you will also get an error.

**Comment by ggppdk** [comment]
We need the actual error to fix this
but i have found an issue in older PHP versions

please redownload the newer package and retest

**Comment by mekamak** [comment]
You solved the problem. Thank you.
