### ISSUE TITLE
Ux for field translation

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#759]
![20795232_1515608395164764_1162826632_o](https://user-images.githubusercontent.com/2539440/29242350-e01304c8-7f8b-11e7-9db5-b214dfed0b56.png)
À good Idea for translate field
New tab on field
On ordering to translate usefull value
Title
Label
Value
Etc
See screenshot

**Comment by ggppdk** [comment]
Now for the purpose of translating the "options" [label, value] pairs,
we are using Joomla language strings
- labels are language filtered if a parameter is enabled
- values are not language filtered

thinking 2 alternative
- either on clicking save in field configuration the strings will be added to Joomla language overrides file
- or create multiple links to Joomla language overrides management inside a modal, that will try to load the proper string and for every language

for both of the above options, we will need to do option parsing (label / value) in field configuration
also for both of the above options we will need to load the translations from the language overrides file the purpose of displaying them

**Comment by micker** [comment]
I think add string un override.ini id good Idea
