### ISSUE TITLE
Creating New User Group from FLEXIcontent shows empty (modal) window (area)

### ISSUE THREAD

**Issue by VelikiZliVuk** [FLEXIcontent/flexicontent-cck#761]
Creating New User Groups from Joomla interface works. 

Creating New User from FLEXIcontent works.
Editing existing users from FLEXIcontent works.
Editing existing Groups from FLEXIcontent end up in Joomla UI for editing user groups.

URL that gives empty area is 
/administrator/index.php?option=com_flexicontent&view=groups
while New Group button url in Dashboard is:
/administrator/index.php?option=com_flexicontent&task=groups.add

**Comment by ggppdk** [comment]
I have fixed it

please note
that usergroups manager inside FLEXIcontent, current has not real use

soon we will be adding per usergoup options, like author limitations
then it will be really useful
