### ISSUE TITLE
Feature Request: Get Flexi to work with ARK INLINE EDITOR

### ISSUE THREAD

**Issue by mikeh000** [FLEXIcontent/flexicontent-cck#77]
JCK Editor just released JCK7, that has inline editing: http://arkextensions.com/  However, they said to get it to work with flexicontent, you would need to talk to work together to accomplish this. Is this do-able? It works fine on com_content items, but not com_flexicontent items.

**Comment by mikeh000** [comment]
Ark editor is now compatible with construction kits for you to use.

**Comment by micker** [comment]
Do you have more infos ?

**Comment by mikeh000** [comment]
Yes, more info here is here in the changelog: http://arkextensions.com/changelogs/ark-editor/38-professional/254-v-1-4-rc3

**Comment by micker** [comment]
OK they speak about an API good new for later
