### ISSUE TITLE
striptagsandcut return ENT_NOQUOTES

### ISSUE THREAD

**Issue by AlainRnet** [FLEXIcontent/flexicontent-cck#770]
Hi.
I don't know if the problem is only with french text, but in FLEXI modules, ' disappear after passing through striptagsandcut function.
For example, "pour l'association" becomes "pour lassociation".

I try to modify ENT_QUOTES with ENT_NOQUOTES on line 1916 and it works well on my website.

https://github.com/FLEXIcontent/flexicontent-cck/blob/3c73e5c29d0487703189a07ca4142be80103bd38/site/classes/helpers/html.php#L1916

**Comment by ggppdk** [comment]
closing this as, we have fixed it
Now striptagsandcut() helper method will not to encode single quotes
only double quotes will be encoded
