### ISSUE TITLE
Unable to duplicate template

### ISSUE THREAD

**Issue by iamrobert** [FLEXIcontent/flexicontent-cck#772]
When duplicating a template following javascript error:

```
Uncaught TypeError: Cannot read property 'value' of undefined
    at Object.Joomla.isChecked (core.js?170322be5aad3a027d1e5854a9418172:1)
    at HTMLInputElement.onclick (index.php?option=com_flexicontent&view=templates:556)
```

![flexicontent-error](https://user-images.githubusercontent.com/8617673/30334139-5549081c-9811-11e7-87db-7ad78ea4e457.png)

v: Joomla! 3.7.5
v: FLEXIcontent 3.2.1.1   Release date: 2017-09-12

**Comment by ggppdk** [comment]
Ah i have not thought of that

those button were supposed not be clickable
they are suppored to be only "legend" aka explaining what the buttons do

- i will remove both the "btn" class from them and also their JS 

in order to duplicate , please click the button next to template, it works right ?

**Comment by iamrobert** [comment]
Thanks - I haven't used the default template for a while.

I'm not sure with 3.2.1.1 - I tried to create a new category and it didn't show - no js errors. I started from scratch Joomla install then FLEXIcontent - no articles/no categories. 

When I tried to recreate a new category it said it existed - but nothing showed. So - I deleted the install.

**Comment by ggppdk** [comment]
This sounds like a different problem,
if you believe that you found a bug with creating new categories when zero categories exist
then please open a new issue

**Comment by iamrobert** [comment]
Ok - will do!
