### ISSUE TITLE
Unable to create new Category

### ISSUE THREAD

**Issue by iamrobert** [FLEXIcontent/flexicontent-cck#773]
When trying to create a new category - it doesn't display:

https://www.youtube.com/watch?v=PtvBne5IMPc

Also in item the category doesn't exist:

![flexicontent-error](https://user-images.githubusercontent.com/8617673/30338972-0ce7d3dc-9820-11e7-9c57-be76e0ca0d99.png)

**Comment by ggppdk** [comment]
Fixed with 3303edd

Now new categories should be created properly

Also the categories that you tried to create but then they did not appear, will now appear as unpublished
