### ISSUE TITLE
Image with Rokbox

### ISSUE THREAD

**Issue by tevez15** [FLEXIcontent/flexicontent-cck#775]
Hi, with latest version, I want to use Rokbox on gallery image, but he dont put this code on image:

`data-rokbox-album="Album"`

Can you check? Thank you

**Comment by ggppdk** [comment]
Can you give more details of this ?
is it `data-rokbox-album="..."`  The group title of the images ?

**Comment by tevez15** [comment]
Hi,

Yes, I choose on field config, but dont add that.

I write the code on image field php file, and now work well

**Comment by ggppdk** [comment]
Ok so what would the group title be ?

the item title ?
or the label of the current image field ?

**Comment by tevez15** [comment]
item title

**Comment by ggppdk** [comment]
hhmm
we already  have a parameter for the grouping

it is used in all other gallery JS
Rokbox had no support

i see that they have added,
just the "grouping string" we have now is not suitable for display !
```php
	// Create a grouping name
	switch ($grouptype)
	{
		// This field only
		case 0: $group_name = 'fcview_'.$view.'_fcitem_'.$item->id.'_fcfield_'.$field->id; break;
		
		// All fields of the item
		case 1: $group_name = 'fcview_'.$view.'_fcitem_'.$item->id; break;
		
		// Per view:  all items of category page, or search page
		case 2: $group_name = 'fcview_'.$view; break;
		
		// No group
		default: $group_name = ''; break;
	}
```

We will need to calculate a $group_title that is suitable for display too
will do

**Comment by ggppdk** [comment]
Ok the group name is not shown so we can use same index as 
- in all other gallery

aka we can use `$group_name`

```php
	$group_str = $group_name ? 'data-rokbox-album="'.$group_name.'"' : '';
```

Tested and added support of the above with commit 4a33ede

**Comment by tevez15** [comment]
Thank you very much my friend. :)
