### ISSUE TITLE
Issues on categories and state with the batch mode 

### ISSUE THREAD

**Issue by vistamedia** [FLEXIcontent/flexicontent-cck#777]
The following issues are on FLEXIcontent 3.2.1.2: 

1. It's not possible to add secondary categories in batch mode.
2. It's not possible to use the element "Do not change" on the state selector. (instead it will change all the items with the default value "Unpublished")

![bug-batch-mode](https://user-images.githubusercontent.com/9335926/30475494-4f3ecd56-9a07-11e7-8ade-6182cc9c33d3.jpg)

**Comment by ggppdk** [comment]
I think these issues were introduced due to effort to better support the import manager doing 
- create
- update
- create / update

should be easy to fix

**Comment by ggppdk** [comment]
Fixed both with

You can use install from URL to test:
https://github.com/FLEXIcontent/flexicontent-cck/archive/3.2.x-stable.zip

**Comment by vistamedia** [comment]
Awesome ;)
