### ISSUE TITLE
FLexicontent Search Menu Item Parameter 'default (word) combination' is ignored when hidden

### ISSUE THREAD

**Issue by ldoliv** [FLEXIcontent/flexicontent-cck#778]
Hello,

I'm using FLEXIcontent 3.2.1.2,

I had reported this issue for the filtering module, it seems the same issue occurs for the search menu item.
![image](https://user-images.githubusercontent.com/6535818/30596007-cbe074a4-9d4a-11e7-82a5-86d546c39c61.png)
"Default combination" isn't applied when "Word Combination" is set to hide, only works when set to show.

I noticed when it is set to hide it doesn't pass the "p" variable in the url.

Also the FLEXIcontent - Search module, doesn't have this option, so what is the default word combination when no p variable is passed ? shouldn't the search module have these options as well ?

**Comment by ggppdk** [comment]
Hello, the fix we made for
#768  ([Filtering module] Parameter 'default (word) combination' is ignored when hidden)

should have fixed this case too

So can you test if issue is already fixed ?
Install via URL (in a test site):
https://github.com/FLEXIcontent/flexicontent-cck/archive/3.2.x-stable.zip

**Comment by ldoliv** [comment]
Just installed 3.2.x-stable version, and issue is still there.
It is fixed for the category view with text search, but not for search menu item.
It does not pass the "p" parameter in the url when hidden.

**Comment by ggppdk** [comment]
Closing this , as we fixed the search view case too, with commit 4d639e8
(Fixed word combination setting in search menu item being ignored, when word combination selector is configured not to be shown)
