### ISSUE TITLE
Using an image field in the item manager

### ISSUE THREAD

**Issue by vistamedia** [FLEXIcontent/flexicontent-cck#780]
Joomla! v3.8
FLEXIcontent v3.2.1.3
(all previous versions were affected too)

When using an image field in the item manager it generates a wrong link to the image...

![item-manager-1](https://user-images.githubusercontent.com/9335926/30683555-2a041950-9eae-11e7-9041-75be13dc5a5d.jpg)
![item-manager-2](https://user-images.githubusercontent.com/9335926/30683569-34111c90-9eae-11e7-9b69-ca5814b5312c.jpg)

Instead there are 3 possibilities:

1. put the correct link and open the image (with or without lightbox)
2. remove the link
3. link to edit the item

**Comment by ggppdk** [comment]
we need to put a check if field is display in backend side
will fix

**Comment by ggppdk** [comment]
This has been fixed with 9bd9258
