### ISSUE TITLE
Display type for the filter of "state" field has no effect

### ISSUE THREAD

**Issue by vistamedia** [FLEXIcontent/flexicontent-cck#782]
Joomla! v3.8
FLEXIcontent v3.2.1.3
(all previous versions were affected too)

Whatever the configuration you choose, the state filter always renders a dropdown list. 
It would also be awesome to have the item count...

![state-filter](https://user-images.githubusercontent.com/9335926/30740345-e3729ba4-9f90-11e7-8420-2c367f5ab656.jpg)

**Comment by ggppdk** [comment]
For this 'state' field the parameter for customizing appearance of the filter were added
- but the code to use them was never added

thus the indeed the filter of the field will always display as drop down list

**Comment by vistamedia** [comment]
Nice, it works for me ;)
