### ISSUE TITLE
In category views the orderby is reset when using pagination

### ISSUE THREAD

**Issue by vistamedia** [FLEXIcontent/flexicontent-cck#785]
In category views the orderby parameter does not stay in the query string when using pagination. It makes the usage of faceted navigation very difficult with large collections of items...

![orderby](https://user-images.githubusercontent.com/9335926/30742480-8a737a92-9f99-11e7-92a9-8e28738c5d42.jpg)

**Comment by ggppdk** [comment]
This may depend on some specific configuration
I will test at the specific website, as i can not reproduce it locally

**Comment by ggppdk** [comment]
Bug only occurs only 
- if home page menu item points exactly to the specific category

I tested with other categories that have or do no have specific menu items and it is working for them

**Comment by vistamedia** [comment]
Wow, that was tricky and it's good to know ;)
