### ISSUE TITLE
Issues with using both FlexiContent and Joomla's native Custom Fields

### ISSUE THREAD

**Issue by woluweb** [FLEXIcontent/flexicontent-cck#789]
Hi everybody !

I wanted to share some big problems/conflicts on sites having both FlexiContent and Joomla's native Custom Fields.
 
Here are some examples of surprising issues.
I had created two new Categories for Articles : _Documentaires_ and _Lieux_.
They were in Blog view in front-end. Everything working fine.
 
Then, when I click on the title of any of those articles, first big issue : the site would ask me to log in ! (while everything is public regarding those : articles, fields, menu, everything).
 
After that, I logged in, but instead of having the normal view, I had two issues :
•	Description text is not displayed 
•	The Custom Field « galerie » is shown, while it is NOT assigned to that Category
 
Eventually, in all my attemps to have a workaround, I disabled the following plugin
System - Flexisystem, core tasks
 
That solved temporarily the 3 issues above.
But of course that introduces side-effects
1.	on the page of the site displaying Flexicontent : now, when I filter on the Flexicontent page, the page reloads and shows the right content… but the Filter Module then disappears
2.	in the backend, Flexi asks to enable all the plugins of course (and do other things), so that I can’t access the items
 
So, what can be done about all that ?
Ideally, one would want to keep the Flexisystem, core tasks enabled of course, but without having the conflicts I identified above.
 
Txs a lot.

This is just feedback I share with you because I do use and appreciate Flexicontent.
(but probably not many people have used Custom Fields yet, at least together Flexicontent, to report those issues to you)

**Comment by ggppdk** [comment]
In current version it is best to use only FLEXIcontent field for your items

The work on supporting J3.7+ custom fields is not 100% finished
It is good that you have compiled a list of issues that need to addressed

**Comment by ggppdk** [comment]
Will address these during october

**Comment by woluweb** [comment]
Txs a lot Georgios,
Your commitment is appreciated :)

I also spotted another little issue (less annoying though)
Now that there are Native Joomla Custom Fields, when you edit an article an extra Tab comes, : « Type : Article » (with no field in it).
So I guess that extra Tab should not come there as it is empty anyway, as it confuses the end users.

Here is the html of that tab : 
<li class=""><a href="#attrib-fcfields" data-toggle="tab">Type : Article</a></li>

Voilà. Now you know all what I have noticed so far about "conflicts".
Txs a lot & see you soon

**Comment by ggppdk** [comment]
> Now that there are Native Joomla Custom Fields, when you edit an article an extra Tab comes, : « Type : Article » (with no field in it).

Was supposed to make a decision for this

The "type" TAB with zero fields,
was supposed to be replaced with "select type" , that will be shown only if explicitely enabled in FC component configuration
