### ISSUE TITLE
Send to Reviewers: Available in FLEXIcontent PRO

### ISSUE THREAD

**Issue by lyquix-owner** [FLEXIcontent/flexicontent-cck#800]
Hello guys
I am testing the "Send to Reviewers" function and I get a message: "Available in FLEXIcontent PRO version"
I was unaware of a FLEXIcontent PRO... where can I buy it?

**Comment by ggppdk** [comment]
This feature is finished, but others are not

Besides this it is meant to have endless scroll (with good integration) and reviews
and a few other features

Please wait

**Comment by lyquix-owner** [comment]
Oh, ok... thank you
