### ISSUE TITLE
Allow direct edit of item form layout (as an alternative to parameter-based layout)

### ISSUE THREAD

**Issue by ggppdk** [FLEXIcontent/flexicontent-cck#803]
Currenlty we are creating the item form layout via parameters

It will be more flexible to allow advance users to edit the layout directly
- this will be an alternative to using the parameters

**Comment by micker** [comment]
yes good Idea

**Comment by micker** [comment]
maybe think about a global value like {auto fields} to render all Custom field in one check
easy to Custom Joomla loading and flexicontent loading
