### ISSUE TITLE
FLEXIContent 3.2.1.7 and Falang v2.9.2   If I use All tab content not Show

### ISSUE THREAD

**Issue by lungkao** [FLEXIcontent/flexicontent-cck#805]
FLEXIContent 3.2.1.7 and Falang v2.9.2   If I use All tab content not Show

**Comment by irbian** [comment]
Also happens with Falang 1.4.5

**Comment by ggppdk** [comment]
Yes i have noticed

**Comment by irbian** [comment]
would you like to make an estimate? this makes impossible to add new content, I would like to know if installing a older version is needed in the meantime

**Comment by ggppdk** [comment]
> would you like to make an estimate? this makes impossible to add new content, I would like to know if installing a older version is needed in the meantime

why impossible ?
You can still use Falang interface to add translations

**Comment by irbian** [comment]
Maybe Im missing something. Now when I open ther article view, whatever I put on the *all* field disappears on frontend. For example, the title. What is your approach? Add it on my label field?

**Comment by ggppdk** [comment]
I meant in backend

**Comment by irbian** [comment]
I have to do more testing, looks like the module affected is the universal module flexicontent but this dont look like a problem for the article view...

Have to check it

If there is something I can do for help, let me know

**Comment by irbian** [comment]
Nevermind, the problem looks like it appears when saving, because old content looks ok

Anyway, almost all the content in our page goes to "all", because thats our flow of work, putting our text on the "all" section and translate if needed. It´s not that I can´t add translations via the interface, it´s that simple editing an article is broken

Maybe I´m not explaining myself well, have you been able to reproduce it?

**Comment by irbian** [comment]
ok, I can see how on the falang database is storing the empty translations. That means that later falan will show me this empty info instead of the default

**Comment by irbian** [comment]
Got it!

On this commit, 
https://github.com/FLEXIcontent/flexicontent-cck/commit/bba9a20a181a7eb655be37d2d8a84b5f4b4d92f9

At this point exactly, the condition changes, from "!strlen" to "!isset || !is_string"
![image](https://user-images.githubusercontent.com/3071767/32433713-d397047a-c2d3-11e7-88b6-fd87a4d3a19f.png)

This means that it will store empty translations,  disabling the default values

Would you be so kind to release a version with this fix? :D It´s important for us

**Comment by irbian** [comment]
After modifying my code as concept, it is still storing the alias translations instead of storing them as 0, don´t know if this is intended

**Comment by irbian** [comment]
did you were able to check this? is enough with my fix? are the alias stored on the translations table  intended?

**Comment by ggppdk** [comment]
Hi this is next issue i will check, will try to do today , otherwise tomorrow evening

**Comment by ggppdk** [comment]
I have made a fix
you can test using install from URL (in Joomla extension manager)
https://github.com/FLEXIcontent/flexicontent-cck/archive/3.2.1.x-stable.zip

For testing
- you will either need to edit and re-save an item and then view it frontend to check if translation is missing for an item in e.g. description, the 'All' language translation should be shown

For correcting DB
- If you have edited many items and saved empty values in falang content table , you will need to execute in e.g. phpmyadmin
```sql
DELETE FROM `DB_PREFIX_falang_content`  
WHERE  value = ''
```

**Comment by irbian** [comment]
I tried your fix, works ok :)

I had another question earlier, when I create an article, on the falang_content table I can see how the alias is stored once for each alias. Is this intended? Is on your side this or is handled by falang?

Regards

**Comment by irbian** [comment]
Ok, now I see how the language code is stored after the value and that is indeed working properly

Thanks for your help :D

**Comment by ggppdk** [comment]
Ok thanks for testing
