### ISSUE TITLE
Q: Should jQuery UI more resemble Joomla ISIS Template?

### ISSUE THREAD

**Issue by iamrobert** [FLEXIcontent/flexicontent-cck#808]
Does this look more integrated?

http://jqueryui.com/themeroller/#!zThemeParams=5d00000100f905000000000000003d8888d844329a8dfe02723de3e57025317821810f9d630423a0d88a0e1983112c135eca36423191882fa6d78873bce00ee53be6bc16530963bb283038e47ed74b4aa36ca067e282a88e235a651a944a122e0c1d15bc23dbb011d897e79993dcbdbe05af31f160f08600f2d06d74cb829afbb6765576c808f24c24316ced2a9eb4789c81ffa11e94e1d1e9f7bf32debb2062728fc57d6a9ad5e7a857d9022465702234256d027a776c93bdede06c1e31db8943c68a2cf2a4d402e8b1af94adf48c08f24178620ea9d4e6b242c6f582a5e4aa075274c1fad6eac5547b78fbca3e37eff0eab0c603366b1ff98f8ca31fdee92a21f0fd87e36ee93dc1bdb60740593d90915d72e8807acc452e10700508d578f6581d8167139b56c6eb28c9b8ad2067c439d28d28f26f5fb8a87894b49a4903556596b24af766a4b7bc09eb644ed41b0311e6a3b445173db03999b63e68d3b175bb9bf86b4b6bda9b6e9b92721d66927fc8224b0cb6d5fccdc455b464993b5c7e637e24698ba0bb87b5ac632a49b4331a8521f619a09de10aa0b8f917b73031c9de59af977b9f6700f654df17260f96836820ef745943474713a7257cd32923f3b30e0b42f6cd8ad039fe1f73501a25921c7af226189bd5a26be176f54d88b1fdf9ea79

**Comment by lyquix-owner** [comment]
My suggestion is to use Joomla isis styles when possible, instead of jQuery UI

For example, instead of using this lightbox using when creating new items, or when viewing files
![](https://i.imgur.com/klYQJoN.png)

It should be:
![](https://i.imgur.com/IwZScyO.png)

Instead of using these tabs:
![](https://i.imgur.com/SX4BhWi.png)

they should be like these:
![](https://i.imgur.com/K7rJemH.png)

It's only a suggestion

**Comment by micker** [comment]
Intersting Idea... Difficult to choose ... With j4 évolution

**Comment by iamrobert** [comment]
Here's my new administrator template for FLEXIcontent that's more bootstrappy:

https://www.dropbox.com/s/407ez7el8iikd8y/iamrobert.zip?dl=0&m=

Basically removed all tables, and used bootstrap. However - tabber still remains in parts, and I haven't touched jQuery UI. 

**Item:**
![item](https://user-images.githubusercontent.com/8617673/32478269-c3eead7a-c3be-11e7-8c0a-ba5feff51a2f.png)

**Items:**
![items](https://user-images.githubusercontent.com/8617673/32478271-c4eeaa4a-c3be-11e7-9f4e-2b94ad387101.png)

**Dashboard:**
![dashboard](https://user-images.githubusercontent.com/8617673/32478272-c613fa74-c3be-11e7-8a8b-8a6c6d42d271.png)

You could copy html/com_flexicontent to ISIS template and see how it goes.

**Comment by ggppdk** [comment]
With commit 04149cd
we added new option in Advanced TAB of component configuration to select jQuery UI theme, currently 2 themes only but we can add more of them
