### ISSUE TITLE
Permissions tab is wrongly centered

### ISSUE THREAD

**Issue by irbian** [FLEXIcontent/flexicontent-cck#813]
The culprit 

https://github.com/FLEXIcontent/flexicontent-cck/blob/master/site/assets/less/flexi_shared_rtl.less#L2116

https://github.com/FLEXIcontent/flexicontent-cck/blob/master/site/assets/less/flexi_shared.less#L2116

**Comment by ggppdk** [comment]
Yes i see the effect, will remove or replace this CSS
