### ISSUE TITLE
Image Field in groupfield issue

### ISSUE THREAD

**Issue by ldoliv** [FLEXIcontent/flexicontent-cck#823]
Hello,

I'm using FLEXIcontent 3.2.1.9-dev build.

I have **2 image fields in a fieldgroup**. When I upload an image on the **second image field**, it places the image on the **first image fileld**.

**I tested this and this bug happens on all releases after 3.1.1**

**Start fresh:**

![image](https://user-images.githubusercontent.com/6535818/34561794-95c639c4-f143-11e7-93ba-185248c64f1b.png)

**After upload:**

![image](https://user-images.githubusercontent.com/6535818/34561814-af78e524-f143-11e7-92e5-d73347647303.png)

**After saving the article:**

![image](https://user-images.githubusercontent.com/6535818/34561867-d8726d74-f143-11e7-9432-2f178e092e4b.png)

**Comment by ggppdk** [comment]
What is the image source of the 2 fields
are they both in "Folder" mode, or both in "DB-reusable" mode?

**Comment by ggppdk** [comment]
Fixed please test
