### ISSUE TITLE
' on tag (import and search

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#829]
We have a problem on ' with tag
relevant
http://mail.flexicontent.org/forum/9-support/55127-problemes-apres-importation-de-tags-avec-autocompletion-et-apostrophes.html

**Comment by 2CPRESTA** [comment]
Hello what's new about this problem ?

**Comment by ggppdk** [comment]
hhmm, will have a look to fix this too

About tags, note, that currently, there is work being done that is related tags

- to map and sync FLEXIcontent tags to respective Joomla tags

1. (done) item form mapping and syncing, (todo) respect language setting
2. (todo) tags manager, map to respective Joomla tag and open it in modal edit window
3. (todo) use Joomla tags data in tagged items view

**Comment by ggppdk** [comment]
Fixed issue quotes inside tag names with 8050577
