### ISSUE TITLE
"Reset filter" don´t autosend

### ISSUE THREAD

**Issue by irbian** [FLEXIcontent/flexicontent-cck#83]
What steps will reproduce the problem?
1. On category view, with autosend on, "Reset filter" don´t autosend

What version of the product are you using? On what operating system?

r1932
Please provide any additional information below.

Actually this behaviour could be interesting if can be configurable
http://flexicontent.org/forum/index.php?f=21&t=8331&rb_v=viewtopic

**Comment by ggppdk** [comment]
Changed behavior here: 0e6c167
