### ISSUE TITLE
Exclude currently edited item from the items list of relation field

### ISSUE THREAD

**Issue by ggppdk** [FLEXIcontent/flexicontent-cck#830]
Relevant forum thread:
http://www.flexicontent.org/forum/20-general-support/56456-exclude-itself-item-in-relation-field.html

**Comment by lipatovroman** [comment]
Also, highlight already added items or remove them from list and change behavior of dropdown menu.

**Comment by ggppdk** [comment]
Done both of then with 4343c50
- Current item is now not selectable
- Already selected items appear as disabled inside the (per category) items selector
