### ISSUE TITLE
pagination with sh404sef Version4.13 issue

### ISSUE THREAD

**Issue by charlynancy54** [FLEXIcontent/flexicontent-cck#831]
The issue comme from [FLEXIcontent forum](http://www.flexicontent.org/forum/21-troubleshooting/56439-pagination-with-sh404sef-not-working.html) 
Experiencing pagination problems with sh404sef Version4.13

Here is the answer from sh404SEF : 

> I have done as I said, downloaded a copy of the site and debugged locally. As expected, this is a problem in FlexiContent, which comes from assuming the Joomla SEF pagination format ie /xxxx?start=20 or /xxxx?start=40.
They cannot handle something like /xxxxx/page-2.

> The bug was hidden by older versions of sh404SEF, as we had made a workaround for those extensions. In last version, we remove the workaround as we thought all extensions should have been fixed by now, but apparently even large extensions such as Flexi have not yet started to use the correct Joomla API.

> Here are the details:

> In the file /components/com_flexicontent/controller.php, at line 1151, there is this code:

`// Add any existing URL variables (=submitted via GET), ... we only need variable names, (values are ignored)
foreach($_GET as $_varname => $_ignore) $safeurlparams[$_varname] = 'STRING';`

> A short-term fix can be:

`// Add any existing URL variables (=submitted via GET), ... we only need variable names, (values are ignored)
// foreach($_GET as $_varname => $_ignore) $safeurlparams[$_varname] = 'STRING';
$getVars = $this->input->getArray();
foreach($getVars as $_varname => $_ignore) $safeurlparams[$_varname] = 'STRING';`

> I would suggest you report this to the FlexiContent team and suggest this change, or maybe they can workout something else as needed.

**Comment by ggppdk** [comment]
I ll test

**Comment by ggppdk** [comment]
https://github.com/FLEXIcontent/flexicontent-cck/commit/9694621c80f3eeafc8cb735569a6bb57dd6ff77b

Fixed 2 issues with SH404SEF
- (current issue) pages not changing when caching is enabled
- and also fixed frontend per-page (limit) selector being ignored

Fix included in v3.2.1.10
