### ISSUE TITLE
How to trigger the "binding" of articles created via Joomla native Article Manager

### ISSUE THREAD

**Issue by woluweb** [FLEXIcontent/flexicontent-cck#834]
Hi,
On a website where Flexi is used, but also Joomla's native Article Manager, I face an issue
(I have already have a vocal call with Yannick about this the other day)

Here is what happens : 
- articles are created using Joomla's native article manager
- but doing so the "bind" is not triggered
- if you go to Flexi Item Manager, the interface suggests to "bind" by clicking on a button

Actually, the symptons are now the following : if the "bind" is not done then
1. opening such an Article in front-end results in a login-screen
2. and even if you log in, if there is an override (which I had bc of Custom Fields), the override layout is ignored (and Flexi layout is used)

As a workaround, I had discovered that disabling "Flexisystem, Core Tasks" would at first sight seem to solve 1. and 2. But then there are side-effects on the Flexi pages, for example the pages using the front-end filter module would not work correctly any more of course.

So the question is : would it be possible somehow to trigger the binding automatically 
  - via a CRON for example ?
  - or with a hook or so that could be triggered upon Saving native Articles ?

Txs

**Comment by ggppdk** [comment]
Hi
You should disable system core tasks plugin only temporarily if emergency, e.g. If it gets broken

Actually the hook to update flexicontent item data during article form save is already implemeny
And it exactly inside this plugin,

What you need to do is to go to component setting and inside item form type select a type for new articles , aka with joomla article form and save settings

Then relogin and make sure everything is bind and then try to create a new joomla article

**Comment by woluweb** [comment]
Hi Georgios,
Txs for the quick reaction :)

With Yannick, we had already been to Component Settings in order to set Item Form to Joomla Article.

But I have just tried and it does not work.

2 things to be precise (knowing that in Flexisystem Core Tasks I have set Super User etc to be allowed to use the Joomla Native Article Manager) : 
- from back-end, I create a new article with Joomla Native Article Manager... and still it is not accessible for Public from front-end (asking to log ing)
- from the front-end, I have something strange as well when I want to create a new article (from List page, with the button New)
  - if "Core Tasks" is disabled, then of course Joomla Native Article Manager
  - but if "Core Tasks" is enabled then
     - editing an article opens the  Joomla Native Article Manager
     - but creating New article opens some Flexi Article form (which does not display my Custom Fields btw)

If you wish, I can share my screen with you one of the coming days, so that you can quickly see for yourself...

Txs

**Comment by ggppdk** [comment]
Hello

fixed with ae378ee
you can use install via URL, in a test site to test it
https://github.com/FLEXIcontent/flexicontent-cck/archive/3.2.1.x-stable.zip

**Comment by woluweb** [comment]
Txs Georgios,

Issue 1 of my last message (from back-end) is indeed fixed.

But Issue 2 is still there :
"from the front-end, I have something strange as well when I want to create a new article (from List page, with the button New" (see detail above)
Screenshot : https://screenpresso.com/=KeR8f

**Comment by woluweb** [comment]
ohooo.
Now I see that the filter module does not filter anything anymore (just tested with the dev version you just sent. I had not checked before/after the previous update made last week).
See it for yourself on
goo.gl/tmfYau
Any idea ?

**Comment by ggppdk** [comment]
In frontend you are presented with FLEXIcontent item form
because if you are in FLEXIcontent category view
and you click "Add" then you will get FLEXIcontent item form

about filtering module i will check it

**Comment by woluweb** [comment]
Front-end : 
- it is a Joomla Category View, not a Flexi Category View
- meanwhile I have also tested with a "create article" menu link. Same result : Flexi Form comes up

Txs & see you soon :)

**Comment by ggppdk** [comment]
Tested with filtering module and it is working 

about new article form  ...
- i see that last commit indeed it forces the redirection to

for existing items, this is straighforward, 
it is simple, we use the type setting of allowing or not allowing to 
view and edit via Joomla article view and Joomla article form

but for new article links , the code to decide might is a little more tricky, will fix it

**Comment by woluweb** [comment]
Txs Georgios.
It is a pleasure to see how FlexiContent (you) is reactive :)
I am happy to contribute a little by reporting ;)

For the filter, maybe it was a cache issue. I will test it later on

**Comment by ggppdk** [comment]
About filtering module 
since the filering module is not related to this issue

please open (after you test a little) a new thread at our forum 
and then if needed will open a new issue here

**Comment by ggppdk** [comment]
Hi,
added a compoent parameter 
- to allow or not allow the -new- Joomla article form in frontend

the default setting is to allow it

**Comment by woluweb** [comment]
I will be happy to test, but how do I get the right version for that ?
Download button on https://github.com/FLEXIcontent/flexicontent-cck ?

**Comment by woluweb** [comment]
oops, one caveat though : 
1. when creating a new article from backend, the binding is OK
2. but when creating a new article from front-end, the form is now OK but the binding does not happen...

**Comment by ggppdk** [comment]
hhmm we have code to prevent 
... changng item type change in frontend for **existing items**

but when creating Joomla article form , the item is created and then it gets assigned to a type
i will make a fix for this too

thanks for feedback, allowing Joomla article form is a feature that had been requested quite a few times

**Comment by ggppdk** [comment]
Fixed FC item type binding 
also in Joomla **frontend** article form 
with 7eef140
