### ISSUE TITLE
Sql error filter by relational field category view

### ISSUE THREAD

**Issue by ldoliv** [FLEXIcontent/flexicontent-cck#836]
Hello, I'm using the 3.2.1.x-stable release.

In category view when i filter by relational field I get this error:

1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'JOIN #__flexicontent_fields_item_relations AS rival ON rival.item_id=relv.ite' at line 1

**Comment by ggppdk** [comment]
The If above probably needs a negation !

`if ($ri_field_id)`
probably needs to be
`if (!$ri_field_id)`

**Comment by ggppdk** [comment]
I have made a fix here: 1c9cec5
please test using install via URL in extension manager:
https://github.com/FLEXIcontent/flexicontent-cck/archive/3.2.1.x-stable.zip

**Comment by ggppdk** [comment]
This should have fixed, please see my previous message for testing

**Comment by ggppdk** [comment]
@ldoliv 
please confirm that fix is working, pleae see my previous message

**Comment by ldoliv** [comment]
Yes it's working, thank you.
