### ISSUE TITLE
No items displayed after upgrade from 2.x to 3.x

### ISSUE THREAD

**Issue by acs-ferreira** [FLEXIcontent/flexicontent-cck#837]
After upgrade from 2.2.x to latest 3.2.1.10, no Items are displayed.

All articles work fine at the front, but nothing at the back.

## Before upgrade (prod):
![image](https://user-images.githubusercontent.com/12234510/35887417-7e288298-0b94-11e8-8b08-342e2c7ae7e9.png)

![image](https://user-images.githubusercontent.com/12234510/35887460-a4274268-0b94-11e8-83d3-f0792d9a5009.png)

## After upgrade (staging):
![image](https://user-images.githubusercontent.com/12234510/35887474-ac85ecb6-0b94-11e8-8277-a89e23c66afa.png)

![image](https://user-images.githubusercontent.com/12234510/35887499-bc5f470e-0b94-11e8-9e25-2b46778cf563.png)

Under Joomla 3.8.5, PHP 5.6, MySQL 5.5.

**Comment by ggppdk** [comment]
Did you do a full cache clean ?
Did you try to relogin and visit FLEXIcontent backend dashboard ?

**Comment by ggppdk** [comment]
Please open a new thread in our forum,
it is better please to discuss things, before opening issues here
http://www.flexicontent.org/forum.html

**Comment by ggppdk** [comment]
The default order that you have in component settings at
"Backend Managers" TAB / "Items Manager" TAB

**is "per category order"**

- but when using the above order you need to select a category before any items are displayed !

Reconfigure the parameter for default order in component settings to be "Item ID" descending, which is default for new installations, or also using any other ordering, will show all items

there is no bug
