### ISSUE TITLE
Enable / implement extra displays for the categories field filter

### ISSUE THREAD

**Issue by ldoliv** [FLEXIcontent/flexicontent-cck#838]
I would like to request a feature.

The feature is for the **category field**, to add the option to display the filter as "Checkboxes (multi)".

We really need this feature.

![image](https://user-images.githubusercontent.com/6535818/35908428-86e52694-0be8-11e8-846e-ab0349dc097c.png)

**Comment by ggppdk** [comment]
Hhhm
this is almost implemeneted,
we can do a little more work to enabled it

but note that when filtering by more than just the 
- immediatre subcategories, aka having categories that are nested into multiple levels then we will force drop-down select, right ?

**Comment by ldoliv** [comment]
Yes I agree

**Comment by ggppdk** [comment]
Implemented with 34f82bf

Added filter displays as
- checkboxes
- radio

The drop-down select display will be automatically forced if having more than 1 parents, e.g. in multi-category view

So you can use this feature only in single category view
