### ISSUE TITLE
Is FlexiContent CSS / JS optimized for fast website load ?

### ISSUE THREAD

**Issue by jimiero** [FLEXIcontent/flexicontent-cck#842]
Hello,

Sorry if I may be wrong, but I just looked on the demo website you mentioned in your website homepage: https://com3elles.biz/jdays2017/en/

When I check that website page source I see a huge amount of javascript/css files loaded, example:

CSS:

`<link href="/jdays2017/components/com_flexicontent/librairies/jquery/css/ui-lightness/jquery-ui-1.9.2.css" rel="stylesheet" type="text/css" />

<link href="/jdays2017/components/com_flexicontent/assets/css/flexicontent.css?971e6381ed89759f3e3584da4d5d4908" rel="stylesheet" type="text/css" /

<link href="/jdays2017/components/com_flexicontent/librairies/select2/select2.css?3.5.4" rel="stylesheet" type="text/css" />
 <link href="/jdays2017/components/com_flexicontent/assets/css/fcvote.css?971e6381ed89759f3e3584da4d5d4908" rel="stylesheet" type="text/css" />
 <link href="/jdays2017/components/com_flexicontent/templates/default/css/item.css" rel="stylesheet" type="text/css" />
 <link href="/jdays2017/components/com_flexicontent/assets/css/tabber.css?971e6381ed89759f3e3584da4d5d4908" rel="stylesheet" type="text/css" />

<link href="/jdays2017/components/com_flexicontent/librairies/fancybox/source/jquery.fancybox.css" rel="stylesheet" type="text/css" />
  <link href="/jdays2017/components/com_flexicontent/librairies/fancybox/source/helpers/jquery.fancybox-buttons.css" rel="stylesheet" type="text/css" />
 <link href="/jdays2017/components/com_flexicontent/librairies/fancybox/source/helpers/jquery.fancybox-thumbs.css" rel="stylesheet" type="text/css" />
 <link href="/jdays2017/components/com_flexicontent/librairies/fcxSlide/fcxSlide.css?971e6381ed89759f3e3584da4d5d4908" rel="stylesheet" type="text/css" />
 <link href="/jdays2017/components/com_flexicontent/librairies/mCSB/jquery.mCustomScrollbar.css" rel="stylesheet" type="text/css" />
  <link href="/jdays2017/components/com_flexicontent/librairies/nouislider/nouislider.min.css" rel="stylesheet" type="text/css" />
  <link href="/jdays2017/components/com_flexicontent/assets/css/flexi_filters.css?971e6381ed89759f3e3584da4d5d4908" rel="stylesheet" type="text/css" />`

Javascript:

`

<script src="/jdays2017/components/com_flexicontent/librairies/jquery/js/jquery-ui/jquery.ui.menu.min.js" type="text/javascript"></script>

  | <script src="/jdays2017/components/com_flexicontent/librairies/jquery/js/jquery-ui/jquery.ui.autocomplete.min.js" type="text/javascript"></script>
  | <script src="/jdays2017/components/com_flexicontent/librairies/jquery/js/jquery-ui/jquery.ui.progressbar.min.js" type="text/javascript"></script>
  | <script src="/jdays2017/components/com_flexicontent/assets/js/flexi-lib.js?971e6381ed89759f3e3584da4d5d4908" type="text/javascript"></script>
  | <script src="/jdays2017/components/com_flexicontent/librairies/select2/select2.min.js?3.5.4" type="text/javascript"></script>
  | <script src="/jdays2017/components/com_flexicontent/librairies/select2/select2.sortable.js?3.5.4" type="text/javascript"></script>
  | <script src="/jdays2017/components/com_flexicontent/assets/js/tmpl-common.js?971e6381ed89759f3e3584da4d5d4908" type="text/javascript"></script>
  | <script src="/jdays2017/components/com_flexicontent/assets/js/jquery-easing.js?971e6381ed89759f3e3584da4d5d4908" type="text/javascript"></script>
  | <script src="/jdays2017/components/com_flexicontent/assets/js/fcvote.js?971e6381ed89759f3e3584da4d5d4908" type="text/javascript"></script>
  | <script src="/jdays2017/components/com_flexicontent/assets/js/fcfav.js?971e6381ed89759f3e3584da4d5d4908" type="text/javascript"></script>
  | <script src="/jdays2017/components/com_flexicontent/assets/js/tabber-minimized.js?971e6381ed89759f3e3584da4d5d4908" type="text/javascript"></script>

<script src="/jdays2017/components/com_flexicontent/librairies/fancybox/lib/jquery.mousewheel-3.0.6.pack.js" type="text/javascript"></script>

  | <script src="/jdays2017/components/com_flexicontent/librairies/fancybox/source/jquery.fancybox.pack.js" type="text/javascript"></script>
  | <script src="/jdays2017/components/com_flexicontent/librairies/fancybox/source/helpers/jquery.fancybox-buttons.js" type="text/javascript"></script>
  | <script src="/jdays2017/components/com_flexicontent/librairies/fancybox/source/helpers/jquery.fancybox-media.js" type="text/javascript"></script>
  | <script src="/jdays2017/components/com_flexicontent/librairies/fancybox/source/helpers/jquery.fancybox-thumbs.js" type="text/javascript"></script>
  | <script src="/jdays2017/components/com_flexicontent/librairies/fcxSlide/class.fcxSlide.js?971e6381ed89759f3e3584da4d5d4908" type="text/javascript"></script>
  | <script src="/jdays2017/components/com_flexicontent/librairies/mCSB/jquery.mCustomScrollbar.min.js" type="text/javascript"></script>
  | <script src="/jdays2017/components/com_flexicontent/librairies/imagesLoaded/imagesloaded.pkgd.min.js" type="text/javascript"></script>
  | <script src="/jdays2017/components/com_flexicontent/librairies/nouislider/nouislider.min.js" type="text/javascript"></script>

`

Plus other inline javascript code.

This is the best result I could get reported for that website:

![screen shot 2018-02-22 at 11 24 20 am](https://user-images.githubusercontent.com/3626762/36530171-0b835bec-17c3-11e8-9352-fced36f772a8.png)

Are there any plans for improving this in the near future?

**Comment by ggppdk** [comment]
You are speaking of the very first web-site visit, in regards

to JS  / CSS, 
- their size and number is not much,
- also about JS the trend now is to split Javascript to multiple different files
- also an administrator can use a tool to combine and compress them

Also regarding large or very large websites the page creation is very fast  (i mean server execution time)

Finaly the job to combine JS / CSS is left to website administrator

**Comment by jimiero** [comment]
Hi @ggppdk thanks for answering, one more question, are those javascript files loaded all the time all over the website or are they loaded only on the pages where they are in need?

**Comment by charlynancy54** [comment]
Hi,
i used JCHoptimize with Flexi and the score is generaly A (i obtain B with adsense advertising)
That is test result of a site with 10 000 items and 800 Categories
JCH rock with Flexi

**Comment by micker** [comment]
maybe we can do a article in faq with preset value ? @lipatovroman and @charlynancy54
