### ISSUE TITLE
How to store country name instead of country code on Address field

### ISSUE THREAD

**Issue by jimiero** [FLEXIcontent/flexicontent-cck#844]
Hi @ggppdk you said on a previous topic that's how the store work.

> the actual value of the every property is stored
and the actual value of the country propery is the countty code

Is there any way to store the country name instead?

**Comment by ggppdk** [comment]
It should be possible using value creation via
"Custom code"
inside the configuration of "Country" field (field type must be 'text')

As this tracker is not for support questions,
please ask in our forum, will answer you there, and then i ll put final answer here

**Comment by jimiero** [comment]
Hi @ggppdk posted here:

 https://flexicontent.org/forum/20-general-support/56556-how-to-store-country-name-instead-of-country-code-on-address-field.html

Also looking forward for my other topic i have on the forum.

Rgds
