### ISSUE TITLE
Language Associations is wrong filtered in front edition

### ISSUE THREAD

**Issue by charlynancy54** [FLEXIcontent/flexicontent-cck#845]
Hi,
With 3.2.1.12 release.
When you edit an item in frontpage.
The Language Associations is bad filtered.
Example : french item edited in front , when you click on select to associate an english item, you obtain a page with only french item
If you do that in backend it's ok : french item --> Language Association --> Select --> give English items

**Comment by charlynancy54** [comment]
This is related to a post in FLEXIcontent forum : [Here is the Link](https://flexicontent.org/forum/29-bug-reports/56549-language-associations-is-wrong-filtered-in-front-edition.html)
For memory, Georgios say in this post : 

> we should look into this and fix it (should not be difficult)
I think there is a relevant change in Joomla 3.8.4

**Comment by ggppdk** [comment]
Fixed it
also some UX improvements

in popup items listing for selecting an item to associate
- show if an item is already used in other association group and prevent its selection
- show if an item is already used in current association group
