### ISSUE TITLE
Favoured items view (category-based) is filtering according to current language, but it should not

### ISSUE THREAD

**Issue by ldoliv** [FLEXIcontent/flexicontent-cck#854]
Hello,

I'm using FLEXIcontent 3.2.1.12.

I configured a menu item using Favoured Items (category view), the issue is that it has a separate favourites list for each language. In EN language I have 3 items and in PT language I have 1 Item.

Should be the same list and not independent lists.

Thank you.

**Comment by ggppdk** [comment]
Create a default menu item for the view
and in it disable language filtering

**Comment by ldoliv** [comment]
In the menu item options, I disabled
![image](https://user-images.githubusercontent.com/6535818/37600546-8c51cc70-2b7f-11e8-8c71-c8d1474f295e.png)

but still has different lists. Issue remains.

**Comment by ggppdk** [comment]
hhmm i check and actually the setting is completely ignored for favourites
thus using all languages

so the issue may be elsewhere,
i will test / check soon

**Comment by ggppdk** [comment]
I tested with both My favourited (legacy view) and Favoured items (category-based) view and i cannot confirm this

i think that in your case,
there is something else filtering the items 
either they are expired or you have configured some "locked" filter values in menu item configuration
