### ISSUE TITLE
3.3.1 com_tag Installation issues

### ISSUE THREAD

**Issue by iamrobert** [FLEXIcontent/flexicontent-cck#855]
The website doesn't use tags (https://www.zapatas-shanghai.com/). 

After installation I see this maintenance button:

![](https://i.imgur.com/Tidbftz.png)

Then the maintenance message won't complete:
![](https://i.imgur.com/B77nDrp.png)

If this is expected behavior - should the maintenance button be disabled or hidden - if maintenance isn't required? 

Finally the site dies as:
![](https://i.imgur.com/MSJ2yaF.png)
- so I guess that maybe template changes I need to make?

Have downgraded

**Comment by ggppdk** [comment]
If you do not have Joomla tags assigned to Joomla articles (FC items) then you do need to run it at all

about the error i wonder why the class file does not get loaded

so you installed v3.3.x-stable branch ?

**Comment by iamrobert** [comment]
Hi,

I installed stable branch.

Can the maintenance button be hidden then as it creates extra stress for the user as they will assume they need to run maintenance that never will work? Or is it needed for other functions?

My fav field is unpublished (which hasn't caused issues before) - could that be why? 

![](https://i.imgur.com/KfW3QnX.png)
