### ISSUE TITLE
Ajax changing of ACL permissions for 'core' fields gives JS error, a full form save is needed to modify ACL permissions 

### ISSUE THREAD

**Issue by Cahuzacl** [FLEXIcontent/flexicontent-cck#858]
Hello,

In the edit page of the tags field, if you try to change the right, you got this error:

Uncaught TypeError: Cannot read property 'value' of null

For info, what I am trying to do is let the user from a usergroup edit that field from the frontend.

Best regards.

**Comment by ggppdk** [comment]
I have modified the title of this issue, to more accurately specify what the bug is about
still since saving the field saves the ACL permissions, i would say that this is minor issue
thanks for reporting

**Comment by ggppdk** [comment]
Fixed it with 2077d45
