### ISSUE TITLE
Displaying bugs when one gallery (or image or upload field) after the other

### ISSUE THREAD

**Issue by 2CPRESTA** [FLEXIcontent/flexicontent-cck#862]
![bug-image-fields-flexicontent](https://user-images.githubusercontent.com/30958416/39303784-beb3bb60-4957-11e8-8063-4f4b5f3a4659.png)
As you can see here , i have some problems to display several fields like Image / gallery / Document upload , one under the other , in Input Form.

Thanks for help

**Comment by ggppdk** [comment]
You mean in frontend, right ?

there must be some custom CSS (probably by Joomla template) in effect ...
lets discuss this in our forums
