### ISSUE TITLE
Add parameter limit to the image-gallery field for the number of images suggested via OG:IMAGE 

### ISSUE THREAD

**Issue by ggppdk** [FLEXIcontent/flexicontent-cck#864]
There should be a limit for this,
e.g. limiting to just one should be configurable , so that website creators can limit user selection to a specific image (the first one)

**Comment by lipatovroman** [comment]
Hello
No, additional parameters.
Just one - limit to the image-gallery field - only first image suggested via OG:IMAGE
YES/NO

But if you want extend this option, this parameter should be in each image in editor.
Something like - "Add meta OG:IMAGE for this image".
But I think it's not necessarily.

**Comment by ggppdk** [comment]
This feature has been done in recent past with 2 options
Suggest All images via OG or Just suggest the 1st image

So i am closing this issue
