### ISSUE TITLE
About UI improvement for new Item Type selection modal window

### ISSUE THREAD

**Issue by lungkao** [FLEXIcontent/flexicontent-cck#867]
![screen shot 2561-05-06 at 14 02 55](https://user-images.githubusercontent.com/2047778/39670774-629721aa-5136-11e8-81da-f8f4194341fd.png)
Select type page . 
margin: 2px 0;
![screen shot 2561-05-06 at 14 06 16](https://user-images.githubusercontent.com/2047778/39670788-b254a866-5136-11e8-9a83-c23504b18d93.png)

long label
![screen shot 2561-05-06 at 14 02 31](https://user-images.githubusercontent.com/2047778/39670837-794f0542-5137-11e8-8b5b-241248c7afd8.png)

**Comment by ggppdk** [comment]
About new item type creation
yes,
wanted to do this, it is rather ugly

What about making the "New item" button a drop down with choosen or select2 JS drop down (with search box if list is too long ?

**Comment by ggppdk** [comment]
About long labels i see it is a problem for languages with no spaces 
i think we can force wrap for it (break at regardless of having space)

**Comment by lungkao** [comment]
"New item" button a drop down with choosen or select2  good 
or  same as Select Menu Item Type
![screen shot 2561-05-07 at 09 41 52](https://user-images.githubusercontent.com/2047778/39682571-e7b871fa-51da-11e8-96cd-de38102e505d.png)
and show shot Description ( add parameter ennable or disable)
![screen shot 2561-05-07 at 09 42 19](https://user-images.githubusercontent.com/2047778/39682602-1ab0599c-51db-11e8-946e-4420ebd292cd.png)

**Comment by ggppdk** [comment]
Your suggestion implies that we also need a description for every type
Indeed it would be nice to have a description for every type

**Comment by ggppdk** [comment]
Added description property to the types
and update the selection to be similar to new menu item type selection

please update your testing to latest github version of v3.2.1.x-stable branch
and review it

![select_new_item_type](https://user-images.githubusercontent.com/5092940/39697041-40341c4a-51f8-11e8-94a3-f185e6edee4e.png)
