### ISSUE TITLE
Add proper usage of srcset to image gallery field,

### ISSUE THREAD

**Issue by ggppdk** [FLEXIcontent/flexicontent-cck#870]
We already have 3 thumbnail sizes auto-generated (+1 image if you count original image)
- and possibly add 1 or 2 more sizes

We could make some better use of them using srcset image attribute

This would give 
- faster response when squeezing a larger image and
- better quality compared to stretching the a smaller image

This would 
- either be automatic
- or by adding an auto option or similar to configuration

**Comment by micker** [comment]
for me i am agree !
thanks for contrubuting

**Comment by ggppdk** [comment]
> Let me know what you think. If you agree with this approach, I can work on development and submit a pull request.

Hi , yes any such improvements are welcome

**Comment by lyquix-owner** [comment]
Excellent! I will start working on it.

**Comment by micker** [comment]
hello sorry i do a bad merge and cancel it !
can you re pull in it in master branch for next release 3.4 ?

**Comment by rubenreyes2000** [comment]
Sorry about that, I always get confused on what branch to use.

https://github.com/FLEXIcontent/flexicontent-cck/pull/959

**Comment by micker** [comment]
perfect i will merge it and encourage community for testing and return
