### ISSUE TITLE
Select field language string labels are not translated in backend

### ISSUE THREAD

**Issue by ldoliv** [FLEXIcontent/flexicontent-cck#873]
Hello,
I'm using FLEXIcontent 3.2.1.14-rc 
I have added the language strings in all languages in the overrides. Works fine in frontend, but backend shows language constant, it should show the translation.

![image](https://user-images.githubusercontent.com/6535818/41966742-d9d12024-79f7-11e8-83e4-7e2cee470d29.png)

**Comment by ggppdk** [comment]
Hello

it is the way that joomla language overrides work ...
which is probably more powerful

you need to **set override for both frontend and backend**
in your case you have probably added only to frontend

**Comment by ldoliv** [comment]
Ok, thanks. I didn't remember that they are separated between frontend and backend.
