### ISSUE TITLE
[Sharemedia (video) field] Add support for video display in popup

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#877]
It can be nice to create a popup mode for the sharemedia field
- display image thumbnail instead of video (need size parameters)
- open video in popup window (need size parameters)

**Comment by ggppdk** [comment]
Better we implement 
sticky positioning as soon as scroll past it (adding it via JS)
`position: sticky`
similar to what social network and news websites are using

**Comment by micker** [comment]
good idea we can add twice option

**Comment by micker** [comment]
sticky was added
