### ISSUE TITLE
swf upload support removed from Joomla Media Manager

### ISSUE THREAD

**Issue by iamrobert** [FLEXIcontent/flexicontent-cck#880]
Recently  Joomla removed swf files as safe for upload:

https://docs.joomla.org/J3.x:Joomla_3.8.8_notes_about_the_changed_default_settings

Should FLEXIcontent do the same?

Also - in FLEXIcontent its missing from Legal MIME Types
image/jpeg,image/gif,image/png,image/bmp,application/msword,application/excel,application/pdf,application/powerpoint,text/plain,application/x-zip

**Comment by ggppdk** [comment]
@iamrobert 

So you are saying to remove it from (2 parameters legal MIME and allowed extensions)
- our manifest.xml
- and from the default="..." in the parameters too

**Comment by iamrobert** [comment]
I am thinking so - as who uses FLASH anymore?

**Comment by ggppdk** [comment]
Removed Flash file from default allowed extension and from default legal mime
with commit b26cd81

Settings in existing websites will not be effected
