### ISSUE TITLE
Last master version : problem with "easy styling funtion"

### ISSUE THREAD

**Issue by 2CPRESTA** [FLEXIcontent/flexicontent-cck#898]
i tested for a few minutes . it seems , category view style are only applied (through "easy-styling function ;) ) when more than 2 items (problem with featured items ? )... and just for the second and more, not the first . Thanks for help !

**Comment by ggppdk** [comment]
At blog layout

The first NN items are "featured"
The rest total-NN are "standard"

The parameters for the above 2 cases are different
you need to edit and set parameters for both cases

**Comment by 2CPRESTA** [comment]
I was wrong sorry... ;)
