### ISSUE TITLE
Help needed about a message Item Layout....

### ISSUE THREAD

**Issue by 2CPRESTA** [FLEXIcontent/flexicontent-cck#899]
I have this message but can't find the error i made... 

![image](https://user-images.githubusercontent.com/30958416/46916953-afcebf00-cfc1-11e8-8a48-5d530e57ebc4.png)

Could you please help me ?

**Comment by micker** [comment]
Please use forum for personal bug... But you item doenst find your template check item and type config and After check if you template folder exist

**Comment by 2CPRESTA** [comment]
Ok i wil post on forum...i verified but all seems ok...😭

**Comment by ggppdk** [comment]
Should be good now
