### ISSUE TITLE
Add info to $this -> filters object

### ISSUE THREAD

**Issue by rubenreyes2000** [FLEXIcontent/flexicontent-cck#901]
Hello guys

As we are working on leveraging FC filters via a JS app, I have found that I need to add some information to the $this -> filters object in order to properly generate some json output. I tried parsing the HTML output but it get really complicated.

I was wondering if you can consider making this changes to the core files that would pass the current value(s) of a filter, as well as the available options:

On [site/classes/flexicontent.fields.php](https://github.com/FLEXIcontent/flexicontent-cck/blob/767e3df2ac36db201cb2aa56ee9544c0c39c98cb/site/classes/flexicontent.fields.php):

Insert in line 3688

```
$filter->options = [];
$filter->value = $value;
```

Insert in line 3743:

```
foreach($options as $option) {
	if($option->value != '') {
		$filter->options[] = [
			'value' => $option->value,
			'text' => $option->text,
			'disabled' => $option->disable,
			'selected' => $option->value == $value ? true : false,
		];
	}
}
```

Insert in line 3810:

```
$filter->options[] = [
	'value' => $result->value,
	'text' => $result->text
];
```

Insert in line 4082:

```
if($result->value != '') {
	$filter->options[] = [
		'value' => $result->value,
		'text' => $result->text,
		'disabled' => $disable_attr != '' ? true : false,
		'checked' => $checked ? true : false
	];
}
```

Let me know what you think.

Thank you!

**Comment by ggppdk** [comment]
Hi,
can you make a PR ?, then we can review it and merge it

**Comment by rubenreyes2000** [comment]
Sure I can do that

I can see there have been several changes to the file on the current state of the repo. Should I make my changes on this last version, or the stable version 3.2.1.15?

**Comment by ggppdk** [comment]
If branch 3.2.1.x branch is more convenient then you can use it

After it gets merged, i will transfer changes to 3.3.x branch

**Comment by rubenreyes2000** [comment]
Perfect, thank you

**Comment by micker** [comment]
Thanks for propose

**Comment by ggppdk** [comment]
I have back-ported layouts for field filters from 3.3.x branch,
which already contain the $results (the fitering values array) inside the $displayData of the layout

**Comment by rubenreyes2000** [comment]
Great! Thank you!
