### ISSUE TITLE
Adress field asks for Google  Api Key even if OpenstreetMap is chosen

### ISSUE THREAD

**Issue by 2CPRESTA** [FLEXIcontent/flexicontent-cck#912]
Hello... All is in the title 

I was working on  a project and surprised by this error... so unable to validate the field. Thanks for corrections :)

**Comment by ggppdk** [comment]
The google API is still used in item form

maybe without an API key
you can use item form with free limit

it is typically the item viewing that will register most views
and you will be doing these with OpenstreetMap 

so want to be able to use item form without an API key ?

**Comment by 2CPRESTA** [comment]
yes if possible. I want to use OpensStreet Map per default. It seems like OpenStreet map wont display in the module i have on my homepage. Thanks for your help

**Comment by ggppdk** [comment]
Removed required property from API key field in field configuration
item form should work but it will show a message that API key is empty

**Comment by 2CPRESTA** [comment]
Hello.. it's quite ok... just , is it possible to use with a classic adress ( number of street, city , country) instead of GPS datas ? Thanks

**Comment by micker** [comment]
we will study to propose same system with openstreetmap

**Comment by 2CPRESTA** [comment]
Hello, i'm back ;) thanks for your help...

**Comment by 2CPRESTA** [comment]
Hello, something new about Openstreetmap integration? Thanks

**Comment by 2CPRESTA** [comment]
Hello...some news about the integration...in last version, problem remains... Thanks

**Comment by ggppdk** [comment]
Hello
the work for viewing
item view (mutliple values), category view / module (multiple items) is complete it fully supports openstreetmap

for **item form** you will still need to use googlemaps, 
there is no plan to work on this in the immediate future

other more important work is happening
plus of course bug-fixing new 3.3.x.x version (which is almost done)
