### ISSUE TITLE
Github Email Notifications for Crowdin Translations

### ISSUE THREAD

**Issue by lyquix-owner** [FLEXIcontent/flexicontent-cck#918]
Guys, is there a way to prevent emails notifications when Crowdin translations are commited, or maybe have them done in fewer commits?

This morning I received about 2800 emails from Github. And a few days ago there were about 1500 two days in a row.

Let me know your thoughts.

**Comment by micker** [comment]
sorry for that i am working on autogenerate installable package for language .. And now i add auto update file via joomla update system ... that create many email

**Comment by ggppdk** [comment]
I am thinking we need to create new repository
It should not be difficult to move existing configuration

**Comment by micker** [comment]
hello we moved all translation in new repo
https://github.com/FLEXIcontent/flexicontent-translations
no need to use notification on 
we will finish auto generate package with update inside
fighting with crowdin api

**Comment by ggppdk** [comment]
So @lyquix-owner  you just need to unsubscribe from notifications in the translations repository

**Comment by ggppdk** [comment]
The crowdin translations have been moved to other repository
so no more email / github notifications for commits related to translations
closing this one
