### ISSUE TITLE
Add item button in category view

### ISSUE THREAD

**Issue by vistamedia** [FLEXIcontent/flexicontent-cck#919]
The add item button doesn't have an image anymore. It seems there's a problem in the html helper. The button is still functional but invisible.
![2019-03-16_09-30-15](https://user-images.githubusercontent.com/9335926/54472773-9e871a00-47ce-11e9-80ab-5720e4a569af.jpeg)

**Comment by micker** [comment]
Ahhh 
3.3.1.3 ? 
maybe you can change option to use font-icon instead of image in global config ?

**Comment by ggppdk** [comment]
All icons either image or via CSS icon are not created by the same helper method

The add image (icon via CSS is good) got broken in the process, will fix

**Comment by ggppdk** [comment]
Fixed with f301939
