### ISSUE TITLE
Address field enhancements: multi-value, fieldgroup support

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#92]
refered to https://github.com/FLEXIcontent/flexicontent-cck/commit/43808c5c2d503e33ccbd7287e4a522b8f8ffb2bf
i think the best way to echanced this field is to generate select list with google api :
-1 dropdown for country
-1 dropdown for region
-1 text select with auto suggestion adress

and add 
- multi value ability
- field group support

what do you think @ggppdk @iamkeng ?

**Comment by ggppdk** [comment]
Hello,
I missed answering here

1. will use (Liquix) Ruben's suggested code,  --> and the suggested changes
2. also any reason not allowing direct change of latitude and longtitude ?
  i will change plugin to allow this, seeing what changes are needed to s
3. in future we would like to add 
   a) multi-value support and
   b) field-grouping support

Ruben you remember that also have commit ability.
Do you have a local GitHub repository of FLEXIcontent ?

**Comment by ggppdk** [comment]
For now i re-enabled the usage of
country drop down and USA states drop-down.

Other Liquix's suggested changes should be done in v3.1, if not done in v3.0

**Comment by Lyquix** [comment]
We are working on this field now. Should be sending a pull request tomorrow.

**Comment by ggppdk** [comment]
This is nice to hear,  I did not find time to work more on this field. And it is good to know to avoid duplicate work.

Thanks for contributing this and for new work on it))
