### ISSUE TITLE
Javascript bug on autocomplete feature

### ISSUE THREAD

**Issue by vistamedia** [FLEXIcontent/flexicontent-cck#920]
There's a strange javascript bug that appears when autocomplete is on in text search filter / category view. It make the top menu item disapear.
![2019-03-16_09-46-05](https://user-images.githubusercontent.com/9335926/54472898-ac3d9f00-47d0-11e9-8295-d41415e41cae.jpeg)
![2019-03-16_09-46-22](https://user-images.githubusercontent.com/9335926/54472900-b19ae980-47d0-11e9-97d4-ebf3086955eb.jpeg)
You can experience it here: [http://www.iddac.net/creation/agenda-creation](http://www.iddac.net/creation/agenda-creation)

**Comment by ggppdk** [comment]
After private discussion we had , i am closing this, it seems to be related to the version of jQuery loaded in the website
