### ISSUE TITLE
Manual adding of News template

### ISSUE THREAD

**Issue by 2CPRESTA** [FLEXIcontent/flexicontent-cck#934]
Hello, i just wanted to add the News template (sent by ggppdk for tests) to the latest version of Flexicontent... but it doesnt seem to work correctly... Could you have a look and tell me if i did something wrong ? I unzipped the archive in com_flexicontent/templates...
Thanks

**Comment by micker** [comment]
Hello without explain.... Difficult did you see template and option on backend ?

**Comment by ggppdk** [comment]
Please open a forum issue with details.
Github issue tracker is not a place for giving support.
I am going to close this
