### ISSUE TITLE
Error 1054 when using "create item" form link

### ISSUE THREAD

**Issue by 2CPRESTA** [FLEXIcontent/flexicontent-cck#935]
Hello..; all is in title... how can i fix that ? seems strange... i just installed latest version and can't create any item form frontend. thanks

**Comment by micker** [comment]
Hello laste isnt good 3.3.1.6 or 3.3.1.5

**Comment by ggppdk** [comment]
I cannot replicate this
please make sure you have 3.3.15 and then enabled Joomla debug and give here the full stack trace

**Comment by ggppdk** [comment]
Please post here only if you have complete details of an issue.

After you you have installed 3.3.15 , then enable Joomla debug and open a new forum thread with the full stack trace

**Comment by 2CPRESTA** [comment]
Hello... complete new install solved the problem ;)
