### ISSUE TITLE
Lyquix FLEXIcontent template - for your consideration

### ISSUE THREAD

**Issue by Lyquix** [FLEXIcontent/flexicontent-cck#94]
@ggppdk and @micker 

I opened this enhancement to let you know about the new Lyquix FLEXIcontent template. We created it to address some challenges we have had while working on our client's projects. Here are the objectives that we were trying to accomplish:
1. Reduce the amount of code that we need to maintain by reusing code across templates.
2. Allow us to rely more on configuration parameters to create different layouts than creating custom php templates
3. Create a more flexible HTML structure that we can easily customize with CSS for different client needs and designs

Keep in mind that this template is intended for advanced developers. We don't mean this as something that can be easily used by a non-advanced developer because it requires a lot of configuration and styling. However, I believe there are several ideas that would be beneficial for the FLEXIcontent core. I hope you like it.
# Categories
## Category Layout

We wanted to have the most flexibility when setting up the layout of categories. There are several elements of categories that we needed to place in different positions depending on the content and the client design:
- Category description
- List of subcategories
- List of items

Changing the order in which these needed to be rendered required changing the php code. We came up with an idea to have all the elements of categories activated and ordered as needed. We created a jQuery Select2 sortable field that contains the specific parts of a category layout:

![image](https://cloud.githubusercontent.com/assets/2821924/5550826/398f2f40-8b7e-11e4-8904-c6bfe3d9bee3.png)

The complete list is:
- Buttons
- Title
- Filter
- Alpha index
- Image
- Description
- Subcategories
- Map
- Items
- Pagination

Additionally we added some "separators" that create wrapping DIVs that can be used for further fine tuning the layout and style of the category page.

This is allowing us to very easily turn on or off parts of the category as we need it, as sort it as needed by the design or the content.
## Title override

We added a field that allow us to override the title to be used for the category. If not used, the Category title is used as page title. Also, the page title is always in H1 tags.
## Labels or headings

For various sections we included options for adding labels or headings, this includes: Filters, Alpha Index, Sub Categories, Leading Items List, Featured Items List and Intro Items List.

This setting allows to enter HTML directly so we have control on what tag we want to use for that heading.

![image](https://cloud.githubusercontent.com/assets/2821924/5550866/b12e9ee0-8b7f-11e4-9392-ea4ff0230f67.png)
## Sub-Categories
- Option for the tag to use on sub-categories titles
- Option on link to subcategories
- Option on subcategory image alignment (adds a class to the image wrapper)
- Option to show items in each subcategory
- Options for display of subcategory items:
  - List of titles (text only)
  - List of clickable titles (links to items)
  - Items with fields as configured in the category template positions
- Option for a custom css class

![image](https://cloud.githubusercontent.com/assets/2821924/5550868/bb23a92c-8b7f-11e4-8675-e4b110ccb2f9.png)

It is important to highlight the logic we use: when we select to show subcategory items under each subcategory, those items are not displayed in the main category item lists. In our projects it has not made sense to have the same item appearing twice. The only exception is when the item is explicitly in both the main category and the sub category.
## Map

We included the option to add a map in the category view. The following options are available:
- Option to display no map, map only, or map with items lists
- Field that contains address information (field type addressint)
- Dimensions of the map
- Type of map (roads, satellite), and controls to be included
- Pre- and post- HTML code, CSS class, and Google Maps API key

![image](https://cloud.githubusercontent.com/assets/2821924/5550892/6863e6ec-8b80-11e4-9f6f-3b6935d97526.png)

Additionally, for each item in the map, we have settings that control the information that will appear in their bubble:
- Title tag type
- Field to use as title
- Format for dates
- Field to use as description, and max characters
- Label for read more link
- CSS class
- Options for item image: field to use, size to use, image clickable, alignment and css class

![image](https://cloud.githubusercontent.com/assets/2821924/5550897/b06d4f82-8b80-11e4-999d-d6360d5db858.png)
## Items lists

This is our approach:
If Featured Items need to be on its own group, we display them first
If Leading Items are used, they are displayed next
The rest of the items (Intro Items) are displayed next

We added a parameter "Separate Featured Items" to indicate whether the list of Featured Items should be separate and first, or if Featured Items will be mixed with the rest and just have an additional CSS class.

Also, as mentioned above, if an item is set to appear under its subcategory, then it will not appear in the item lists, with the exception of items that are both in the main category and a sub category.

For all the lists we added parameters that allow to:
- Include Sharing Buttons and Comments Count on each item
- Select the title heading tag to use
- Field to use as title
- Format to use on date fields
- Field to use as description, and max characters
- Read more label
- Custom CSS class
- Item image settings: field to use, size to use, clickable, alignment and custom CSS class

![image](https://cloud.githubusercontent.com/assets/2821924/5550954/31ee28ea-8b83-11e4-99d5-d8e1dce77d64.png)
# Items

For items we don't have many parameters: only the format for dates, and classes to be added to the positions.
# General Template Considerations
## Files and Functions

We have a template named "custom" that only has the following files:

category.php

``` php
<?php
include(JPATH_SITE.DS.'components'.DS.'com_flexicontent'.DS.'templates'.DS.'lyquix'.DS.'category.php');
```

item.php

``` php
<?php
include(JPATH_SITE.DS.'components'.DS.'com_flexicontent'.DS.'templates'.DS.'lyquix'.DS.'item.php');
```

category.xml and item.xml have all the custom parameters and positions. This very basic structure allows us to create custom templates for different content types. We create copies of this template and name them custom-news, custom-projects, custom-people, etc. In that way we can independently configure the fields that will go in the positions.

We have a folder that contains our base category.php and item.php:

category.php

``` php
<?php defined( '_JEXEC' ) or die( 'Restricted access' );

// Category sections ordering
$cat_sections = $this->params->get('cat_layout_order',array("buttons","title","filters","alpha","image","desc","map","subcats","items","pagination"));
if (!is_array($cat_sections[0])){
    $cat_sections = explode(",", $cat_sections[0]);
}
if (is_array($cat_sections)) {
    $i=1;
    echo '<div class="tmpl-'.str_replace('.category.','',$this->tmpl).' cat-'.$this->category->alias.'">';
        echo '<div class="section-'.$i.'">';
          foreach ($cat_sections as $cat_section){
              if (strstr($cat_section, 'sep')){
                  $i++;
                  echo '</div><div class="section-'.$i.'">';
              }else {
                $section= 'renderCat'.ucfirst($cat_section);
                plgFlexicontentLyquix::$section();
              }
          }
    echo '</div>';
}
```

item.php

``` php
<?php defined( '_JEXEC' ) or die( 'Restricted access' );
echo '<div class="tmpl-'.str_replace('.items.','',$this->tmpl).' item-'.$this->item->alias.'">';
for($j = 1; $j <= 7; $j++){
    if(isset($this->item->positions['group_'.$j])){
        echo '<div class="group_'.$j.' '.$this->params->get('item_css_group_'.$j, '').'">';
        foreach ($this->item->positions['group_'.$j] as $field){
            echo plgFlexicontentLyquix::renderItemField($this->item,$field);
        }
        echo '</div>';
    }
}
echo '</div>';
```

You can see in both cases that the structure is very slim. We make use of CSS classes for styling. We can easily customize styles based on the specific template used, or whether it is a category or item.

The rendering of each section of the category or item pages relies on a set of functions that we placed in a couple plugins. We didn't want to create global functions directly on our FC templates, and instead of going and creating PHP classes, we decided to use the Plugin infrastructure of Joomla. You will find the plugin files in the attachment.

Beware that we created a new element Select2 as well.

You can download all the files here: http://lyquix.com/files/lyquix-fc-tmpl.zip
## Positions

In both category and item layout we are using 7 positions. We figured that this gives us all the necessary blocks we need for any kind of layout. Our code automatically generates these positions only if there are any fields in them. With 7 positions we can do something as complex as this:

![image](https://cloud.githubusercontent.com/assets/2821924/5551004/e7f4f712-8b84-11e4-96ff-4f6ae639f912.png)

In our projects we have not encountered the need for something as complex as this.

**Comment by ggppdk** [comment]
Will find time to review this

Please note that select2.php these links are broken

$doc->addScript(JURI::root().'components'.DS.'com_flexicontent'.DS.'librairies'.DS.'select2'.DS.'select2.js');
$doc->addStyleSheet(JURI::root().'components'.DS.'com_flexicontent'.DS.'librairies'.DS.'select2'.DS.'select2.css');


'.DS.'
should be:
/


but it better to use:
flexicontent_html::loadFramework('select2');

e.g. it will also load language files of select2

**Comment by ggppdk** [comment]
Again thanks for your submission, v3 is almost done, will include this in v3.1, which will have several new category layouts:

e.g. category layout:
- calendar,
- full view mobile (touch) slider,
- google-maps
- etc

**Comment by micker** [comment]
Great roadmap

**Comment by Lyquix** [comment]
Hello guys, we have continue development of our FC template, you can check it out here:
https://github.com/Lyquix/flexicontent_templates

Some things we have added recently:

**Category View:**
* Fields to add custom CSS classes, heading labels, and pre-text and post-text for all category sections: filters, alpha index, subcategories, items, leading items, featured items, intro items, pagination
* AddThis sharing buttons: you can control whether you want them in the category view (for individual items). We can also control its position (after a specific field), and customize its services.
* Subcategories "View all" link text can be customized and include the category title in it. For example a category with title Services, the label "View All {title}" would be rendered as "View All Services"
* Disqus comment count link position can now be customized after specific field
* Read More links can have custom position (after specific field)
* Custom CSS classes for items based on field values: when rendering each item a custom function is executed that can create classes based on field values. For example imagine you have field that indicates if an items is "free" or "paid", you can have a css class added on each case and use that for customizing your styles
* Field rendering override: before each field is displayed, a custom function is invoked and has the opportunity to override the rendering of the field
* Section rendering override: before each category section (filters, alpha index, subcategories, items, leading items, featured items, intro items, pagination) is rendered, a custom function is invoked and has the opportunity to render the section differently

**Item View:**
Same enhancements for AddThis and Disqus, and custom field rendering, as in category view

**Comment by micker** [comment]
great !!! i will test it

**Comment by ggppdk** [comment]
Thanks for contribution !!

will review this soon

**Comment by ggppdk** [comment]
@Lyquix 

3.0.16 milestone

Since we have optimized forms with AJAX loading of templates
- we can add layouts with many parameters with no worries

Please provide latest version of the template
lyquix-fc-tmpl

(of course we propably use some other name like lyquix-modular)

**Comment by ggppdk** [comment]
Sorry i missed your answer, you have them here:
https://github.com/Lyquix/flexicontent_templates

**Comment by Lyquix** [comment]
That's right. Take a look and let me know what you think. What we normally do is that we create copies of `custom` and `json` as needed so that we can configure them independently for categories and types.

The master branch is our 1.0.x version, there is another branch for 2.0.x.

We just launched this site making use of our templates, modules and plugins that you find in the Lyquix repositories: https://www.rothmaninstitute.com/

**Comment by Lyquix** [comment]
We also used our Joomla template, that includes our responsive framework: https://github.com/Lyquix/tpl_lyquix

**Comment by ggppdk** [comment]
A comment about
> What we normally do is that we create copies of custom and json as needed so that **we can configure them independently** for categories and types.

Yes we would want to be able to create extra configuration of templates **without copying the files**
- because we would want to avoid having to update multiple set of files every time with the new version of the template

I had start doing this, and implemented this into the DB model, possibly work needed to finish this, is just update the code that loads the top-level template files (which is inside the view.html.php ... which is good ...)
- the idea is have 2 options
1. new layout configuration + (empty template folder = use files from master template)
2. new layout configuration + copy of the template files

also if later is needed someone could also add a copy of the template files 
then our backend template manager will list configuration under the master template

- but maybe simpler solution is just add something like "include MASTER.PHP"  inside all template files of the copied template, ... and just parse the file to check if it is only including the "master" still not sure what is best, 

in any case i think it is good to finish this

**Comment by Lyquix** [comment]
@ggppdk that's already taken care of, all the logic is in the `lyquix` folder.

`category.php` and `item.php` in the `custom` and `json` folders call their corresponding `category.php` and `item.php` files in the `lyquix` folder.

In addition to that there are optional `category-custom.php` and `item-custom.php` where we can add custom functionality for specific templates, which includes things like:

* Custom/dynamic CSS classes and HTML attributes for sub-categories and items
* Custom field rendering: some times we need to tweak how a type of field (or individual instance of a field) is rendered in a specific template
* Custom rendering of sections (title, description, subcategories, items, etc) - even in our template some times we need to vary how some sections are rendered

If we are in a situation where we need to do the same field or section rendering customization for multiple categories, we create a separate PHP file and use includes.

**Comment by rubenreyes2000** [comment]
This issue can be closed

**Comment by ggppdk** [comment]
Hello

about templates beside my comments above
i want to add that

we will go for using a single template 
- that will be using **page builder JS**
- but ... it will be repeatable per category item !!

like we did in universal module
