### ISSUE TITLE
PHP Notice: $assocs_id undefined in Categories View

### ISSUE THREAD

**Issue by iamrobert** [FLEXIcontent/flexicontent-cck#941]
FLEXIcontent 3.3.1.5 
php 7.2.11

<b>Notice</b>:  Undefined property: FlexicontentViewCategories::$assocs_id in <b>##\administrator\components\com_flexicontent\views\categories\tmpl\default.php</b> on line <b>309</b><br /> hidden-phone hidden-tablet

![](https://i.imgur.com/F5981oy.png)

Line:
`<td class="<?php echo !$this->assocs_id ? 'hidden-phone hidden-tablet' : ''; ?>">`

not sure why we can't call like this:

`<td class="col_assoc hidden-phone hidden-tablet">`

Also on the th:

`<th class="hideOnDemandClass <?php echo !$this->assocs_id ? 'hidden-phone hidden-tablet' : ''; ?>">`

vs: 

`<th class="col_assoc hideOnDemandClass hidden-phone hidden-tablet">`

**Comment by ggppdk** [comment]
Can you try 3.3.1.x branch ?
it should be fixed, install via URL
https://github.com/FLEXIcontent/flexicontent-cck/archive/3.3.1.x.zip

**Comment by iamrobert** [comment]
Its still there with:

![](https://i.imgur.com/78E7ETa.png)

**Comment by ggppdk** [comment]
The non-existing variable was copied there by mistake. It is not needed / does not exist in this view
Fixed with e2571f5
