### ISSUE TITLE
Update PHP to 7.2 creates "Fatal Error 0 Using $this when not in object context"

### ISSUE THREAD

**Issue by lungkao** [FLEXIcontent/flexicontent-cck#948]
FLEXIcontent v3.3.1.5 php 7.2.16

com_flexicontent/templates/blog/item_html5.php on line 24

$menu = JSite::getMenu()->getActive();

change to

$menu =  JFactory::getApplication()->getMenu();

**Comment by ggppdk** [comment]
Is this some old copy of blog template ?

I see that this code has been changed already for more than 1 or 2 years ago
https://github.com/FLEXIcontent/flexicontent-cck/blob/a62b84eedd6b4e7ad07ae2498765144d2cb54292/site/templates/blog/item_html5.php#L27

Also you should use
`$menu = JFactory::getApplication()->getMenu()->getActive();`
not
`$menu = JFactory::getApplication()->getMenu();`

**Comment by lungkao** [comment]
sorry

**Comment by ggppdk** [comment]
No problem, thanks for feedback
