### ISSUE TITLE
Finish support for bootstrap 4 in field viewing layouts and frontend module layouts

### ISSUE THREAD

**Issue by lipatovroman** [FLEXIcontent/flexicontent-cck#949]
Need to Finish support for bootstrap 4 in field viewing layouts and frontend module layouts
because now FlexiContent not supports templates with bootstrap 4.

Relevant topic (with example) - https://flexicontent.org/forum/29-bug-reports/57278-search-module-button-and-helix-templates.html

**Comment by micker** [comment]
hello i close this issue .. we will check mre with j4
