### ISSUE TITLE
FLEXIcontent causes double execution of the Joomla batch function.

### ISSUE THREAD

**Issue by vistamedia** [FLEXIcontent/flexicontent-cck#955]
To reproduce it just try to copy a module using the batch function. It will be copied twice.

<img width="574" alt="Capture d'écran 2019-08-04 14 13 01" src="https://user-images.githubusercontent.com/9335926/62423564-45a71800-b6c2-11e9-893c-9a92f0650038.png">
<img width="816" alt="Capture d'écran 2019-08-04 14 14 44" src="https://user-images.githubusercontent.com/9335926/62423565-45a71800-b6c2-11e9-8eca-c2e5d0be6661.png">

**Comment by vistamedia** [comment]
FYI, I just tested on a fresh Joomla install with only FLEXIcontent on it.

**Comment by ggppdk** [comment]
It sounds like a Joomla bug, 

Possibly the SQL query of batch operation that selects the modules to copy has a SQL JOIN that causes the modules to be selected twice

but in any case i will test with a new installation to see what exactly is happening
