### ISSUE TITLE
About (new) Field Grouping, new multi-value UI, configurable server-side validation, COMMON field configuration, better Item Form UI

### ISSUE THREAD

**Issue by ggppdk** [FLEXIcontent/flexicontent-cck#96]
happy new year with health and prosperity :-)

There is a lot of work  going on in fields in ITEM FORM

- more work to cleaner CSS

- adding configurable server-side validation to our generic fields:
 text, textarea
![new_server-side-validation](https://cloud.githubusercontent.com/assets/5092940/5594965/84cf2a90-926e-11e4-8c27-72a401e42315.png)

- improved output for our generic fields:
 text, textarea
   ![new_output](https://cloud.githubusercontent.com/assets/5092940/5594958/4b5a50aa-926e-11e4-97fa-7416f639f5d6.png)

- better user experience for multi-value
  a. new cleaner -common- CSS   (inside flexi-shared.css), removed almost all header-inserted CSS
  b. inline ADD-new buttons !!
  c. smarter delete button will "empty" last value (maybe we could have a clear button but then too many buttons ...)
  d. better / more BROWSER-side validation 
  e. scroll to make visible new values (* works with field grouping too !!)
  f. more compact view, with boxes that will wrap holding label and form field together e.g (weblink, email, termlist)
  
- converted to multi-value several fields  (to use them in field grouping)
  textarea, select, radio, radioimage
  
  TODO ?: addressint, shareaudio, sharevideo
![new_multi-value_look](https://cloud.githubusercontent.com/assets/5092940/5594985/1afcfdbc-926f-11e4-8de4-4cebe135440d.png)
![new_multi-value_look2](https://cloud.githubusercontent.com/assets/5092940/5594984/1afc3d50-926f-11e4-9b91-58c084d74e4b.png)

- updated almost ALL fields to have common configuration 3 main sections of parameters and the similar sub-sections (including your phonenumbers field)
   a. Item from
   b. Frontend (viewing)
   c. Filtering
e.g. phonenumbers:
![phone_field_updated1](https://cloud.githubusercontent.com/assets/5092940/5594969/ac87549a-926e-11e4-9213-7ab3e4b985c8.png)
![phone_field_updated2](https://cloud.githubusercontent.com/assets/5092940/5594970/ac888770-926e-11e4-9940-3be35974c8c7.png)
![phone_field_updated3](https://cloud.githubusercontent.com/assets/5092940/5594971/ac892158-926e-11e4-84ad-c5fb75174743.png)

- added FIELD GROUPING to all multi-value fields (* YOU NEED fieldgroup field which is not on GitHub)
 a. image,
 b. text, textarea, textselect
 c. date, email, weblink, extendedweblink, termlist, phonenumbers
 d. select, radio, radioimage,
 
 TODO: file, linklist,
 ... AND (after they are converted to multi-value): addressint, shareaudio, sharevideo
 
 PREPARED: ** checkbox, checkboxradio, multi-select ** were done but the are disabled, because they become an array of array of values,
 ... so will not enable these 3 without MORE PLANNING, e.g. if we compress (PHP serialize) values, tehn filtering will not work, and we break compatibility
 ![itemform_with_fieldgroup_field](https://cloud.githubusercontent.com/assets/5092940/5594957/45f3404a-926e-11e4-8908-8b00c4147c05.png)
![itemform_with_fieldgroup_field3](https://cloud.githubusercontent.com/assets/5092940/5594994/679c341c-926f-11e4-9496-60565639eb5a.png)
![itemform_with_fieldgroup_field2](https://cloud.githubusercontent.com/assets/5092940/5594995/6a4ee100-926f-11e4-848f-4c271076febf.png)

- About field grouping:
 a. it works with very --complex-- fields, e.g. image field !!!
 b. almost all ITEM FORM / VIEWING field parameters are respected/used
 c. existing values are usable if field is GROUPED / UNGROUPED
 d. FILTERING works on field that participate in a group
 e. FORM VALIDATION works properly

**Comment by micker** [comment]
great adding !!!!
i test it perfect
juste if you use texte area in multi value and html editeur
=> other value doesn't have html editor :100:

**Comment by ggppdk** [comment]
Mickey this was fixed, you've have HTML editor in All values of a multivalued textarea

**Comment by vistamedia** [comment]
Looks amazing... to my point of view it was the only missing feature (I mean the field groups). The server side validation is really great also. By the way I noticed that the inputmask library was outdated and thus doesn't match the documentation (some functions names have changed).

**Comment by micker** [comment]
MMMMAAAAAANNNNUUUUU is HERE !!!! good save the queen

**Comment by ggppdk** [comment]
Emmanuel, yes you are right !

the inputmask is outdated and the custom mask code is broken , plus we do not have regular expression

i will update and add REGULAR Expression
so now have "custom mask" and "regular expression"
![text_field_validation_options](https://cloud.githubusercontent.com/assets/5092940/5853090/71c72730-a228-11e4-917b-b6bd165c7f2d.png)

**Comment by acymru** [comment]
This is a profoundly beautiful piece of software (using 3.0 beta5).  I wonder - you mention "added FIELD GROUPING to all multi-value fields (* YOU NEED fieldgroup field which is not on GitHub)".  Where could one find it?

**Comment by ggppdk** [comment]
It is now included in the BETA4/BETA5

i ll change this message

Please click "new Field"  it is in the list

**Comment by acymru** [comment]
The below notice is still included in my install of beta5.  I realize that could mean nothing, as it could just be legacy text.  But the multiple value option for text fields in a fieldgroup doesn't work for me.  Would it make sense to try it with a full fresh re-install?

To be clear, the fieldgroup itself can be multivalue, just not the fields within it.

"Note: installed version of Field: 'fieldgroup' is meant for FLEXIcontent versions prior to: v3.0 rc,   and it is given freely in BETA versions prior to: 3.0 rc,   nevertheless it will continue to function after FLEXIcontent is upgraded."

**Comment by ggppdk** [comment]
-- multi-value is not intended to be used inside the field group, 
--> since the multiple value of the field, are used 1 each group

will hide this in next commit to avoid confusion

**Comment by ggppdk** [comment]
In all fields merge field grouping TAB into the editing 
and combined "Use in group" with the multi-value parameters,
hidding them when Use in group is ON

**Comment by acymru** [comment]
Aha, makes sense.  Thank you.

**Comment by acymru** [comment]
I see that it is not possible to add a "file" field to a fieldgroup.  Is this also by design?

**Comment by ggppdk** [comment]
This was left to be done last (last field and maybe Address field too in near future),

code of file field is 90% done to support field grouping, it needs a little more work


about file field you may want to check out the new "Form-inline"  mode
-- the new mode means that we need some more work to support field grouping in file field

now finishing Cascading support (of dependent values)  for field grouping  (e.g. Content-Country-City) for fields:   select, selectmultiple, radio(image), checkbox(image)

**Comment by acymru** [comment]
I am endlessly amazed.  I'm glad the feature is coming, as I have much good use for it, setting up file upload groups with publication details (repeatable blocks of file field with companion text fields).

**Comment by acymru** [comment]
Just checking in on the file field code status.  I have a very nice interface set up for highly specialized content entry, and this is the last missing piece of the puzzle that will make folks very happy.  Speaking of which, you've mentioned that this will evolve into a commercial version.  I would like very much to do whatever I can to direct assets in your direction, as this component is worth a lot and you deserve compensation.  We are a guaranteed sponsor.

**Comment by ggppdk** [comment]
Hello

you speak of finishing field grouping support in file field , please open a new issue, i will mark it as bug so that it is not missed for v3 RC (after BETA6, which is mostly done)

**Comment by acymru** [comment]
Excellent, will do, thank you.

**Comment by ggppdk** [comment]
Done , closing this in favor of specific issues,

we have another 1 or 2 other related issues open like:

- finishing support of file field in field grouping
- and like adding an HTML display variable with custom replacement for creating the display of the field group: #147
