### ISSUE TITLE
Date filter in category view return no article in 3.3.1.6

### ISSUE THREAD

**Issue by DevMatGod** [FLEXIcontent/flexicontent-cck#963]
### Expected behavior
When filtering with a date field on a flexicontent category page, the page should display articles who match the selected value.

### Current behavior
The page display no article.

### Temporary solution
Downgrading to 3.3.1.5 solve the problem.

**Comment by ggppdk** [comment]
I will look into this,
it must be because the filter confuses multi-value mode with range value mode

**Comment by ggppdk** [comment]
this was broken when filter as age option was added
i have made a fix, i need to test a little more

**Comment by ggppdk** [comment]
Fixed with c461b92c0
