### ISSUE TITLE
Does address field require is_ingroup?

### ISSUE THREAD

**Issue by iamrobert** [FLEXIcontent/flexicontent-cck#967]
I am getting a notice about Undefined variable: is_ingroup for address field.

Notice: Undefined variable: is_ingroup in plugins\flexicontent_fields\addressint\tmpl\value.php on line 653

![Error](https://i.imgur.com/9YidEOM.png)

If I add:

 is_ingroup = ''; to value.php file it seems to vanish. Is it meant to be defined in addressint.php?

**Comment by ggppdk** [comment]
This will not occur in next release (v3.4.0)
