### ISSUE TITLE
Bug on multi-select sorting

### ISSUE THREAD

**Issue by rubenreyes2000** [FLEXIcontent/flexicontent-cck#969]
Hi guys

Just wanted to let you know that we are observing the following bug on 3.3.1.5 and 3.3.1.6:

Configuration

- selectmultiple field
- default value is set, for example "a,b,c"
- Usage of default value: Load when editing new items
- sortable: yes
 
To reproduce issue

- Create new item
- Field is prepopulated with default options
- Change the order of options
- Save and close item
- Open item again
- Field is displaying values in correct saved order BUT select field has default order (use Inspect to view)
- Save and close item
- Open item again
- Field is now reverted to default ordering

I am looking through the code to find the bug, I will let you know what I find.

**Comment by micker** [comment]
hello can you try to test last version in master branch ?
because https://github.com/FLEXIcontent/flexicontent-cck/commit/aafd02a1897cc5417a7432b9a5e67d81d9236da5

**Comment by rubenreyes2000** [comment]
Same problem using the current version of master branch

**Comment by micker** [comment]
ok @ggppdk  can look it

**Comment by ggppdk** [comment]
hi, I will have a look at this

**Comment by rubenreyes2000** [comment]
I created a pull request with a fix for this issue. Please review it an let me know what you think:

https://github.com/FLEXIcontent/flexicontent-cck/pull/974

**Comment by ggppdk** [comment]
I followed the instructions and i cannot replicate the bug
but i can not replicate it. Tested with firefox and chrome

**I think there is a JS error** during form load or during reordering that causes this.
Can you check for error (not for warnings / notices) in browser console ?

If we include the suggested fix,
then order of drop down selection will be changed no longer being as configuration

**Comment by rubenreyes2000** [comment]
I don't see any JS errors.

I prepared a new video to explain how to reproduce the error. I hope this helps:

https://www.loom.com/share/a867ce8cc2c74738bda1883037d5bdd6

**Comment by ggppdk** [comment]
Good
**i can now replicate** this bug with 3.3.4
to be able to replicate i need to load + save the form a 2nd time, -without reordering- the field

- no JS error, just our JS code is bogus and does not set the order when form is saved a 2nd time without any reordering occuring

**Will make
 a JS fix ASAP**
 and / or add your suggested code of reordering the options list on form reload

about the topic of the choices js , it is JS work that it is not trivial, and can lead to bugs,
will be done slowly, starting with the select field

now need to finish work on 
 - reviews
 - endless scroll (lazy loading of items)
 - add lazy loading to more fields, (now mediafile (media player) field has it) 
 - move the page builder ability (you can already see in universal module) to item layout and category layout

**Comment by ggppdk** [comment]
Sorry for late response for this issue
i have tested your suggested fix and committed it

Thanks !
