### ISSUE TITLE
Dahshboard Naming Inconsistent

### ISSUE THREAD

**Issue by iamrobert** [FLEXIcontent/flexicontent-cck#97]
### 1. Is it dashboard or home?
The title says dashboard yet the side menu says home.

### 2. The side Menu + control panel order?
Side Menu - items/types/categories but control panel is items/categories/types

I think items/categories is better.

However, I haven't worked out how to change the side menu items.

![download](https://cloud.githubusercontent.com/assets/8617673/5602118/0ef48f9e-9373-11e4-88b8-2c0861ac35e0.png)

**Comment by ggppdk** [comment]
Hello

i merged your pull request
