### ISSUE TITLE
How ta translate "No viewable content in Current View for your Access Level" ?

### ISSUE THREAD

**Issue by AlainRnet** [FLEXIcontent/flexicontent-cck#973]
Hi.
In
https://github.com/FLEXIcontent/flexicontent-cck/blob/4a5101567511d369abcdc8ae6df805de439e5907/modules/mod_flexicontent/helper.php#L1383 and in https://github.com/FLEXIcontent/flexicontent-cck/blob/4a5101567511d369abcdc8ae6df805de439e5907/modules/mod_flexicontent/helper.php#L1270 how can I translate this string in french ?

**Comment by micker** [comment]
haaaa need to update
for now you can use override.ini 
No viewable content in Current View for your Access Level="your tranalsation"

**Comment by micker** [comment]
corrected here (only for beta 4 for now)
https://github.com/FLEXIcontent/flexicontent-cck/commit/5f733697edec8cfcd3cbc9de215bfbfd58e45e3a

**Comment by AlainRnet** [comment]
> for now you can use override.ini
> No viewable content in Current View for your Access Level="your tranalsation"

doesn't work...

**Comment by micker** [comment]
can you test beta4 (donwload and install master branch) ?

**Comment by AlainRnet** [comment]
Not on this website, cause in production.
Thank you very much.

**Comment by micker** [comment]
i already use it .. i understand
=> you can update via override files or waiting official 3.4

**Comment by AlainRnet** [comment]
I'll wait.
I use Language -> Override, but "No viewable content in Current View for your Access Level" becomes "NOVIEWABLECONTENTINCURRENTVIEWFORYOURACCESSLEVEL" and when I add "No viewable content in Current View for your Access Level" and translation by FTP, I always have original string.

Do you mean another override system ?

**Comment by micker** [comment]
yes edit file directly
languages/fr-FR/override.ini
