### ISSUE TITLE
Need to update phpthumbs for php 7.4

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#976]
relevate too
https://github.com/JamesHeinrich/phpThumb/commit/11b318e7d06f7b84b524a22ab7b6d78397bfedec
need to update phpthumbs librarie

**Comment by ggppdk** [comment]
We have added this already,
https://github.com/FLEXIcontent/flexicontent-cck/blob/3.3.1.x/site/librairies/phpthumb/phpThumb.php#L1-L22

It seems some merging overwrote the changes in the master branch
easy fix i recommitted the changes here b31d1f1

**Comment by micker** [comment]
Cool thanks
