### ISSUE TITLE
Module Flexifilters does not display custom fields outside flexicontent

### ISSUE THREAD

**Issue by vistamedia** [FLEXIcontent/flexicontent-cck#977]
When using the filters module on a non flexicontent page the custom fields are not displayed. (v3.3.2)

Please see: [https://www.flexicontent.org/forum/21-troubleshooting/57695-field-filter-not-show-in-flexifilter-module-in-not-flexicontent-pages.html](url)

**Comment by ggppdk** [comment]
I ll fix this.
I have made a change to make filters appear in Joomla backend and the FILTERING layouts are no longer found when current component is not com_flexicontent

i have run a test and we confirm the issue below, it is try to find layout in current component
e.g. it is trying /components/com_newsfeeds/layouts

Layout: items_list_filters.select_selectmul
Include Paths: Array
(
    [0] => /joomla3xxdev\templates/protostar/html/layouts/com_newsfeeds
    [1] => /joomla3xxdev/components/com_newsfeeds/layouts
    [2] => /joomla3xxdev/templates/protostar/html/layouts
    [3] => /joomla3xxdev/layouts
)
 
Searching layout for: items_list_filters/select_selectmul.php
Unable to find layout:  items_list_filters.select_selectmul

**Comment by ggppdk** [comment]
Fixed with 3db7d2e81
