### ISSUE TITLE
[fc_field image] Low image quality because of srcset

### ISSUE THREAD

**Issue by NGXG** [FLEXIcontent/flexicontent-cck#985]
Hello,

with some high-quality image based templates, image quality isn't satisfying because of the min-width based that stretch lower-sized thumbnails.

For exemple, on a design i use m_size thumbnail for category view (400w) and l_size for item view (1920w). Because of srcset, using image width as breakpoint, the displayed pic was the 400w on a HD screen (I use image as background in this template, and didn't wanted to set m_size bigger to keep catview well optimized).

The solution for me was to modify FC image plugin to get a param that allow me to choose min-based or max-based srcset.
I made it on a live website and it's working great. I wanted to push a commit but i read that i should always submit an issue before pushing a commit.

Should I wait someone to attribute issue to me or may I push a commit directly ?

**Comment by micker** [comment]
hello i think the best way is to fork and do a pr we will happy to review and merge !

**Comment by ggppdk** [comment]
I understand setting the max-width to real image width will solve your issue
I mean your PR makes sense

but please note
- that it is the CSS for "width" that can stretches an image not the "min-width"

e.g. if CSS for width is 100% then this will cause the image to be stretched
- we had such CSS and we removed it recently. 
- plus another issue with quality was that the real image width in some case was not calculated correctly

I mean your issue may be already fixed !!
In any case i have merged your PR , just i added the new parameter per thumbnail size
![min-max-width-limit](https://user-images.githubusercontent.com/5092940/85806014-926e6400-b756-11ea-9754-307df7255a84.png)
