### ISSUE TITLE
https://www.flexicontent.org/ Banned

### ISSUE THREAD

**Issue by iamrobert** [FLEXIcontent/flexicontent-cck#991]
Hi,

I logged in to FLEXIcontent forum (https://www.flexicontent.org/forum/) to post a question and first it showed a 500 error and now I am banned and blocked from viewing the site:

![Image of ban](https://i.imgur.com/suBGKUY.png)

It says I'm banned from this extension:
https://www.flexicontent.org/index.php?option=com_rantispam&view=banned

Hope that helps. I would hate to be blocked from the community.

**Comment by micker** [comment]
lol sorry its an ip problem
can you send me yannick@com3elles.Com
regards

**Comment by rubenreyes2000** [comment]
@iamrobert you should not be spamming the forum 🤣🤣🤣
