### ISSUE TITLE
Image field load elastic slide js effect in category view

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#998]
In category view elastick slide js galery is loading (if useed or not) that can broke other js like carroussel display
exemple here
http://flexidemo.com3elles.com/recipe/

**Comment by ggppdk** [comment]
hhmm,
The JS of galleriffic layout is loaded, but the HTML of the image-gallery field is missing from the page
this causes the JS error

The loading of JS is field 's display was created is expected !
But we should not have a JS error if the layout does not add the field's HTML into the page ...
Need to fix this

**Comment by micker** [comment]
ok cool
