### ISSUE TITLE
repetable field can't works on image field

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#999]
Repeatable field can't works on image field
i try to add this in pannellum layout to create multi point system
but i think we have a conflict with Ajax loading

**Comment by ggppdk** [comment]
I am not sure that i understand you ,
is this specific issue specific to the pannellumlayout of the image-gallery field ?

**Comment by micker** [comment]
no i think repetable field (joomla field) can't works with ajax option loading
![2021-01-04_08h49_02](https://user-images.githubusercontent.com/2539440/103512817-b929f780-4e69-11eb-9538-b838dcd777cf.png)

i add this code
<field name="" type="separator" default="FLEXI_HOTS_SPOTS_TITLE" level="level1" />
			<field
	name="hotspot"
	type="subform"
	label="FLEXI_HOT_SPOTS_LABEL"
	description="FLEXI_HOT_SPOTS_DESC"
	multiple="true"
	min="1"
	max="100"
	>
	<form>
		<field
			name="pitch"
			type="number"
			label="FLEXI_HOTS_SPOTS_PITCH"
			description="FLEXI_HOTS_SPOTS_PITCH_DESC"
			/>
			<field
			name="yaw"
			type="number"
			label="FLEXI_HOTS_SPOTS_YAW"
			description="FLEXI_HOTS_SPOTS_YAW_DESC"
			/>
		<field
			name="hot_spot_text"
			type="textarea"
			label="FLEXI_HOTS_SPOTS_TEXT"
			cols="40"
			rows="8"
			description="FLEXI_HOTS_SPOTS_TEXT_DESC"
			/>
			<field
			name="hot_spot_url"
			type="url"
			label="FLEXI_HOTS_SPOTS_URL"
			description="FLEXI_HOTS_SPOTS_URL_DESC"
			/>
	</form>
</field>

**Comment by micker** [comment]
https://github.com/FLEXIcontent/flexicontent-cck/issues/1031
